### PR TITLE
fix(messaging,ios): hasPermission checks authorizationStatus

### PR DESCRIPTION
**Pull request by dulmandakh**
### Summary

hasPermission checked if alert notification enabled and returned false on iOS 12 and up when provisional permission granted or Notification Center is enabled. This PR changes hasPermission to check authorizationStatus is equal to or above UNAuthorizationStatusAuthorized (value is 2), because it might be a UNAuthorizationStatusProvisional(value is 3).

Previously, on iOS 12 requestPermission would return true, but hasPermission returned false. This PR fixes it, and both return true.

See https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[CATEGORY][type] [LOCATION] - Message

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dulmandakh** [comment]
Maybe we need to change API to return permission details as object like { authorized: true, badge: true, alert: true, provisional: false }

**Comment by dulmandakh** [comment]
@Ehesp @Salakar please review and merge

**Comment by mikehardy** [comment]
Would likely be better to collaborate with react-native-permissions, these are all solved problems over there? https://github.com/react-native-community/react-native-permissions/#checknotifications

I use it successfully

**Comment by Salakar** [comment]
> Maybe we need to change API to return permission details as object like { authorized: true, badge: true, alert: true, provisional: false }

This is planned for v7 - as its a breaking change, we wanted to do it for v6 but had time constraints. We may also consider deprecating the api entirely to allow use of `react-native-community/react-native-permissions` instead.

----


This change does look good to me though.

**Pull request merged**
