### PR TITLE
refactor(*): load Android Gradle Plugin conditionally

### PR DESCRIPTION
**Pull request by SaeedZhiany**
### Summary

This wraps the Android Gradle plugin dependency in the buildscripts section of android/build.gradle in a conditional:

```
if (project == rootProject) {
    // ... (dependency here)
}
```

The Android Gradle plugin is only required when opening the project stand-alone, not when it is included as a dependency. By doing this, the project opens correctly in Android Studio, and it can also be consumed as a native module dependency from an application project without affecting the app project (avoiding unnecessary downloads/conflicts/etc).

for more info, you can refer to [this thread](https://github.com/facebook/react-native/pull/25569) and especially [this comment.](https://github.com/facebook/react-native/pull/25569#issuecomment-532504277)

### Checklist

- [x] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[INTERNAL] [ENHANCEMENT] [ALL MODULES] - Load Android Gradle Plugin only when the android projects of each module opened as a stand-alone project in Android Studio.

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@Ehesp, @mikehardy

please review this.

**Comment by mikehardy** [comment]
@Salakar - this style, conditional loading, was arrived at after a good collaboration and I've adopted it in my modules. You get nitty-gritty with build systems as well and you weren't in the initial collaboration so maybe you know something we don't, but these seemed like the cleanest solution we could find to modules all having their own (out of date) gradles when you built a work project. So I approve in general, FWIW

**Comment by SaeedZhiany** [comment]
> Hey @SaeedZhiany ! Fancy meeting you in react-native-firebase :-), looks like this change is slowly rippling out across the popular modules, good to see. My only hesitation here is not structural or stylistic - I just think you need to run ./gradlew wrapper as well? I don't see the wrapper change included even though you bumped the gradle ver, and I think it would change?

Hey @mikehardy!
Thanks for reviewing this. yes, you're right I almost forgot to upgrade gradle wrapper versions. is it OK to upgrade to version 5.6.4? or it should be upgraded to v6.0?

**Comment by SaeedZhiany** [comment]
> Hey @SaeedZhiany ! Fancy meeting you in react-native-firebase :-), looks like this change is slowly rippling out across the popular modules, good to see. My only hesitation here is not structural or stylistic - I just think you need to run ./gradlew wrapper as well? I don't see the wrapper change included even though you bumped the gradle ver, and I think it would change?

Hey @mikehardy!
Thanks for reviewing this. yes, you're right I almost forgot to upgrade gradle wrapper versions. is it OK to upgrade to version 5.6.4? or it should be upgraded to v6.0?
is it necessary to run `./gradlew wrapper`, I can upgrade all versions manually in each file.

**Comment by SaeedZhiany** [comment]
> Hey @SaeedZhiany ! Fancy meeting you in react-native-firebase :-), looks like this change is slowly rippling out across the popular modules, good to see. My only hesitation here is not structural or stylistic - I just think you need to run ./gradlew wrapper as well? I don't see the wrapper change included even though you bumped the gradle ver, and I think it would change?

Hey @mikehardy!
Thanks for reviewing this. yes, you're right I almost forgot to upgrade gradle wrapper versions. is it OK to upgrade to version 5.6.4? or it should be upgraded to v6.0?
is it necessary to run `./gradlew wrapper`? I can upgrade all versions manually in each file.

**Comment by SaeedZhiany** [comment]
> Hey @SaeedZhiany ! Fancy meeting you in react-native-firebase :-), looks like this change is slowly rippling out across the popular modules, good to see. My only hesitation here is not structural or stylistic - I just think you need to run ./gradlew wrapper as well? I don't see the wrapper change included even though you bumped the gradle ver, and I think it would change?

Hey @mikehardy!
Thanks for reviewing this. yes, you're right I almost forgot to upgrade gradle wrapper versions. is it OK to upgrade to version 5.6.4? or it should be upgraded to v6.0?
run `./gradlew wrapper` (for example in the android folder of AdMob package) shows me an error message that `compileSdkVersion could not found`.
it seems `compileSdkVersion` must be in `app`'s gradle file which I could not see it either. 
could you help me with that?

**Comment by SaeedZhiany** [comment]
> Hey @SaeedZhiany ! Fancy meeting you in react-native-firebase :-), looks like this change is slowly rippling out across the popular modules, good to see. My only hesitation here is not structural or stylistic - I just think you need to run ./gradlew wrapper as well? I don't see the wrapper change included even though you bumped the gradle ver, and I think it would change?

Hey @mikehardy!
Thanks for reviewing this. yes, you're right I almost forgot to upgrade gradle wrapper versions. is it OK to upgrade to version 5.6.4? or it should be upgraded to v6.0?
run `./gradlew wrapper` (for example in the android folder of AdMob package) shows me an error message that `compileSdkVersion could not found`.
it seems `compileSdkVersion` must be in `app`'s gradle file which I could not see it either. 
could you help me with that, please?

**Comment by SaeedZhiany** [comment]
@mikehardy 
I could not run `gradlew wrapper` command on the projects, I create a new android project in android studio and I saw that it create with gradle wrapper 5.4.1, just like the current projects of this repository. then I run `gradlew wrapper --gradle-version 5.6.4 --distribution-type all` on my project and it successfully upgraded to 5.6.4.

then I try to copy and paste of `gradlew`, `gradlew.bat`, and `gradle-wrapper.properties` content in all Android projects of this repository. I hope this isn't wrong.

Also, I saw in some `gradle/wrapper` folders there is `gradle-wrapper.jar` file and so it is an auto-generated file when opening the project as a stand-alone project, I remove them from all projects (only 6 projects have the jar file), if any further work needed about this, let me know.

**Comment by SaeedZhiany** [comment]
Oops, android build has been failed, maybe I should not remove all `gradle-wrapper.jar` files, right?
which ones must remain in the repository? the jar files of `test/android` and `packages/template/android`?

**Comment by SaeedZhiany** [comment]
@mikehardy 
I could not run `gradlew wrapper` command on the projects, I create a new android project in android studio and I saw that it create with gradle wrapper 5.4.1, just like the current projects of this repository. then I run `gradlew wrapper --gradle-version 5.6.4 --distribution-type all` on my project and it successfully upgraded to 5.6.4.

then I try to copy and paste of `gradlew`, `gradlew.bat`, and `gradle-wrapper.properties` content in all Android projects of this repository. I hope this isn't wrong.

Also, I saw in some `gradle/wrapper` folders there is `gradle-wrapper.jar` file and so it is an auto-generated file when opening the project as a stand-alone project (only 5 projects have the jar file), I remove them from three projects below,

```
packages/analytics/android/gradle/wrapper/
packages/app/android/gradle/wrapper/
packages/functions/android/gradle/wrapper/
```

and for avoiding CI builds failures I replaced a new `gradle-wrapper.jar` generated from `gradlew wrapper` in two directories below:

```
packages/template/project/android/gradle/wrapper/
test/android/gradle/wrapper/
```

if any further work needed about this, let me know.

**Comment by Salakar** [comment]
PR and related links makes sense to me, thanks for providing the context @mikehardy and thanks @SaeedZhiany for sorting this PR 🎉 

> and for avoiding CI builds failures I replaced a new `gradle-wrapper.jar` generated from `gradlew wrapper` in two directories below:
> 
> ```
> packages/template/project/android/gradle/wrapper/
> test/android/gradle/wrapper/
> ```

Thanks for sorting this, I can confirm the wrapper in these two directories should remain as these are actual Android app projects, but everywhere else can be removed - so thanks for sorting

**Comment by mikehardy** [comment]
Nice @SaeedZhiany - thanks! All the modules I work with are slowly moving towards One True Gradle download

**Pull request merged**
