### PR TITLE
Fix missing Foundation import

### PR DESCRIPTION
**Pull request by zoontek**
If we don't import the FirebaseDatabase SDK, `NSObject` will not be found.

screen shot 2017-08-10 at 22 26 18

### CODE REVIEW

**Comment by kyle-ssg** [comment]
+1

**Comment by kyle-ssg** [comment]
I'm no expert on objc but i also get a similar error on ```RNFirebaseDatabaseReference.m```, seems like it's fixed by changing ```@implementation RNFirebaseDatabase ``` to ```@implementation RNFirebaseDatabase : NSObject ```

**Comment by Ehesp** [comment]
We're just checking a few things here. Same code is in other modules (e.g. Admob) but if you don't include that it doesn't complain about NSObject;

**Comment by zoontek** [comment]
@kyle-ssg I tried various fixes, this PR must be merged with https://github.com/invertase/react-native-firebase/pull/327

**Comment by phips28** [comment]
please merge!

**Comment by chrisbianca** [comment]
Just released v2.1.2 which addresses this issue more thoroughly.
@zoontek thanks for bringing it to our attention

**Comment by zoontek** [comment]
@chrisbianca Thanks you for fixing the issue!

**Pull request closed without merging**
