### PR TITLE
docs(analytics): correct NavigationController to `NavigationContainer`

### PR DESCRIPTION
**Pull request by JDMathew**
### Description
The reference to `NavigationController` should be `NavigationContainer`

### Checklist

- I read the [Contributor Guide](../blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Indeed - thanks for the catch!

**Comment by mikehardy** [comment]
@JDMathew just waiting on you to sign the CLA and I'll merge this in, thanks!

**Comment by mikehardy** [comment]
@JDMathew will close unmerged if the CLA is unsigned

**Comment by JDMathew** [comment]
@mikehardy have signed CLA, thanks 😃

**Comment by mikehardy** [comment]
merged! better docs for everyone thank you @JDMathew :nerd_face: :memo:

**Pull request merged**
