### PR TITLE
fix(firestore): GeoPoint latitude error message incorrectly used 'longitude'

### PR DESCRIPTION
**Pull request by zholmes1**
…range

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — DISMISSED** [review]
nice catch!

**Comment by mikehardy** [comment]
needs the CLA signed but is obviously correct, can merge when CLA is set, thanks!

**Comment by zholmes1** [comment]
Signed.

**Comment by mikehardy** [comment]
@zholmes1 irony - of *course* the error message identically wrong :facepalm: 

https://github.com/zholmes1/react-native-firebase/blob/5207a33bfe09efab7322eff7f73913ffb909faa6/packages/firestore/e2e/GeoPoint.e2e.js#L58

I just fixed that on your branch as well, tests should pass, I'll merge...

**Comment by zholmes1** [comment]
> @zholmes1 irony - of _course_ the error message identically wrong 🤦
> 
> https://github.com/zholmes1/react-native-firebase/blob/5207a33bfe09efab7322eff7f73913ffb909faa6/packages/firestore/e2e/GeoPoint.e2e.js#L58
> 
> I just fixed that on your branch as well, tests should pass, I'll merge...

🤣 Nice

**Pull request merged**
