### PR TITLE
[JS][FEATURE][FIRESTORE] - Implement isEqual in CollectionReference

### PR DESCRIPTION
**Pull request by cmmartin**
### Summary

Please see https://github.com/invertase/react-native-firebase/issues/2028#issuecomment-486053074 for context. Let me know if I missed anything here

### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [x] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
- [x] Flow types updated
- [x] Typescript types updated

🔥

### CODE REVIEW

**Comment by Salakar** [comment]
Ignore my commit - just triggering CI - it's not behaving well today 😫

**Comment by Salakar** [comment]
Will merge and test locally, CLI on v5.x.x isn't working very well.

Thanks for sending this over - appreciate it. Will patch release if all is well and let you know here.

**Comment by Glendonh** [comment]
We're migrating from the Javascript SDK to react-native-firebase and need to implement this function. Do you know when this will be published?

**Comment by Salakar** [comment]
I will cut a release of v5.x.x today

**Comment by mikehardy** [comment]
@Salakar related question - I believe the firebase-ios-sdk pods had breaking changes as they moved from 5.20.2 to 6+, beyond just moving up their API support baseline. Are you open to PRs that allow react-native-firebase 5.x to track breaking changes? There is a little precedent in the firestore timestamp thing even though obviously the semantic version stuff becomes crazy. The reason I ask is that I'd like to do some heap analysis on the ios side (I'm crashing there) but it seems pointless if I try to log a firebase-ios-sdk issue on older pods, at the same time I can't move to react-native-firebase 6.x yet :thinking:

**Comment by tsemerad** [comment]
@Salakar Do you have a time frame for the v5.x.x release? I really appreciate your work on this.

**Comment by Glendonh** [comment]
I tried making a build off of the 5.x.x branch and the resulting package failed in the same way. I ran the `build` script and published. Is there a part of the build process that I'm missing?

**Comment by Salakar** [comment]
I've tried releasing a few times now and iOS built fine but android fails to build with duplicate dependency issues relating to RN afaik, might just be the test project causing this but haven't had the time to investigate further, have already spent a few days on it 😓

If you'd like I can manually publish it as is on a separate npm tag for you to try out and confirm Android ok, all the tests are passing on iOS so I'm pretty sure its fine, just Android build being annoying 😑

**Comment by mikehardy** [comment]
@Salakar can you point to a git tag tag or commit hash that's trying to build, then I assume it's a Circle CI config that's running (or you could point to the start of the build commands) - maybe I can fuzzbust android

**Comment by Salakar** [comment]
Hey @mikehardy - thanks for the assist,

Here's the current issue: https://circleci.com/gh/invertase/react-native-firebase/4909?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

This wasn't the issue I had before, it was the android multiple dependencies versions do not satisfy version constraints or something, it was Detox and React Native dependencies clashing ([this error](https://github.com/wix/Detox/issues/1208)).

Upgrading detox to 12.5.0 'solved' that issue, but then caused other issues so had to go through updating various build tools versions, adding kotlin etc - finally landing on the above current error.

To run locally:

 - Clone v5.x.x branch
 - `yarn && cd tests && yarn`
 - `yarn run build-android` (in tests folder)

**Comment by mikehardy** [comment]
My god what a yak shave! :-) I'll give it a whirl

**Comment by Salakar** [comment]
Tell me about it 🙈 	

yak shave

**Comment by mikehardy** [comment]
Oh man, you've been AndroidX'd. There's a support vs androidx classcast issue. Plus some AAPT2 thing. You may have crossed a semver breaking change with your updates. What do you think about me moving back to the 5.3.2 then moving forward bisect?

**Comment by Salakar** [comment]
Go for it 💪

**Comment by mikehardy** [comment]
First goal, just get the current build building again. Bitrot has taken hold.

Conundrum: 
1- react-native-firebase 5.3.1 requires react-native 0.59.3+, but...
2- React-native 0.59.x requires changes only present in Detox v12, but...
3- Detox v12 is AndroidX so will not work (unless we de-jetify [their AAR build which they produce as of 12.5] (https://github.com/wix/Detox/blob/master/docs/Guide.Migration.md#migrating-from-detox-124x-to-1250-nonbreaking) but I don't want to go there right now) because RN0.59 doesn't do AndroidX, and...
4- Detox v9 won't build with XCode 10.2 because Swift v3 support was removed.

Here's the general plan then, all happening on [my fork's 5.3.1-dev branch](https://github.com/mikehardy/react-native-firebase/tree/v5.3.1-dev):

1. we will take this as an invariant
2. There is a patch floating around for this, I'll try to integrate it in a moment
3. moving to AndroidX is a nonstarter, so we I will not use Detox 12.x
4. [The Detox < v12 fix for XCode 10.2](https://github.com/wix/Detox/commit/d69327e56e7d5291b574c07ef828f13d13749eaa) was easy, so I [added in-situ patches (think patch-package, but since this is native code that blows up during install we have to go manual and altered the instructions](https://github.com/mikehardy/react-native-firebase/commit/b93c0877538e45bce52781939a54ee2f0e769198). I suppose in CI you'd have to run the yarn command that will fail with an ` || true` after it so CI doesn't blow. At first I attempted to fork Detox to add support but Detox does a lot of source processing prior to publish, so you can't just yarn add a git repo with the patch. Don't waste your time there like I did.

So where we are at now is that I have Detox 9 building successfully, but... now the react-native CLI is blowing up for me on `yarn run packager-jet`. I think in the last couple months they must have updated something and it no longer works on node 8 which you are using in CircleCI

progress, but halting.

**Comment by mikehardy** [comment]
On that branch I have android working now through `./gradlew downloadDependencies` via patch-package and the patch I mentioned, in strategy #2 above, so this may work for android now, but I still can't get the packager to start locally me. Here's the commit with the android fix - https://github.com/mikehardy/react-native-firebase/commit/3f5e5ba333c9ef97e417addfbcdae38a5e871c67

**Comment by mikehardy** [comment]
Nope - still not quite there. The AAPT error is still present because buildTools are mismatched, should just be an ext { buildTools... } fix away but out of time for now.

**Comment by mikehardy** [comment]
I have android building locally but haven't committed my changes yet. The last patch needed (or upgrade, just haven't checked compatibility) is `node_modules/jet/android/build.gradle` moving to API 28 for SDK and tools. So I think we'll have this compiling and working and the v5 branch will be releasable shortly

**Comment by Salakar** [comment]
`node_modules/jet/android/build.gradle` I can publish an update to this if needed, is one of our packages, let me know

**Comment by mikehardy** [comment]
That dependency is out of date so I'm going to see if I can upgrade it first, I'm checking both directions (patch dependency used originally for 5.3.1, and/or update package) to see what's best. Upgrades are best IMHO, I'm only patching (like detox) when the dependency incompatibilities can't be untangled

**Comment by mikehardy** [comment]
Okay, for jet you need to be using the ext reference style so the versions may be overridden: https://github.com/invertase/jet/blob/master/android/build.gradle

But you've moved to detox 12 there which is AndroidX, so I can't upgrade that dependency all the way even if you made a 0.4.1

If you did a jet version 0.3.1 using the PR I just made to jet - https://github.com/invertase/jet/pull/13 - then merging these changes will have android building I think, but not based on the tip of your branch - I started from the 5.3.1 tag and went from there.

I'll submit my changes as a PR but I expect the PR to be a mess until/unless you revert some of your work, so it won't be clean and pretty on first glance even though my changes were pretty surgical

**Comment by mikehardy** [comment]
#2166 is submitted with my work, we'll see...

**Comment by Salakar** [comment]
@cmmartin thanks to the assist from @mikehardy this is now up in v5.4.0: https://rnfirebase.io/docs/v5.x.x/releases/v5.4.x

Thanks for your patience on this 👍

**Comment by mikehardy** [comment]
I'm going to integrate this in dev builds of my app but I don't use all the firebase features, so holler if you see something blow up. Otherwise hopefully we all get to happily roll along, but with the ability for important things like this to flow through on v5. 

I'm really happy to see releases flowing again, it is a very, very closely shaven yak ;-)

**Comment by mikehardy** [comment]
My integration build appears to be working successfully FWIW, though it's in our nightly type environment so hasn't seen detailed inspection yet. Primarily using analytics, auth, firestore, messaging + notifications. Not using the rest yet. But it is up and running

**Comment by Glendonh** [comment]
I really appreciate all of the hard work to get this published. Unfortunately I'm still getting the error that isEqual is not a function. I've tried cleaning my xcode project and reinstalling node modules. @cmmartin does this version work for you?

**Comment by Salakar** [comment]
@Glendonh have you got an example of the code you're using, we have tests for this method that are successfully passing so not sure what the issue could be

**Comment by mikehardy** [comment]
You might try react-native-clean-project after install run React-native
clean-project-auto

Just to make sure 😁

**Comment by Glendonh** [comment]
We figured out our problem. I was actually passing a query and not a collection into the function that caused the crash. We are working on a pull request.

**Pull request merged**
