### PR TITLE
Enable foreground notification on ios

### PR DESCRIPTION
**Pull request by hisokakei**
Enable `show_in_foreground` flag for local notification on ios

### CODE REVIEW

**Comment by Salakar** [comment]
LGTM - thank you for the PR

**Comment by drailanjohngss** [comment]
How can I use this ?

**Comment by Ehesp** [comment]
@drailanjohngss `show_in_foreground: true` in the options object.

**Comment by drailanjohngss** [comment]
It working now, hmm but when I tested it, notifications are sent every second.

**Comment by hlbp** [comment]
hi @drailanjohngss  did you find a solution for this? 
thanks!

**Comment by kholiavko-roman** [comment]
@Ehesp Could you please help me, is 'show_in_foreground' works now ? 
I try `"show_in_foreground": true` and `"show_in_foreground":1` but it not work in current version.

**Pull request merged**
