### PR TITLE
feat(app): ios sdk 10.27.0 / android sdk 33.1.0

### PR DESCRIPTION
**Pull request by mikehardy**
Pretty standard update, however the android tests are failing for me locally, so I expect an e2e android test failure here, in the database test suite

If that occurs obviously will need to investigate for root cause, and even if it does not occur then I will need to determine what the environmental difference is such that it fails for me locally but not in CI

We'll see...

### CODE REVIEW

**Comment by mikehardy** [comment]
As sometimes happens, android simply had a slow runner so it timed out. Didn't make it to the point where it's having trouble for me locally.

Re-running.

**Comment by mikehardy** [comment]
Well, that's a failure I've never seen before.

```
  firestore().namedQuery()
    v8 compatibility
      - returns bundled QuerySnapshot
      - limits the number of documents in bundled QuerySnapshot
      - returns QuerySnapshot from firestore backend when omitting "source: cache"
      - calls onNext with QuerySnapshot from firestore backend
      - throws if invalid query name
      - calls onError if invalid query name
    modular
      ✔ returns bundled QuerySnapshot
      ✔ limits the number of documents in bundled QuerySnapshot
      - returns QuerySnapshot from firestore backend when omitting "source: cache"
      ✔ calls onNext with QuerySnapshot from firestore backend
12:04:27.437 detox[6577] ERROR: [WS_ERROR] The app has crashed, see the details below:

@Thread main(2):
java.lang.RuntimeException: Internal error in Cloud Firestore (25.0.0).
	at com.google.firebase.firestore.util.AsyncQueue.lambda$panic$3(AsyncQueue.java:545)
	at com.google.firebase.firestore.util.AsyncQueue$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: java.lang.IllegalArgumentException: Unknown change type set
	at com.google.firebase.firestore.remote.RemoteSerializer.decodeWatchChange(RemoteSerializer.java:1006)
	at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:107)
	at com.google.firebase.firestore.remote.WatchStream.onNext(WatchStream.java:38)
	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.lambda$onNext$1$com-google-firebase-firestore-remote-AbstractStream$StreamObserver(AbstractStream.java:119)
	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at com.google.firebase.firestore.remote.AbstractStream$CloseGuardedRunner.run(AbstractStream.java:67)
	at com.google.firebase.firestore.remote.AbstractStream$StreamObserver.onNext(AbstractStream.java:110)
	at com.google.firebase.firestore.remote.FirestoreChannel$1.onMessage(FirestoreChannel.java:140)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:660)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:647)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
	at java.lang.Thread.run(Thread.java:1012)
```

re-running to see if persistent or flake

**Comment by 1337LutZ** [comment]
Would be great to have at least the iOS package updated asap since it most likely is the culprit of this issue we are facing:
- https://github.com/invertase/react-native-firebase/issues/7810

See: 
1. https://github.com/firebase/firebase-ios-sdk/issues/12629
2. https://github.com/firebase/firebase-ios-sdk/issues/12468

**Comment by mikehardy** [comment]
@1337LutZ released - also note that for things like this that are urgent for you, the "escape hatch" of being able to specify an override the firebase-ios-sdk version is always available --> https://rnfirebase.io/#ios

**Comment by 1337LutZ** [comment]
@mikehardy Awesome and thanks!
We are using Expo, so updating without pointing to your PR branch would've meant ejecting 🥲
Thanks a lot again 👏

**Comment by 1337LutZ** [comment]
In the end this didn't fix our issue, however the 10.26.0 SDK added some better logging for these kinds of issues and that is what in the end helped us. Thanks again!

**Pull request merged**
