### PR TITLE
fix: onTokenChange method causing app to crash

### PR DESCRIPTION
**Pull request by focux**
### Description

After being several days trying to find what was causing my app to crash with a very undetailed message:
```
TypeError: Properties can only be defined on Objects
```
I found that the error is due to calling `onTokenChange` method from the messaging package. It was trying to define a new property in a string instead of doing it in his proto. Also, it seems that bug what's introduced by this commit 1940d6c8fbab64ccf739186cea9633a605237942.

### Release Summary

Fix onTokenChange bug that was crashing app.

### Checklist

- I read the [Contributor Guide](/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [x] Yes
  - [ ] No

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by Salakar** [comment]
Is this Hermes by any chance? Guessing it is

Also we're planning on removing this now, was just a hacky backwards compatibility fix - though I'm fine to merge this fix until we remove it

**Comment by focux** [comment]
Actually no, it’s not Hermes. I’m using the default engine and RN 0.60 if it matter.

**Comment by Salakar** [comment]
Thanks for replying - I'd be inclined then to just remove the work around entirely then I think, let's remove the `Object.defineProperty` and change `listener(tokenStringWithTokenAccessor);` to `listener(token);`.

Each RNFirebase package is independently versioned so I don't see any harm in going ahead with the breaking change now - if you don't mind making the change?

Once merged a new semver major of messaging will get automatically published to NPM, so can get this out pretty quickly

**Comment by focux** [comment]
Great! I just pushed the requested changes. Let me know if it's okay or if you want to change anything.

**Comment by Salakar** [comment]
Awesome, thanks! I'll get this reviewed and released tomorrow (late here) 🎉

**Comment by alexfoxy** [comment]
@Salakar getting this issue, when will this fix be merged into a release?

**Comment by mikehardy** [comment]
@focux check out the `patch-package` package - if you try it yourself and it works, you have a nice persistent (across CI other devs etc) fix locally plus you can report success here - win/win

**Comment by focux** [comment]
> @focux check out the `patch-package` package - if you try it yourself and it works, you have a nice persistent (across CI other devs etc) fix locally plus you can report success here - win/win

Actually, I already use `patch-package` and I applied the fix since day one, it's working well. We just need to get this PR merged and publish a new major. I think that @Salakar was going to do that.

**Comment by Salakar** [comment]
Batching a few commits into the next release (nothing extreme) so will manually trigger a release tomorrow, sorry for the delay :see_no_evil:

**Comment by focux** [comment]
Love it. Thank you.

**Comment by smxdevst** [comment]
Any updates when this one will be publishing? @Salakar

**Pull request merged**
