### PR TITLE
[bugfix] fix string values are incorrectly coerced into int

### PR DESCRIPTION
**Pull request by novasponge**
### Summary

Fix [issue 2457](https://github.com/invertase/react-native-firebase/issues/2457)
### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[CATEGORY][type] [LOCATION] - Message

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by novasponge** [comment]
I have signed the contributor license but somehow the job still thinks I have not signed it yet.

**Comment by mikehardy** [comment]
Usually it’s an email address vs github-known-email-address issue as stated in the message: “If you have already a GitHub account, please add the email address used for this commit to your account.”

**Comment by Salakar** [comment]
Hey, this has been published in 0.1.4, thanks again for sending this over.

**Comment by novasponge** [comment]
My pleasure 😊

**Pull request merged**
