### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by asood123**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/react-native-firebase ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)]
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by Salakar** [comment]
@asood123 thanks for sorting this :)

**Comment by vovkasm** [comment]
And this slowdown `npm install` for all projects that use this module, on CI also... Thank you people :-(

**Comment by chrisbianca** [comment]
@vovkasm I think you're slightly exaggerating the impact this has on `npm install`.  Perhaps you should take some time to consider why we've added open collective in the first place?

Open source is fantastic, but it doesn't appear out of nowhere - it takes an incredible amount of effort and time to produce a library like this, which you and anybody else out there are subsequently able to take advantage of for free.  Open collective is one way for people to give something back to show their appreciation.

Ungrateful comments like this highlight a complete lack of understanding for the wider open source community.

**Comment by vovkasm** [comment]
@chrisbianca Just imagine. Each of ~900 OSS libraries which your project depends on will make additional network calls and show banners on half screen when your just do `rm -rf node_modules && npm install`. Does it feel good for you, do you expect developers to be happy with this? )))

**Comment by chrisbianca** [comment]
@vovkasm Wow, you really are as ungrateful as you came across initially, you should be ashamed of yourself.

What are you going to do when many of those 900 OSS libraries can't sustain themselves anymore so your nice shiny app has a security vulnerability, or can no longer be upgraded to use the latest functionality?

**Comment by vovkasm** [comment]
Ok, I will go my way. Last message on this topic.

1. I hope that this thread will be signal to authors. Signal to think more about methods to advertise people to contribute. Because:
 a. Not the fact that banner on `npm install` is helping now.
 b. It will be completely useless if there are more than one such banners.
 c. It most visible to people that can contribute time and code. People that can contribute money will not see this banner because they not read text consoles.
2. This implementation make the development experience worse:
 a. It increase installation time for **each** install
 b. It deserves usual npm <-> terminal interoperation, e.g. it ignore `--silent` flag

> What are you going to do when many of those 900 OSS libraries can't sustain themselves anymore so your nice shiny app has a security vulnerability, or can no longer be upgraded to use the latest functionality?

When I found that some library not working for me, I look around, how can I solve this. If I can use another library, I will try. If not I will fix the library and contribute, if my contribution not needed or ignored, I will fork the library.

I'm sorry if you thought I was not grateful. This is great library and I'm really grateful to the people who created it and support it. My comment applies to the only thing - the banner on npm install.

**Pull request merged**
