### PR TITLE
docs(analytics): address common DebugView confusion

### PR DESCRIPTION
**Pull request by fivecar**
The internet (and I) are often puzzled about why analytics events don't show up in DebugView. I've looked this up in new projects so many times that I think it'd help to add this to the official documention.

Thank you so much!

:fire:

### Description

Clarifying a common question on StackOverflow, and a thing I always forget when using RNFirebase in a new project.

### Release Summary

Instructions on how to get analytics events to show up in debug builds in Firebase Console's DebugView

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Loaded the modified md file in an md previewer. Here it is in VS Code:
image

### CODE REVIEW

**Comment by fivecar** [comment]
Updated! New look:
image

@mikehardy : thank you for such constructive (and instructive) feedback. I see your comments across Github projects and have benefitted a bunch from them. Long time listener, first time caller, etc etc. Thank you! 🔥

**Review by mikehardy — APPROVED** [review]
I like it - there are more than enough breadcrumbs in here for people to be able to put it together via search even if the links break (it happens...) but it should hopefully get people the actual steps as is now. Glad my comments scattered around react-native ecosystem have helped. It can get messy at times, lots of pieces to put together (and document the putting together ;-) ). Cheers

**Comment by mikehardy** [comment]
CI running now - it may need some spelling or linting additions, I can handle those to push this through but there's no getting around the CLA check if you could check the comments / details link on that one and do the needful, we can get this in. Cheers

**Comment by fivecar** [comment]
@mikehardy : CLA done. I updated the text because spelling & grammar claimed Prettier wasn't passing, but I've verified that the change is prettier-clean. Happy to make other necessary changes as long as it's clear what I need to do.

**Review by mikehardy — DISMISSED** [review]

**Comment by mikehardy** [comment]
```bash
gh pr checkout 6778
yarn lint:markdown --write
git push
```

should fix it up...

**Comment by mikehardy** [comment]
added DebugView to spellcheck dictionary

**Comment by fivecar** [comment]
Awesome -- thanks for teaching me again, @mikehardy. Really appreciate it.

**Pull request merged**
