### PR TITLE
bug(analytics): logEvent params can be objects

### PR DESCRIPTION
**Pull request by russellwheatley**
addresses: #2876

### Checklist

- [ ] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[CATEGORY][type] [LOCATION] - Message

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Salakar** [comment]
My guess is you're not finished on this yet but just in case; the tests would need updating also for this change; 

image

**Comment by russellwheatley** [comment]
@Salakar tests pass on this one. If you're happy, I'll merge locally with master, push up & get this merged in.

**Comment by Salakar** [comment]
@russellwheatley LGTM

**Comment by jmschlmrs** [comment]
Is there a way that I can track upcoming releases? Looking forward to this fix 👍

**Comment by russellwheatley** [comment]
@jmschlmrs we have a [release](https://invertase.io/oss/react-native-firebase/releases) page on the docs site. This came out as a patch on [v6.3.0](https://invertase.io/oss/react-native-firebase/releases/v6.3.0). Therefore, the latest version 6.3.4 has this change. 

FYI, we have mimicked the behaviour of the Firebase Analytics web SDK.

**Comment by jmschlmrs** [comment]
> FYI, we have mimicked the behaviour of the Firebase Analytics web SDK.

That's perfect as my use case is an abstraction to be used both for React Native and the web.

**Comment by jmschlmrs** [comment]
@russellwheatley I'm not convinced this fix shipped in v6.3.4. I am still running into the issue:
Screen Shot 2020-03-05 at 9 32 25 AM

v6.3.4 is not tagged in https://github.com/invertase/react-native-firebase/releases, but I noticed that when looking at the commit history for master (https://github.com/invertase/react-native-firebase/compare/v6.3.0...master), the commit with `bug(analytics): logEvent params can be objects (#3219)` (Feb 18) comes after the commit for `v6.3.4` (Feb 17).

Can we maybe get a 6.3.5 release?

**Comment by russellwheatley** [comment]
@jmschlmrs I am sorry, you are correct. We're currently working on v7 features at the moment so we aren't planning any further releases on v6 I'm afraid.

**Comment by plaa** [comment]
@russellwheatley @Salakar The type definitions have not been updated to allow other types: 
https://github.com/invertase/react-native-firebase/blob/master/packages/analytics/lib/index.d.ts#L673

**Comment by Salakar** [comment]
@plaa fixed in https://github.com/invertase/react-native-firebase/commit/65ec7eb431712f8c4d3cf96c24489e6a13ef4e13

We'll add this to v6.4.0 release later this week - we decided to do one last minor v6.x release to address [messaging issues](https://github.com/invertase/react-native-firebase/pull/3339)

**Comment by plaa** [comment]
@Salakar Thanks for the quick reaction! How about the review comment I added?  Has this PR been tested using nested objects and arrays?

This PR brings in the code:

```
if (isObject(value) || isArray(value)) {
    params[key] = value.toString();
}
```

The intent seems to be to convert the objects and arrays into strings?  [Firebase's own examples](https://firebase.google.com/docs/analytics/events?platform=web#log_events_3) passes objects and arrays directly to the library (though Android + iOS examples don't contain similar nested arrays).

Also if `value` is an object or array, then `value.toString()` will always be `"[object Object]"`.  I can't see how this code could be functional.

**Comment by russellwheatley** [comment]
Hi @plaa, `logEvents` using the web SDK also prints strings out of objects on the firebase console. I'm pretty sure that nested object in the array would also be `[object Object]` in the console.

**Comment by plaa** [comment]
@Salakar @russellwheatley I created PR #3351 that fixes the issue.  It simply removes the object / array mangling code, allowing passing them as-is to the Firebase native libraries.

We've been trying to get our analytics working for two days, and finally got the item details to pass through to GTM + Ecommerce using this patched version by passing the details within the `items` array (mode details in the PR).

I hope this can be included in the 6.4.0 release, as the current analytics code is completely broken for arrays/objects, and we cannot get item details into our analytics without it.

**Pull request merged**
