### PR TITLE
fix(analytics): import using package name not relative path

### PR DESCRIPTION
**Pull request by ttkien**
### Description
This is an easy PR. I updated `../../app/lib/common` by '@react-native-firebase/app/lib/common'

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan
- App does not crash when it's opened

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Hey @ttkien thank you!

I like this change, but can you update the PR with some information about *why* the change is needed? Additionally the PR title is meaningless and not conventional

Something like this is "[conventional](https://www.conventionalcommits.org/)" and meaningful:

`fix(analytics): import using package name not relative path`

**Comment by ttkien** [comment]
> Hey @ttkien thank you!
> 
> I like this change, but can you update the PR with some information about _why_ the change is needed? Additionally the PR title is meaningless and not conventional
> 
> Something like this is "[conventional](https://www.conventionalcommits.org/)" and meaningful:
> 
> `fix(analytics): import using package name not relative path`
Thank for your suggestion. I updated it

**Comment by mikehardy** [comment]
Nice! just merged it and I'm still working on the analytics-without-ad-id pod subspec, hope to have it shortly so I can do a release with it. Maybe today? If not, should be tomorrow. Thanks for your help!

**Comment by mikehardy** [comment]
Release 11.4.1 just went out with the change related to this among other fixes + features. Enjoy! :rocket:

**Pull request merged**
