### PR TITLE
[IOS][BUGFIX][ADMOB] - add new iOS framework search path (release)

### PR DESCRIPTION
**Pull request by inomn**
Do the same as https://github.com/invertase/react-native-firebase/pull/2414 for Release search paths

### Summary

Add new iOS framework search path for Release build

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan
The same as https://github.com/invertase/react-native-firebase/pull/2414 but with Release builds

### Release Plan

[IOS][BUGFIX][ADMOB] - Add new iOS code path to Xcode project

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
@Salakar I don't see anything wrong with this, worst case it adds a directory to the search path that does not exist, which meets the standard of "does no harm", correct?

If so I am strongly inclined to merge so that people can at least depend on the branch or the specific commit-hash, even if we are blocked from full release by CI. Opinion?

**Comment by mikehardy** [comment]
and @inomn - thank you!

**Comment by inomn** [comment]
@mikehardy @Salakar any updates on this PR?

**Comment by mikehardy** [comment]
In the interim I would at least use patch-package to integrate it nicely locally, based off the current commit-hash of the v5.x.x. branch on git. All sounds a little off but it will be 100% reproducible on any machine (CI or colleague etc) until it's merged and/or v5 CI is unblocked allowing for a real npmjs.com release

**Comment by mikehardy** [comment]
Also @inomn - the CLA still isn't signed? That happens if email address in github is unexpected for some reason, but the CLA does need to be signed

**Comment by inomn** [comment]
@mikehardy sorry, just signed it.

**Comment by Salakar** [comment]
Sorry for the delay on seeing this @mikehardy, you're correct that either way this won't cause any harm

**Comment by mikehardy** [comment]
I have manually pulled your fork and cherry-picked this commit into my patch queue for v5.5.7 - I won't update this PR again (except to close it if it does not auto-close) but if you see v5.5.7 (should be tonight or tomorrow) it will be in there. Thanks for your patience and for submitting this!

**Pull request closed without merging**
