### PR TITLE
fix: correct androidResolutionForPlayServices API

### LINKED ISSUE #3864: [Play Services utilities] resolutionForPlayServices
## Issue

`resolutionForPlayServices` don't work.

## Reason

[Here is](https://github.com/invertase/react-native-firebase/blob/master/packages/app/lib/utils/index.js#L72) should be
 ```
return this.native.androidResolutionForPlayServices();
```
instead
```
return this.native.androidGetPlayServicesStatus();
```

### PR DESCRIPTION
**Pull request by mikehardy**
### Description
Previously was calling the incorrect native API from JS
With thanks to @Bardiamist for reporting

### Related issues
Fixes #3864

### Release Summary

fix(android): call correct androidResolutionForPlayServices API (#3864)

### Checklist

- I read the [Contributor Guide](/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Note that this is not covered by e2e testing in the original PR and I'm not sure how to effectively do so without creating a great deal of test infrastructure right now to mock out all the underlying GMS play services availability stuff, so I went with the one-liner that will make it correct now

**Comment by Ehesp** [comment]
LGTM - not sure how this one passed through 😕

**Comment by mikehardy** [comment]
I think it's just a "humans aren't robots" issue w.r.t. how it got through :-). But we're pretty collaborative so everything works as time approaches infinity

**Comment by mikehardy** [comment]
CI is still pretty flaky on the android e2e "emulator starts + app is installed + detox starts and connects + tests start" hookup

Can't be related to the PR because the PR doesn't touch an API that has cover :shrug: 

```

detox[4839] INFO:  at node_modules/jet/lib/node/console.js:16:15 
 Running "testing" with {"rootTag":21}
[Wed Jul 01 2020 16:25:23.879]  LOG      JavaScript logs will appear in your environment console
  1) "before all" hook in "{root}"
detox[4839] INFO:  at e2e/init.js:53:11 
  ✨ Tests Complete ✨ 
detox[4839] ERROR: [DetoxExportWrapper.js/DETOX_INIT_ERROR] 
 { DetoxRuntimeError: Failed to run application on the device

HINT: Most likely, your tests have timed out and called detox.cleanup() while it was waiting for "ready" message (over WebSocket) from the instrumentation process.
    at EmulatorDriver._getInstrumentationCrashError (/Users/runner/work/react-native-firebase/react-native-firebase/tests/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:165:12)
    at EmulatorDriver.instrumentationCloseListener (/Users/runner/work/react-native-firebase/react-native-firebase/tests/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:128:67)
    at EmulatorDriver._terminateInstrumentation (/Users/runner/work/react-native-firebase/react-native-firebase/tests/node_modules/detox/src/devices/drivers/android/AndroidDriver.js:156:12) name: 'DetoxRuntimeError' }

  0 passing (6m)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 360000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  

```

**Pull request merged**
