### PR TITLE
Fixes bug when presenting Interstitial and RewardedVideo

### PR DESCRIPTION
**Pull request by ianzitow**
This pull request is intended to avoid problems with view hierarchy in iOS by finding out what is the top most view controller being shown.

### CODE REVIEW

**Comment by Ehesp** [comment]
@ianzitow thanks very much for this & sorry for the delay. Although this looks fine to me, what cases are you having where the view controller isn't the top one already? 

My iOS knowledge is fairly limited, but I was under the impression RN used a single VC?

**Comment by ianzitow** [comment]
@Ehesp Looks like when using React Native Navigation by Wix, it really pushes new VC on top of another, which can cause this kind of issue: "Warning: Attempt to present VC1 on VC2 whose view is not in the window hierarchy!" #263. 

I noticed that the current code assumes the iOS app just needs a single VC since it tries to present always from a root VC. Thus, I think it need to be extended so we can avoid problems when the root itself is not the top.

However, let me run more tests to confirm everything is fine.

**Comment by ovaris** [comment]
@ianzitow any progress on this? ;)

**Comment by Salakar** [comment]
Closing as stale, no responses from original author for several months. Happy to re-open on request. We'll internally look into this as part of the AdMob re-write if not, sometime in the future.

Thanks

**Comment by nenjamin2405** [comment]
Any update on this guys, currently I'm facing this issue :(

**Comment by daheeahn** [comment]
I still faced same issue.

**Pull request closed without merging**
