### PR TITLE
feat(auth): Add Expo support for phone auth

### PR DESCRIPTION
**Pull request by DoctorJohn**
### Description

I rebase #6167 on main after #6472 stalled.
I also added a missing info plist value check and removed a duplicated app.json config key existance check.
Also added some tests for the config plugin. Let's see whether this makes CI happy :)

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Compared plugin with [official setup instructions for iOS](https://firebase.google.com/docs/auth/ios/phone-auth#set-up-recaptcha-verification) and confirmed that [Android doesn't need any extra steps](https://firebase.google.com/docs/auth/android/phone-auth).
Also added some tests to verify the plugin does what it's supposed to do.

:fire: :)

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
I just bumped the config plugin dep to v5 (along with a trivial forward port for the same) to match deps from #6482 and force pushed it to get CI through - should be good to go from that

Thanks for rescuing the PR and getting it through

**Comment by barthap** [comment]
Great to see that you took care of this feature! 😀 After a brief look it looks good to me, glad you added unit tests 😉

**Comment by mikehardy** [comment]
@barthap I always appreciate the support on the Expo stuff - highly valued - thanks!

**Comment by mikehardy** [comment]
Almost unbelievably we still have a transitive dependency on the deprecated jcenter repository and they must be doing an unscheduled brownout (to surface these deps...) which failed the android build

```

* What went wrong:
Execution failed for task ':jet:dexBuilderDebugAndroidTest'.
> Could not resolve all files for configuration ':jet:debugRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :jet
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'.
               > Read timed out
```

I just fixed it I think with https://github.com/invertase/jet/releases/tag/v0.8.2 but it is not worth pushing in this PR to fix CI because the PR is ios + javascript only and those checks passed.

**Pull request merged**
