### PR TITLE
fix(ios, sdk): adopt firebase-ios-sdk 11.3.0

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

A simple bump to the firebase-ios-sdk [per request from @efstathiosntonas](https://github.com/firebase/firebase-ios-sdk/issues/13650#issuecomment-2383870609) 

### Related issues

None logged

### Release Summary

single conventional commit

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

CI should validate it 

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Note that firestore-ios-sdk-frameworks does not have an 11.3.0 in the works, this was a simple change to a single character in package.json but that's more involved, and I am not personally involved so I have no control over that one

Not sure if it's possible to just override your firebase-ios-sdk version locally @efstathiosntonas in the Podfile (perhaps with an expo plugin doing an unsafe edit literally anywhere in the file, like just adding a line at the top that has the override variable?)

**Comment by efstathiosntonas** [comment]
Hi Mike, I've been always pinning firebase on my Podfil, I never bump them before you release an rn-firebase for the reasons you mentioned above, can't tell if there are breaking changes or not on our side that's why I pinged you on ios-sdk repo.

```ruby
	$FirebaseSDKVersion = '11.3.0'
	pod 'FirebaseAppCheckInterop', '=' + "11.3.0"
	pod 'FirebaseAuthInterop', '=' + "11.3.0"
	pod 'FirebaseMessagingInterop', '=' + "11.3.0"
	pod 'FirebaseSharedSwift', '=' + "11.3.0"
	pod 'FirebaseCoreInternal', '=' + "11.3.0"
	pod 'FirebaseInstallations', '=' + "11.3.0"
	pod 'FirebaseCoreExtension', '=' + "11.3.0"
```

I've built the app but it crashed on boot, felt the same crash like with `11.2.0`, unfortunately I built on command line so no Xcode trace. Tried to create more builds on different devices but couldn't reproduce the crash, will keep trying. Given the fact that ios crashes on boot are extremely rare I'm afraid this is 11.3.0 issue again.

 I don't think we should merge this until ios-sdk repo issue has more feedback from more devs.

**Comment by efstathiosntonas** [comment]
fear came true, seems it's not fixed: 

Screenshot 2024-10-01 at 08 36 59

**Comment by mikehardy** [comment]
This should be good to go now that firestore-ios-sdk-frameworks 11.3.0 is published and seems to be working well
Cheers!

**Pull request merged**
