### PR TITLE
docs(*): update npm badge

### PR DESCRIPTION
**Pull request by Naturalclar**
### Summary

I've updated the npm badge in README, since it was still pointing at react-native-firebase v5

### Checklist

- [ ] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[GENERAL][MINOR] [README] - updated npm badge

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Naturalclar** [comment]
@mikehardy Thanks! I've missed the download badge and license badge.
Replace those badges with @react-native-firebase/app badge

**Comment by mikehardy** [comment]
@Salakar the google emulator team switched up the CLI a little bit. You need to replace 'emulator-headless' with 'emulator -no-window' as headless is now rolled into the main binary

e.g. https://github.com/ankidroid/Anki-Android/pull/5657/commits/796d53dc96bf6f4d5b432c2259d71f2909ecae80

If the CI configs were in github somehow I could PR it but I don't think it's possible?

**Comment by Salakar** [comment]
> @Salakar the google emulator team switched up the CLI a little bit. You need to replace 'emulator-headless' with 'emulator -no-window' as headless is now rolled into the main binary
> 
> e.g. [ankidroid/Anki-Android@796d53d](https://github.com/ankidroid/Anki-Android/commit/796d53dc96bf6f4d5b432c2259d71f2909ecae80)
> 
> If the CI configs were in github somehow I could PR it but I don't think it's possible?

Thanks for the heads-up, they only introduced that in May and now they've removed it again 🙈 have updated the CI

**Comment by mikehardy** [comment]
The emulator team must have staffed up big about a year ago because yes their velocity is pretty rapid right now. I would normally be irritated but for them to first recognize that headless emulation was a big deal and CI usage was vital, then to actually implement a ton of features and stabilization for that case makes me happy, so I'll give them a pass ;-). Current emulators are so much better than last year...

**Pull request merged**
