### PR TITLE
feat(android, emulator): add firebase.json config element to bypass localhost remap

### PR DESCRIPTION
**Pull request by stchristian**
### Description

I came accross a problem with emulators and the way they are handling `localhost` addresses, described [here](https://github.com/invertase/react-native-firebase/issues/4810).

I would love to see [this](https://reactnative.dev/docs/running-on-device) work with firebase emulators, when running and testing apps on real devices.

I started a discussion [here](https://github.com/invertase/react-native-firebase/discussions/5816)

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

:fire:

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
LGTM - thank you! The CI runs will produce a patch-package set that you may use immediately if you like, until this is released

We'll need the CLA signed though for sure - follow the details link there for more information if you haven't already signed it

Thanks again - I do like the toggle, I think the dev experience is better with the remapping but it's nice to not have it be mandatory

**Comment by mikehardy** [comment]
Hey @stchristian - a gentle nudge to sign the CLA, if you follow the details link from the related comment it should walk you through it. Thanks!

**Comment by stchristian** [comment]
Something went wrong with the tests:ios:test-cover. Should I care about that? @mikehardy

**Comment by stchristian** [comment]
Also, where can I see the patch package that has been producer?

**Comment by mikehardy** [comment]
They're linked off the action - should be able to see them here https://github.com/invertase/react-native-firebase/actions/runs/1464262461

**Comment by mikehardy** [comment]
boom! Thanks again

**Pull request merged**
