### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by tareqdayya**
### Summary
Expand the docs with an explanation of Crashlytics behavior in development mode.

### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [n/a] `e2e` tests added or updated in packages/**/e2e
- [n/a] Flow types updated
- [n/a] Typescript types updated

### Test Plan

Non-applicable

### Release Plan
[CATEGORY][type] [LOCATION] - Message

    CATEGORY
  [----------]      TYPE
  [ TYPES    ] [-------------]       LOCATION
  [ JS       ] [ BREAKING    ] [------------------]
  [ GENERAL  ] [ BUGFIX      ] [ {FirebaseModule} ]
  [ INTERNAL ] [ ENHANCEMENT ] [ {Filename}       ]
  [ IOS      ] [ FEATURE     ] [ {Directory}      ]   |-----------|
  [ ANDROID  ] [ MINOR       ] [ {Framework}      ] - | {Message} |
  [----------] [-------------] [------------------]   |-----------|

[GENERAL] [ENHANCEMENT] [CRASHLYTICS] - Added to the Docs

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
@tareqdayya thanks so much for this, we rely a lot on users to help with missing pieces because as maintainers we are frequently missing the perspective to know what's missing after being too close to the library for too long

After the license signing and some review we can get this (or something close, after review) merged I'm sure. There is actually a list of of reasons crashes don't show up so this could make the start of a good section saving people time in the future

**Comment by tareqdayya** [comment]
Thx for this amazing project.

On Jan 2, 2020, at 6:44 PM, Mike Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@tareqdayya<https://github.com/tareqdayya> thanks so much for this, we rely a lot on users to help with missing pieces because as maintainers we are frequently missing the perspective to know what's missing after being too close to the library for too long

After the license signing and some review we can get this (or something close, after review) merged I'm sure. There is actually a list of of reasons crashes don't show up so this could make the start of a good section saving people time in the future

**Comment by andersonaddo** [comment]
If this is ever merged, you night want to keep https://github.com/invertase/react-native-firebase/pull/3112 in mind

**Comment by mikehardy** [comment]
Good catch @andersonaddo I just re-read both and I think #3112 supercedes this, plus the CLA was never signed here

**Pull request closed without merging**
