### PR TITLE
feat(app-check): Replay Protection

### PR DESCRIPTION
**Pull request by apetta**
### Description

This PR adds the Replay Protection feature for App Check, where it provides a consumable token for single-use server calls.

### Related issues

#7394 

### Release Summary

- Introduces Replay Protection feature for App Check
- `getLimitedUseToken` Provides single-use tokens for enhanced security on the server.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Tested in a private repo with the emulator.

---

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Nice!
I think there should be entries in the index.d.ts files so that they are available in typescript?
Also, I think it should be possible to add an entry for this in the e2e test suite for app-check, that way we can see in CI that the methods really are working + not crashing (also, they will help you determine locally that they are working before pushing to the PR branch - best practice is to add an e2e test and put `.only` on it so when you run the suite locally it is super fast to run it + iterate on code changes

**Comment by apetta** [comment]
Thanks! 

I remember I couldn't get the project installed locally last time I tried, so I had to skip the tests. Will try and look at this again soon

**Comment by mikehardy** [comment]
When I took this one and attempted to add tests to it, it hung on iOS - need to investigate why but I suspect it has something to do with not being able to proxy to the currently configured provider from our custom provider, and calling the API directly on the FIRAppCheck.

It appears this new API isn't implemented on the Provider interfaces unlike getToken, for some reason, and I've got an API shape question out upstream to see if I can understand it better https://github.com/firebase/firebase-ios-sdk/issues/11284#issuecomment-1828389986

**Comment by apetta** [comment]
Thank you so much!!

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
