### PR TITLE
fix(messaging,ios): keep original UNUserNotificationCenter delegate

### LINKED ISSUE #3390: Cannot make react-native-firebase work with react-native-push-notification
## Issue

For the local notification, react-native-firebase v6 suggest me to use [these libraries](https://invertase.io/oss/react-native-firebase/v6/messaging/quick-start#local-notifications)

[react-native-push-notification](https://github.com/zo0r/react-native-push-notification)... I choose you.

I am able to create a demo project for `react-native-push-notification`, everything works perfectly. However, when I add the below package and run `pod install`, local push notification doesn't working anymore.

- `@react-native-firebase/messaging`

Please take a look guys. Many thanks

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
    "@react-native-community/async-storage": "1.7.1",
    "@react-native-community/cameraroll": "1.3.0",
    "@react-native-community/masked-view": "0.1.5",
    "@react-native-community/netinfo": "5.3.1",
    "@react-native-community/push-notification-ios": "1.1.1",
    "@react-native-firebase/app": "6.4.0-rc4",
    "@react-native-firebase/messaging": "6.4.0-rc4",
    "axios": "0.19.0",
    "moment": "2.24.0",
    "prop-types": "15.7.2",
    "ramda": "0.26.1",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-background-timer": "2.1.1",
    "react-native-camera": "3.15.1",
    "react-native-device-info": "5.4.0",
    "react-native-fs": "2.16.2",
    "react-native-gesture-handler": "1.5.3",
    "react-native-image-resizer": "1.1.0",
    "react-native-image-zoom-viewer": "2.2.27",
    "react-native-keep-awake": "4.0.0",
    "react-native-orientation-locker": "1.1.8",
    "react-native-pdf": "6.0.1",
    "react-native-push-notification": "^3.1.9",
    "react-native-reanimated": "1.4.0",
    "react-native-safe-area-context": "0.6.2",
    "react-native-screens": "2.0.0-alpha.22",
    "react-native-signature-capture": "0.4.10",
    "react-native-sound": "0.11.0",
    "react-native-splash-screen": "3.2.0",
    "react-native-vector-icons": "6.6.0",
    "react-navigation": "4.0.10",
    "react-navigation-stack": "2.0.8",
    "react-redux": "7.1.3",
    "redux": "4.0.5",
    "redux-promise": "0.6.0",
    "redux-thunk": "2.3.0",
    "rn-fetch-blob": "0.12.0",
    "uuid": "3.3.3"
```

#### `firebase.json` for react-native-firebase v6:

```json
I don't have this file
```
</p>
</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'ProjectName' do
  # Pods for ProjectName
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for ProjectName
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Firebase/Messaging'
  
  use_native_modules!
end
```

#### `AppDelegate.m`:

```objc
/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <UserNotifications/UserNotifications.h>

#if RCT_DEV
#import <React/RCTDevLoadingView.h>
#endif

#import "../../node_modules/react-native-splash-screen/ios/RNSplashScreen.h"

#import "../../node_modules/react-native-orientation-locker/iOS/RCTOrientation/Orientation.h"

// Firebase
#import <Firebase.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  
  // Fix react-native-device-info warning
  #if RCT_DEV
  [bridge moduleForClass:[RCTDevLoadingView class]];
  #endif
  // ====================================
  
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"ProjectName"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  // Splash Screen
  [RNSplashScreen show];
  // =============
  
  // Define UNUserNotificationCenter
  UNUserNotificationCenter *center = [UNUserNotificationCenter currentNotificationCenter];
  center.delegate = self;
  
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

// Push notification

// You may wonder why there is too little code here. It is exactly the same as the demo project and local notification can be triggered normally
// Called when a notification is delivered to a foreground app.
-(void)userNotificationCenter:(UNUserNotificationCenter *)center willPresentNotification:(UNNotification *)notification withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler
{
  completionHandler(UNAuthorizationOptionSound | UNAuthorizationOptionAlert | UNAuthorizationOptionBadge);
}

// Orientation

- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  return [Orientation getOrientation];
}

@end
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 155.25 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 19, 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-22 | Google APIs Intel x86 Atom, android-23 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3/11C29 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
- **`react-native-firebase` version you're using that has this issue:**
  - `v6: 6.4.0-rc4`
- **`Firebase` module(s) you're using that has the issue:**
  - `App`
  - `Messaging`
- **Are you using `TypeScript`?**
  - `Y` & `3.7.4`
  
</p>
</details>

Thank you for the great library
---

Think `react-native-firebase` is great? Please consider supporting all of the project maintainers and contributors by donating via our [Open Collective](https://opencollective.com/react-native-firebase/donate) where all contributors can submit expenses. [[Learn More]](https://invertase.io/oss/react-native-firebase/contributing/donations-expenses)

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### LINKED ISSUE #3414: 🔥Library blocks all local notification opening events on iOS
## Issue

React Native Firebase reacts to opening the app through a Cloud Messaging notification by triggering the `onNotificationOpenedApp` event. On iOS when creating a local notification using a third party library and opening the app by tapping on it, react-native-firebase blocks the event from reaching the third party library and no event is triggered, either by this library or the one that created the alert.

There's a warning in the XCode console that's related:

    UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.

The Objective-C code that blocks the event is this: https://github.com/invertase/react-native-firebase/blob/d66a6118f82005087f53b86571990fc071402153/packages/messaging/ios/RNFBMessaging/RNFBMessaging%2BUNUserNotificationCenter.m#L70-L78

I don't know much about how iOS handles events but apparently this method overrides its third-party library counterparts, and because this handler only does anything with notifications coming from Cloud Messaging, it effectively blocks handling all other notification types. Optimally this would somehow tell UNUserNotificationCenter to move on to the other handlers but I don't know how that would be done or if it's even possible.

Another solution would be to let `onNotificationOpenedApp` handle all notifications and e.g. add a flag that tells whether it's a local notification or a Cloud Messaging notification.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

N/A

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 6.4.0
- **`Firebase` module(s) you're using that has the issue:**
  - messaging
- **Are you using `TypeScript`?**
  - N/A

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by Salakar**
Keeps a reference to any original `UNUserNotificationCenter` delegates that are set before we replace the delegate with out own implementation. Internally we will also call the original delegate if our code does not already handle the delegate call (e.g. non FCM related notifications). This should keep compatibility with other RN modules that set the delegate.

 - Fixes some issues in #3367 
 - Fixes #3414
 - Fixes #3390
 - Fixes https://github.com/notifee/react-native-notifee/issues/24

### CODE REVIEW

**Comment by radko93** [comment]
I tried `v6.4.1-alpha.0` and background notifications are working. But sending a local notification is not working. On 6.3 I use `react-native-notification` to display a local notification when in foreground and it does not work with 6.4.1. I also tested `@react-native-community/push-notification-ios` to make sure but it also does not work. Another thing is that `registerNotificationOpened` from react-native-notifications is also not fired (was working on 6.3).

what I've tried:
```
const unsubscribe = messaging().onMessage(remoteMessage => {
    console.log('notificaiton', remoteMessage) // notifications is correctly reveived
    const data = remoteMessage.data
    PushNotificationIOS.presentLocalNotification({
      alertBody: 'test',
      alertTitle: 'test',
    })
  })
```

**Comment by Salakar** [comment]
@radko93 can you show me your AppDelegate.m file contents?

**Comment by radko93** [comment]
```
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import "RNNotifications.h"
// RN splash screen
#import "RNSplashScreen.h"

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

// Firebase
@import Firebase;

//Branch
#import <RNBranch/RNBranch.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  // Confiture Firebase
  [FIRApp configure];
  // react-native-notifications monitoring
  [RNNotifications startMonitorNotifications];
  // Branch
  // [RNBranch useTestInstance]; // Uncomment this line to use the test key instead of the live one.
  // Flipper
  #if DEBUG
    InitializeFlipper(application);
  #endif
  [RNBranch initSessionWithLaunchOptions:launchOptions isReferrable:YES]; // <-- add this
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"Blossom"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  [RNSplashScreen show];  // here
  return YES;
}

// Add the openURL and continueUserActivity functions
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  if (![RNBranch.branch application:app openURL:url options:options]) {
    // do other deep link routing for the Facebook SDK, Pinterest SDK, etc
  }
  return YES;
}

// Respond to Universal Links
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *restorableObjects))restorationHandler {
  BOOL handledByBranch = [[Branch getInstance] continueUserActivity:userActivity];

  return handledByBranch;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
```

**Comment by Salakar** [comment]
Have you requested permission to display  notifications and accepted? Can you show some code?

**Comment by radko93** [comment]
I'm getting remote notifications in the background so I need to have permissions.

I have something like this (using `react-native-permissions`, also removed the token handling logic for now):
```
useEffect(() => {
    let notificationsHandlerListenerUnsubscribe = () => { }
    async function requestPermission() {
      const { status } = await requestNotifications(['alert', 'sound'])
      if (status === 'granted') {
        notificationsHandlerListenerUnsubscribe = notificationsHandler()
        messaging().setBackgroundMessageHandler(() => Promise.resolve())
      }
    }

    async function registerAppWithFCM() {
      await messaging().registerDeviceForRemoteMessages()

      requestPermission()
    }
    registerAppWithFCM()
    return () => {
      notificationsHandlerListenerUnsubscribe()
    }
  }, [])
```

and `notificationHandler` is basically (+ `Notifications.events().registerNotificationOpened` from RNNotifications):
```
export const notificationsHandler = () => {
  const unsubscribe = messaging().onMessage(remoteMessage => {
    PushNotificationIOS.presentLocalNotification({
      alertBody: 'test',
      alertTitle: 'test',
    })
  })

return unsubscribe
}
```

**Comment by sivakumar-cf** [comment]
Tried to use this PR.  Still, I am not getting the AppDelegate `willPresentNotification ` or `didReceiveNotificationResponse ` callbacks. I am using version  `6.4.1-alpha.0`

**Comment by Salakar** [comment]
@sivakumar-cf I need to know more information other than 'its not working', show me your app delegate code, your code that calls registerForRemoteMessages, which libraries are you using, device or simulator, etc etc?

**Comment by sivakumarjcn** [comment]
I am using `https://github.com/zo0r/react-native-push-notification` for displaying the local notification. 
Debugged in iOS Device iPhone 7
Here is my AppDelegate.m
```@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  NSString *filePath;
  filePath = [[NSBundle mainBundle] pathForResource:@"GoogleService-Info" ofType:@"plist" ];
  FIROptions *options = [[FIROptions alloc] initWithContentsOfFile:filePath];
  [FIRApp configureWithOptions:options];

  [FIRDatabase database].persistenceEnabled = YES;
 
  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  [self.window setBackgroundColor:[UIColor blackColor]];
  self.rootViewController = [[UIViewController alloc] init];
  self.rootViewController.view = rootView;
  [self.window setRootViewController:self.rootViewController];
  [self.window makeKeyAndVisible];
  [[UNUserNotificationCenter currentNotificationCenter] setDelegate:self];
  [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];

  return YES;
}


- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge {
  #if DEBUG
    return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
  #else
    return [CodePush bundleURL];
  #endif
}

- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo
fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
  [RNCPushNotificationIOS didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
  completionHandler(UIBackgroundFetchResultNoData);
}

- (void)application:(UIApplication *)application didRegisterUserNotificationSettings:(UIUserNotificationSettings *)notificationSettings {
  [RNCPushNotificationIOS didRegisterUserNotificationSettings:notificationSettings];
}


- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
  
  if(completionHandler) completionHandler(UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionSound);
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler {
  
  if(completionHandler) completionHandler();
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification {
  [RNCPushNotificationIOS didReceiveLocalNotification:notification];
}

- (void) application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier
forLocalNotification:(UILocalNotification *)notification completionHandler:(void (^)(void))completionHandler {
  if (completionHandler) completionHandler();
}

- (void) application:(UIApplication *)application handleActionWithIdentifier:(NSString *)identifier
forRemoteNotification:(NSDictionary *)userInfo completionHandler:(void (^)(void))completionHandler {
  if (completionHandler) completionHandler();
}

- (void)application:(UIApplication *)application didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken {
  [RNCPushNotificationIOS didRegisterForRemoteNotificationsWithDeviceToken:deviceToken];
}

- (void)application:(UIApplication *)application didFailToRegisterForRemoteNotificationsWithError:(NSError *)error {
   [RNCPushNotificationIOS didFailToRegisterForRemoteNotificationsWithError:error];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
  [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];
}

@end


On React native

PushNotification.configure({
      onNotification: notification => {
        if (notification && notification.userInteraction) {
          this.notificationTapped(notification);
        }
        notification.finish(PushNotificationIOS.FetchResult.NoData);
      },
      popInitialNotification: true,
      requestPermissions: false,
    });

    messaging().onNotificationOpenedApp(remoteMessage => {
      this.notificationTapped(remoteMessage);
    });

    messaging()
      .getInitialNotification()
      .then(remoteMessage => {
        if (remoteMessage) {
          this.notificationTapped(remoteMessage);
        }
      })
      .catch(e => {
        console.log("INITIAL NOTIFICATION ERROR", e);
      });

    messaging()
      .registerDeviceForRemoteMessages()
      .then(val => {
        messaging()
          .hasPermission()
          .then(granted => {
            CFAnalytics.logNotificationPermission(granted.toString());
            messaging()
              .requestPermission()
              .then(granted => {
                if (granted) {
                  this._setUpNotificationTokens();
                }
              })
              .catch(e => {
                console.log(e);
              });
          });
      })
      .catch(e => {});
```

**Comment by sivakumar-cf** [comment]
@Salakar I am getting notifications only when the app enters background or in the Killed state, But the AppDelegate notifications delegate callbacks are not getting called due to swizzling. Is there any way I can disable firebase swizzling methods, and manually send the callbacks to react-native-firebase SDK?

**Comment by artyorsh** [comment]
@radko93 @Salakar I can confirm the package published to `next` tag works fine when testing via firebase console. The issue occurs for notifications sent by other services (SendBird in my case).

**Setup:**

```
 "@react-native-community/push-notification-ios": "^1.1.1",
 "@react-native-firebase/app": "^6.4.1-alpha.0",
 "@react-native-firebase/crashlytics": "^6.4.1-alpha.0",
 "@react-native-firebase/messaging": "^6.4.1-alpha.0",
 "@react-native-firebase/perf": "^6.4.1-alpha.0",
 "react-native-push-notification": "^3.1.9",
 "sendbird": "3.0.117",
```

**Configuration:**

AppDelegate is configured strongly by following [guides](https://github.com/react-native-community/push-notification-ios#getting-started), with no differences.
Same for configuring `messaging`.

_Note:_ not sure if it is documented, but you should also upload the certificates to firebase console (done via `project overview -> project settings -> cloud messaging`).

**Result:** Push notifications are displayed well if sent by firebase console, but not with other services.

**Comment by radko93** [comment]
@artyorsh but does it also work in foregorud?

**Comment by artyorsh** [comment]
@radko93 works as expected in case the notification is sent with firebase console

**Comment by artyorsh** [comment]
@radko93 

**Update on https://github.com/invertase/react-native-firebase/pull/3427#issuecomment-613044036**:

That was my issue not reading sendbird docs carefully. What they say - the app state should be handled with their APIs. The screenshot below might be helpful for sendbird users who stuck into same issue)

image

This makes an issue I described invalid. 
@Salakar Sorry for posting the wrong information. Now I confirm an alpha release works properly.

**Comment by nabilfreeman** [comment]
@sivakumar-cf I also had this question about swizzling, I think RN Firebase now takes stuff straight from native Firebase further up the chain.

So you need to bypass swizzling there.

https://firebase.google.com/docs/cloud-messaging/ios/client#objective-c_6
https://firebase.google.com/docs/cloud-messaging/ios/receive#objective-c-ios-10

I had to do this so I could receive Intercom push notifications as well as Firebase.

**Comment by Salakar** [comment]
> @nabilfreeman Edit2: I got it, I was missing `await FirebaseMessaging().registerDeviceForRemoteMessages();` on app launch. OMG!! I hate push!! Going to bed. Thanks for this bugfix.

Seems like you're not the only one missing this - so I've just pushed a change where registration is now done automatically (with the option to opt-out of auto-registration if required)

**Comment by nabilfreeman** [comment]
> Seems like you're not the only one missing this - so I've just pushed a change where registration is now done automatically (with the option to opt-out of auto-registration if required)

Oh you legend!!! Thanks so much!!!

**Comment by nabilfreeman** [comment]
Just had a funny moment debugging an RN Firebase push issue, found this issue and my own comments from last year 🤦‍♂️

**Pull request merged**
