### PR TITLE
Refine flow type for tryJSONStringify to match newer versions of flow (>=0.96.0)

### LINKED ISSUE #2388: Flow error in `node_modules/react-native-firebase/dist/utils/index.js.flow`
I'm using

`"react-native-firebase": "^5.5.5"`

## Issue
I've got a `Flow` issue that is not mine to solve I think.
Can anybody help me, please?
```
Error ┈┈┈┈┈┈┈┈┈┈ node_modules/react-native-firebase/dist/utils/index.js.flow:191:12

Cannot return JSON.stringify(...) because undefined [1] is incompatible with null [2].

     node_modules/react-native-firebase/dist/utils/index.js.flow
     188│  */
 [2] 189│ export function tryJSONStringify(data: mixed): string | null {
     190│   try {
     191│     return JSON.stringify(data);
     192│   } catch (jsonError) {
     193│     return null;
     194│   }

     /private/tmp/flow/flowlib_355b4f17/core.js
 [1] 491│     ): string | void;
```

## Project Files

Here is my `.flowconfig`:
```
[ignore]
; We fork some components by platform
.*/*[.]android.js

; Ignore "BUCK" generated dirs
<PROJECT_ROOT>/\.buckd/

; Ignore unexpected extra "@providesModule"
.*/node_modules/.*/node_modules/fbjs/.*

; Ignore duplicate module providers
; For RN Apps installed via npm, "Libraries" folder is inside
; "node_modules/react-native" but in the source repo it is in the root
node_modules/react-native/Libraries/react-native/React.js

; Ignore polyfills
node_modules/react-native/Libraries/polyfills/.*

; These should not be required directly
; require from fbjs/lib instead: require('fbjs/lib/warning')
node_modules/warning/.*

; Flow doesn't support platforms
.*/Libraries/Utilities/HMRLoadingView.js

[untyped]
.*/node_modules/@react-native-community/cli/.*/.*

[include]

[libs]
node_modules/react-native/Libraries/react-native/react-native-interface.js
node_modules/react-native/flow/

[options]
emoji=true

esproposal.optional_chaining=enable
esproposal.nullish_coalescing=enable

module.file_ext=.js
module.file_ext=.json
module.file_ext=.ios.js

module.system=haste
module.system.haste.use_name_reducers=true
# get basename
module.system.haste.name_reducers='^.*/\([a-zA-Z0-9$_.-]+\.js\(\.flow\)?\)$' -> '\1'
# strip .js or .js.flow suffix
module.system.haste.name_reducers='^\(.*\)\.js\(\.flow\)?$' -> '\1'
# strip .ios suffix
module.system.haste.name_reducers='^\(.*\)\.ios$' -> '\1'
module.system.haste.name_reducers='^\(.*\)\.android$' -> '\1'
module.system.haste.name_reducers='^\(.*\)\.native$' -> '\1'
module.system.haste.paths.blacklist=.*/__tests__/.*
module.system.haste.paths.blacklist=.*/__mocks__/.*
module.system.haste.paths.whitelist=<PROJECT_ROOT>/node_modules/react-native/Libraries/.*
module.system.haste.paths.whitelist=<PROJECT_ROOT>/node_modules/react-native/RNTester/.*
module.system.haste.paths.whitelist=<PROJECT_ROOT>/node_modules/react-native/IntegrationTests/.*
module.system.haste.paths.blacklist=<PROJECT_ROOT>/node_modules/react-native/Libraries/react-native/react-native-implementation.js
module.system.haste.paths.blacklist=<PROJECT_ROOT>/node_modules/react-native/Libraries/Animated/src/polyfills/.*

munge_underscores=true

module.name_mapper='^[./a-zA-Z0-9$_-]+\.\(bmp\|gif\|jpg\|jpeg\|png\|psd\|svg\|webp\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|aac\|aiff\|caf\|m4a\|mp3\|wav\|html\|pdf\)$' -> 'RelativeImageStub'

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FlowFixMeProps
suppress_type=$FlowFixMeState

suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(<VERSION>\\)? *\\(site=[a-z,_]*react_native\\(_ios\\)?_\\(oss\\|fb\\)[a-z,_]*\\)?)\\)
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue\\((\\(<VERSION>\\)? *\\(site=[a-z,_]*react_native\\(_ios\\)?_\\(oss\\|fb\\)[a-z,_]*\\)?)\\)?:? #[0-9]+
suppress_comment=\\(.\\|\n\\)*\\$FlowExpectedError



[lints]
sketchy-null-number=warn
sketchy-null-mixed=warn
sketchy-number=warn
untyped-type-import=warn
nonstrict-import=warn
deprecated-type=warn
unsafe-getters-setters=warn
inexact-spread=warn
unnecessary-invariant=warn
signature-verification-failure=warn
deprecated-utility=error

[strict]
deprecated-type
nonstrict-import
sketchy-null
unclear-type
unsafe-getters-setters
untyped-import
untyped-type-import

[version]
^0.98.0
```

### PR DESCRIPTION
**Pull request by levibuzolic**
### Summary

Fixes #2388

> [As of version 0.96.0 of flow](https://github.com/facebook/flow/commit/1f6bcf88c02f3ed163104cf927b7f0ba2d62d7fb), an additional return type of `string | void` was added to `JSON.stringify`
>
> This catches the case of `JSON.stringify(undefined)` which returns `undefined` (`void`)
>
> I can get this [to fail](https://user-images.githubusercontent.com/721323/62185154-a7a30d00-b3a4-11e9-8282-e10fdf7e4711.png) `react-native-firebase`'s test suite by upgrading flow to a newer version (I tried 0.98).

### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [ ] ~`e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)~
- [ ] ~Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)~
  - **LINK TO DOCS PR HERE**
- [x] Flow types updated
- [ ] ~Typescript types updated~

### Test Plan

N/A

### Release Plan

[TYPES][BUGFIX] - Update flow return type for internal util `tryJSONStringify` to support flow >=0.96.0

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by levibuzolic** [comment]
Depending on how long the 5.x branch will be around for it could be worth upgrading flow in the `devDependencies` and resolving other errors -- if there's interest I'm happy to make a PR.

**Comment by Salakar** [comment]
Hey @levibuzolic 👋 thanks for sending this over

In its current state, this fails CI as its using an older flow version. Might be worth upgrading flow on the tests project and making a note that 98 is now the min supported; unless we can change the type to work with both?

cc @mikehardy

**Comment by levibuzolic** [comment]
Thanks @Salakar I'll take a look and see if I can get it working -- if not will do a PR with the flow upgrade, looks like there's a few more type issues that'll need attention there.

**Comment by levibuzolic** [comment]
@Salakar looks like I really should have run it locally than cowboying a PR directly from the GitHub UI. 😅 

Looks like I just needed to handle `string`, `void` *and* `null` because the function has an explicit `null` return. Also updated the flow type of `tryJSONParse` so it too can now accept `void`.

**Comment by Salakar** [comment]
Cool, LGTM. Thanks for changing it. The Android CI failure is not related (5.x.x branch needs updating to RN 60).

**Comment by mikehardy** [comment]
Wow, this really went to sleep. Sorry about that - v5.x.x CI is on fire at the moment so merging requires lots of personal attention, which was in short supply.

I have manually pulled your fork and cherry-picked this commit into my patch queue for v5.5.7 - I won't update this PR again (except to close it if it does not auto-close) but if you see v5.5.7 (should be tonight or tomorrow) it will be in there. 

I paired this with a second commit that upgraded v5.x.x to flow-bin 0.98.0 but had to disable a lint to do so. I was not able to get flow-bin 0.113.0 (current at time I type this) to work, but if you want to forward-port to that I can do so. I personally use Typescript so I have no interest, but because of same I do empathize with typing so if it helps you I'll try to merge whatever comes in

Thanks for your patience and for submitting this!

**Comment by levibuzolic** [comment]
Thanks for persisting with it @mikehardy 🙇

**Pull request closed without merging**
