### PR TITLE
Issue #512 - Fixed limit and cursor 

### PR DESCRIPTION
**Pull request by peterdivvito**
- Issue #552 Fixed limit on IOS
- Fixed cursor startAfter, startAt, endAt, endBefore on Android
- Fixed where clause with dates on both IOS and Android

I am a total newb when it comes to Objective C so please be brutal with your comments.

### CODE REVIEW

**Comment by chrisbianca** [comment]
@peterdivvito Thank you so much for this PR - it's great to have something that comprehensively includes Android, iOS and JS changes as well as some thorough tests! 

I've adapted your suggested solution to make use of some functionality that already existed in the library to convert each data type into a simple map containing the type and value.

This allows the iOS and Android code to be a bit more generic and better cope with all types - not just dates but `GeoPoint`, `DocumentReference`, arrays, objects and more.  It also allows the `startAt`, `startAfter`, `endAt` and `endBefore` to make use of `DocumentSnapshot` parameters too.

If you're interested in seeing the changes, they're available in these two commits:

https://github.com/invertase/react-native-firebase/commit/6ae004933867ffc8bb40fbe584ee49ed3c90d61b
https://github.com/invertase/react-native-firebase/commit/270279551aaf8061f64a3d7c47cbc4c10de03458

As well as the limit fix for iOS you suggested:

https://github.com/invertase/react-native-firebase/commit/d8fd09adefa27ea6ee4dc898e7ac3469212f876e

These changes pass all the tests that you added, and some more that I included to validate `GeoPoint` and `DocumentSnapshot` usage.  It would be great if you're able to confirm that the changes fix the issues you were experiencing.  If so, I'll get another release out later today...

You can install the latest code by using the following:

`npm install --save https://github.com/invertase/react-native-firebase#v3.0.x`

**Comment by peterdivvito** [comment]
Hi Chris,

I saw your changes this morning and I've already tested them out. Fantastic job. Keep up the great work.

Peter

**Comment by chrisbianca** [comment]
Awesome, thanks for confirming and thanks again for the PR!  I'm going to close this off and we'll get a release out today or tomorrow with everything in...

**Comment by petetastic** [comment]
I'm now getting a new error when trying to use "limit" which claims that the limit is not positive. I'm using @ryanlanglois' exact index.js code from here: https://github.com/invertase/react-native-firebase/issues/552.

Here's the error:
**Exception 'Invalid Query. Query limit (-5764607523034234557) is invalid. Limit must be positive.' was thrown while invoking collectionOnSnapshot on target RNFirebaseFirestore with params (
    "__FIRAPP_DEFAULT",
    users,
        (
    ),
        (
                {
            direction = ASCENDING;
            fieldPath = "name.first";
        }
    ),
        {
        limit = 20;
    },
    ciODfbwaOpRgJj59Tdqr,
        {
    }
)**

**Comment by chrisbianca** [comment]
@petetastic Have you updated to version 3.1.0?

**Comment by petetastic** [comment]
Forgive me, slight noob at npm, but I've tried:

npm install --save https://github.com/invertase/react-native-firebase#v3.1.x
**npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout v3.1.x
npm ERR! error: pathspec 'v3.1.x' did not match any file(s) known to git.
npm ERR!** 

Do I need to upgrade differently?

**Comment by chrisbianca** [comment]
`npm install --save react-native-firebase@3.1.0`

**Comment by petetastic** [comment]
Okay, so now it doesn't complain, but it doesn't limit the data anymore either (I get 461 results instead of 2). Any thoughts? Here's the relevant piece of code (I tried with and without "orderBy"):

  constructor() {
    super();
    this.ref = firebase.firestore().collection('users')
    // .orderBy('name.first')
    .limit(2)
    this.unsubscribe = null;
    this.state = {
        textInput: '',
        loading: true,
        users: [],
    };
  }

  componentDidMount() {
    this.unsubscribe = this.ref.onSnapshot(this.onCollectionUpdate)
  }

  componentWillUnmount() {
    this.unsubscribe();
  }

  onCollectionUpdate = (querySnapshot) => {
    const users = [];
    var count = 0
    querySnapshot.forEach((doc) => {
    	count++
    });
    console.log("COUNT IS:",count)
  }

**Comment by chrisbianca** [comment]
@petetastic I'm not sure why this wouldn't be working, we have tests in our test pack for limit and they're working perfectly on both iOS and Android. I've even just added a test case for `onSnapshot` explicitly as our tests only had a test for `get` and that's working too...

**Comment by petetastic** [comment]
Yes, I can't figure it out either. Here's my full code, so that you can see it. I switched from onSnapshot to get() to see if that would make a change, but now I get yet a different error:

**Error getting documents Error: Firestore: Operation is not implemented or not supported/enabled. (firestore/unimplemented).
    at createErrorFromErrorData (NativeModules.js:117)
    at NativeModules.js:80
    at MessageQueue.__invokeCallback (MessageQueue.js:354)
    at MessageQueue.js:129
    at MessageQueue.__guard (MessageQueue.js:269)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:128)
    at debuggerWorker.js:72**


[databaseTest.txt](https://github.com/invertase/react-native-firebase/files/1450085/databaseTest.txt)

**Comment by Salakar** [comment]
@petetastic did you rebuild the native part of your app after upgrading the NPM module - i.e rebuilding iOS app or android app, as per the release notes:

image

**Comment by petetastic** [comment]
Thanks @Salakar that fixed the error, but still the "Limit" function is not limiting the results in any way. It doesn't complain, just doesn't do anything at all...

**Comment by petetastic** [comment]
Okay, so it turns out that by going back to the onSnapshot listener the limit function works, but it doesn't work with the regular "get()" construction. Meaning we can't return a single shot of data without setting up a listener. Perhaps it has not been implemented for the latter?

```
// ----- 1st attempt using an observer works -----
//
var ref = firebase.firestore().collection('users')
.where('name.first','==','ella')
.orderBy('name.last')
.limit(3)
.onSnapshot((querySnapshot) => {
	console.log("1) Found number of results:",querySnapshot.docs.length)
})

// ----- 2nd attempt using get() fails -----
//
var ref = firebase.firestore().collection('users')
.where('name.first','==','ella')
.orderBy('name.last')
.limit(3)
.get()
.then(querySnapshot => {
	console.log("2) Found number of results:",querySnapshot.docs.length)
})
.catch(err => {
	console.log('Error getting documents', err);
});
```

Error message from 2nd attempt:
**Error getting documents Error: Firestore: Operation was rejected because the system is not in a state required for the operation`s execution. (firestore/failed-precondition).**

**Pull request closed without merging**
