### PR TITLE
Fix/autolinking

### PR DESCRIPTION
**Pull request by zoontek**
### Summary

It solves the different autolinking issues with React Native 0.60 (podspec location and unknown option warning).

### CODE REVIEW

**Comment by zoontek** [comment]
@DavidLichy Indeed. I renamed the file and remove the rnpm config, no more warning!

**Comment by Salakar** [comment]
👋 this is now live in v5.5.5 - [[changelog]](https://rnfirebase.io/docs/v5.x.x/releases/v5.5.x#Changelog)

Thanks for contributing 🎉

**Comment by kreativ-software** [comment]
Great work! But... How do I add pod 'Firebase/Messaging' to my app?

**Comment by zoontek** [comment]
@kreativ-software Normally. Autolinking only works for `RNFirebase`.

**Comment by kreativ-software** [comment]
Thanks

**Comment by erdenehuu** [comment]
@zoontek How do i add RNFirebaseAuthPackage to my app?

**Pull request merged**
