### PR TITLE
docs(auth): more explicitly note that onIdTokenChanged returns a JWT

### PR DESCRIPTION
**Pull request by efstathiosntonas**
### Description

It's not clear wether ID Token is a JWT token or not, developer will have to visit [official documentation](https://firebase.google.com/docs/auth/admin/verify-id-tokens) in order to find out.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [X] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Hmm - we have this documented also on the getIdTokenResult method, but if it's still unclear I think adding it method-by-method as a strategy is less useful than documenting it on the getIdToken method itself, specifically right here: https://github.com/invertase/react-native-firebase/pull/5674/files#diff-03906ee16085b0c14938e3c6b10b4609a51560685a3b5488ea16129b7f789821R949 - specifying in that spot that the authentication is a JWT value, and may (if desired) be verified using the admin SDK or a 3rd party JWT library with a link to https://firebase.google.com/docs/auth/admin/verify-id-tokens as you linked in the PR

What do you think?

**Comment by efstathiosntonas** [comment]
@mikehardy I’m not quite following, today was a long day and my head is about to explode as you can see from the failing PR title and the parentheses after the `.` instead of before, sorry about this.

Do you want me to add the additional info into the JSDoc example as a comment or in the description of the method?

**Comment by mikehardy** [comment]
I think the description of the method, so there's room for the link and everything. No worries about the semantic PR title failure, it's touchy on single-commit items and won't block merge here, more it serves for me to remember squash-merge with a correct semantic release title

**Comment by efstathiosntonas** [comment]
@mikehardy I think it's ok now

**Review by mikehardy — APPROVED** [review]
works for me - thanks for taking the time to improve the docs, much appreciated!

**Comment by efstathiosntonas** [comment]
My pleasure @mikehardy, keep it up 😁

**Pull request merged**
