### PR TITLE
fix(app, sdks)!: SDK ios 10.21.0 / android / 32.7.2

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

Update dependencies, with the most important change being a transitive requirement to enforce a new minimum requirement for cocoapods version of 1.12.0 - coming in from firebase-ios-sdk in order to support Apple's new Privacy Manifests

This is a tiny, easily met breaking change but is still potentially breaking

### Release Summary

conventional commits, and the `!` and `BREAKING CHANGES` notes in the commit message are patterned off previous ones that correctly generated a great `CHANGELOG` entry with the information developers need on what the break is and how to handle it

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [x] Yes
  - [ ] No

### Test Plan

CI needs to pass as well as local testing - it all passes for me

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by Summys** [comment]
I've seen some issues where the PrivacyInfo file is not picked by xcode's Generate Privacy Report tool if the framework is static. Have you encountered it?

**Comment by mikehardy** [comment]
@Summys 🤔 no I have not encountered this but the main reason why is that although I'm working as quickly as possible to *expose* the new firebase-ios-sdk release that supports the privacy manifests, that has left me no time to actually try it at the app layer yet. So I simply haven't tried 😬 

Is this observation (that Xcode is not picking them up, perhaps because they are static) based on experience with other libraries? Or have you already incorporated the patchset from here and tried it and you are not seeing the firebase-ios-sdk manifests?

**Comment by Summys** [comment]
@mikehardy didn't test the patchset, but from other static frameworks. Maybe that's intended and the PrivacyInfo of these static framework should be included in the app's Privacy.

**Comment by mikehardy** [comment]
@Summys 🤔 I wish I had more experience here, I'm sorry that I don't. I'm going to send up a bat signal that I try to use rarely to preserve it's power 😆  @paulb777 - are you aware of any limitations with App Privacy Manifest inclusion when libraries are linked statically? Is there an documentation on how *exactly* to do the app privacy manifest thing for firebase-ios-sdk when included user apps?

(for reference: users here link via `use_frameworks! :linkage => :static` in app Podfiles)

**Comment by paulb777** [comment]
@mikehardy We're still in the implementation phase, but early testing by @ncooke shows that the manifest shows up in the privacy report:

Static Linking
Configurable via when use_frameworks! :linkage => :static is specified in Podfile
As specified in the podspec, the generated bundle is named FirebaseSharedSwiftResources and referenced in the encompassing app’s privacy report below. 

Screenshot 2024-02-23 at 6 50 38 AM

Because CocoaPods is statically linking the xcframework it builds from the source-based podspec, only the generated resource bundle is embedded within the app’s bundle.

**Comment by mikehardy** [comment]
Nothing more to do on this one, I'm always a little slower on breaking changes (even though this one is really trivial to handle - just cocoapods from last year as a new minimum) but I can't see anything else to do, so here we go

**Pull request merged**
