### PR TITLE
feat(firestore)!: add ignoreUndefinedProperties setting, throw on undefined if false

### LINKED ISSUE #5304: 🔥 [🐛] undefined props are converted to null when writing data to firestore
## Issue

When I write a document to firestore with a prop with the value `undefined` it is converted to `null` before it's written.

This behavior is not consistent with web either [firebase](https://www.npmjs.com/package/firebase) or [firebase-admin](firebase-admin) which will both throw an error unless you have set `ignoreUndefinedProperties: true` using `firestore.settings({ ignoreUndefinedProperties: true })`.

I expect the same behavior as other versions  firebase (error thrown) & it would be awesome if `rnf` exposed the `ignoreUndefinedProps` setting because really what I want is for these undefined to result in these props being left out of the db update.

```
const testCollection = firestore().collection('test');
await testCollection.add({
  time: new Date(),
  u: undefined,
  n: null,
});
```

result in db:
image

[Here](https://github.com/invertase/react-native-firebase/blob/0217bff5cbbf233d7915efb4dbbdfe00e82dff23/packages/firestore/lib/utils/serialize.js#L108) is the line of code that appears to be converting these `undefined` props to `null` before sending them over the bridge.

---

## Project Files

Minimal repro can be found [here](https://github.com/goleary/rnfUndefinedRepro)

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
{
  "name": "rnfundefinedrepro",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-firebase/app": "^11.5.0",
    "@react-native-firebase/firestore": "^11.5.0",
    "react": "17.0.1",
    "react-native": "0.64.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: Windows 10 10.0.19041
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 32.66 GB / 63.74 GB
  Binaries:
    Node: 12.19.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283
    Visual Studio: Not Found
  Languages:
    Java: 15.0.1 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `11.5.0`
- **`Firebase` module(s) you're using that has the issue:**
  - `firestore`

</p>
</details>

### PR DESCRIPTION
**Pull request by jmif**
### Description

Firestore web / node SDKs support an "ignoreUndefinedProperties" field which will automatically filter out undefined properties.  This PR adds support for this.  They will throw by default if undefined is passed in.

Followed the pattern suggested in in #5304 with one exception, I have not added a `settings` getter because the Firestore API already uses `settings` as a setter and it proxies directly to native for over half of the settings.  I can modify the setter to be a getter when no arguments are provided and to save / return all settings if desired.  

This is a breaking change in the current iteration: we mimic the node / web SDKs - we throw when we encounter `undefined` by default

### Related issues

Fixes #5304

### Release Summary

Adds Firestore support for ignoreUndefinedProperties config value

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [x] Yes
  - [ ] No

### Test Plan

```
      ✓ returns a new WriteBatch instance
    collection()
      ✓ throws if path is not a string
      ✓ throws if path is empty string
      ✓ throws if path does not point to a collection
      ✓ returns a new CollectionReference
    doc()
      ✓ throws if path is not a string
      ✓ throws if path is empty string
      ✓ throws if path does not point to a document
      ✓ returns a new DocumentReference
      ✓ filters out undefined properties when setting enabled
      ✓ filters out nested undefined properties when setting enabled
      ✓ throws when undefined value provided and ignored undefined is false
      ✓ throws when nested undefined value provided and ignored undefined is false
    collectionGroup()
      ✓ throws if id is not a string
      ✓ throws if id is empty
      ✓ throws if id contains forward-slash
      ✓ returns a new query instance
      ✓ performs a collection group query
      ✓ performs a collection group query with cursor queries
    disableNetwork() & enableNetwork()
      ✓ disables and enables with no errors
    runTransaction()
      ✓ throws if updateFunction is not a function
    settings()
      ✓ throws if settings is not an object
      ✓ throws if passing an incorrect setting key
      ✓ throws if cacheSizeBytes is not a number
      ✓ throws if cacheSizeBytes is less than 1MB
      - accepts an unlimited cache size
      ✓ throws if host is not a string
      ✓ throws if host is an empty string
      ✓ throws if persistence is not a boolean
      ✓ throws if ignoreUndefinedProperties is not a boolean
      ✓ throws if ssl is not a boolean
    Clear cached data persistence
      - should clear any cached data
    wait for pending writes
      - waits for pending writes

```

### CODE REVIEW

**Comment by mikehardy** [comment]
champion! I'll review this and I appreciate the backwards compatibility. Our next release will be breaking so I think if we are ever going to break now is the time. We should follow JS SDK so I do not break lightly but I think it is justified in this case

**Comment by jmif** [comment]
Ok cool I'll update to breaking change and just found a bug I need to fix as well / add test.

**Comment by jmif** [comment]
Updated / added tests and ran the full suite as well 👍

**Comment by mikehardy** [comment]
I just updated the PR title to have hit all the right "angular conventional commits" high notes so the changelog will be as informative as possible while still being terse - and I approved the CI run so it will chew through it. CI is a little flaky right now but I'll get it through assuming it's not related to this change

Still need to review but I've been in meetings all day, apologies

**Review by mikehardy — APPROVED** [review]
Hey there! Sorry for the delay on review, but in general thanks so much for this. The testing support is fantastic, and deserves special recognition, seriously.

I left a couple comments which are basically trivial + documentation, and I can just commit those myself - I'll do that in a moment and get this in

**Review by mikehardy — CHANGES_REQUESTED** [review]
This is going to be a bit of comment spam but I believe I have to request changes then I can commit...

**Comment by mikehardy** [comment]
This was ready to go minus the two wording changes, but I don't have rights to push to the PR branch so I cloned it off and made a PR with the changes to wording, and also converted a *ton* of firestore e2e tests to unit tests, which was out of scope for you really but a big goal of the repo so it seemed right I do it vs pushing that on you ;-)

Hope you don't mind - your commit is still first in the list, consolidated with a breaking notice + advice to help devs

#5321

**Comment by jmif** [comment]
Sounds great thanks @mikehardy

**Pull request closed without merging**
