### PR TITLE
Full react-redux-firebase example

### PR DESCRIPTION
**Pull request by prescottprue**
* `react-redux-firebase` example in `redux` section of docs has been updated to be a fully working application. Previously things such as the `createReducer` logic were skipped

### CODE REVIEW

**Comment by Salakar** [comment]
Awesome, thanks again!

**Comment by callagga** [comment]
where was this example exactly?  have a link?

**Comment by tmaly1980** [comment]
@callagga FYI: https://github.com/prescottprue/react-redux-firebase/tree/v2.0.0/docs/integrations

I'm guessing he forked react-native-firebase but then moved the documentation to react-redux-firebase

**Comment by prescottprue** [comment]
For anyone that wants it, here is the examples that uses react-native-firebase: https://github.com/prescottprue/react-redux-firebase/tree/v2.0.0/examples/complete/react-native-firebase.

**Pull request merged**
