### PR TITLE
fix(app,ios): handle Info.plist file paths with spaces

### PR DESCRIPTION
**Pull request by twelve17**
### Summary

When the script looks for plist files, it looks for them based on the values of `$BUILT_PRODUCTS_DIR` and `$DWARF_DSYM_FOLDER_PATH`.  When these values have spaces, the script inadvertently splits the paths on spaces and erroneously reports `Info.plist` files missing when they are not.

Example:  given this environment:

```
export PROJECT_DIR=/Users/foo/repo/ios
export BUILT_PRODUCTS_DIR="/Users/foo/Library/Developer/Xcode/DerivedData/MyApp-abcdef/Build/Intermediates.noindex/ArchiveIntermediates/MyApp (staging)/            BuildProductsPath/StagingRelease-iphoneos"
export INFOPLIST_PATH=MyAppStaging.app/Info.plist
export DWARF_DSYM_FOLDER_PATH="/Users/foo/Library/Developer/Xcode/DerivedData/MyApp-abcdef/Build/Intermediates.noindex/ArchiveIntermediates/MyApp (staging)/        BuildProductsPath/StagingRelease-iphoneos"
export DWARF_DSYM_FILE_NAME=MyAppStaging.app.dSYM
```
The script breaks the normal and dsym Info.plist paths into four values, which yield these errors:

```
warning:   A Info.plist build output file was not found (/Users/foo/Library/Developer/Xcode/DerivedData/MyApp-abcdef/Build/Intermediates.noindex/ArchiveIntermediates/MyApp)
warning:   A Info.plist build output file was not found ((staging)/BuildProductsPath/StagingRelease-iphoneos/MyAppStaging.app/Info.plist)
warning:   A Info.plist build output file was not found (/Users/foo/Library/Developer/Xcode/DerivedData/MyApp-abcdef/Build/Intermediates.noindex/ArchiveIntermediates/MyApp)
warning:   A Info.plist build output file was not found ((staging)/BuildProductsPath/StagingRelease-iphoneos/MyAppStaging.app.dSYM/Contents/Info.plist)
```

This PR adds quoting to the variable name interpolation on the loop code, so that the paths will be interpreted properly.

It's possible there are other places in this script that are not considering spaces in paths, and certain configurations could break it as a result, but I didn't get a chance to verify it thoroughly.

### Checklist

- [N/A ] Supports `Android`
- [N/A ] Supports `iOS`
- [N/A] `e2e` tests added or updated in packages/**/e2e
- [N/A] Flow types updated
- [N/A] Typescript types updated

### Release Plan

[INTERNAL][BUGFIX] [APP] - ios_config.sh: handle $BUILT_PRODUCTS_DIR and $DWARF_DSYM_FOLDER_PATH paths with spaces

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Review by Salakar — APPROVED** [review]
Oh wow, good spot with this, LGTM and am happy to merge.

Can also see you've signed the CLA so ignore the CLA status, thanks.

**Comment by twelve17** [comment]
@Salakar , thanks for the quick response!  However, I'm afraid there are still some issues here. This time in the `setPlistValue`.  

```
cd/Build/Intermediates.noindex/ArchiveIntermediates/MyApp (staging)/BuildProductsPath/StagingRelease-iphoneos/MyAppStaging.app/Info.plist'
File Doesn't Exist, Will Create: /Users/foo/Library/Developer/Xcode/DerivedData/MyApp-abcdef/Build/Intermediates.noindex/ArchiveIntermediates/MyApp
Invalid Arguments
```

I haven't been able to properly escape the names without doing an ugly hack to modify `$IFS`:

```
for plist in "${_TARGET_PLIST}" "${_DSYM_PLIST}" ; do
  if [[ -f "${plist}" ]]; then


    # paths with spaces break the setPlistValue unless we do this
    oldifs=$IFS
    IFS="
"

    for i in "${!_PLIST_ENTRY_KEYS[@]}"; do
      setPlistValue "${_PLIST_ENTRY_KEYS[$i]}" "${_PLIST_ENTRY_TYPES[$i]}" "${_PLIST_ENTRY_VALUES[$i]}" "${plist}"
    done

    IFS=$oldifs
  else
    echo "warning:   A Info.plist build output file was not found (${plist})"
  fi
done
```

I'm testing this now.

**Comment by twelve17** [comment]
@Salakar , it seems the `IFS` hack worked for me, do you wish to get another PR?

**Comment by Salakar** [comment]
Yes please @twelve17

**Comment by twelve17** [comment]
@Salakar  here you go: https://github.com/invertase/react-native-firebase/pull/3152

Thanks!

**Pull request merged**
