### PR TITLE
fix(firestore): increase amount of maximum disjunctions in firebase

### LINKED ISSUE #7542: [🐛] Change to amount of maximum disjunctions in firebase
## Issue

Currently, it's not possible to make more that 10 disjunctions in firestore although it's allowed up to 30. 
```
firestore()
  .collection(collection)
  .where('id', 'in', [1,2,3,4,5, ..., 30])
  .get();
```

[Here are the updated limitations from firebase docs](https://cloud.google.com/firestore/docs/query-data/queries#in_not-in_array-contains-any_limits)

> **Limitations**
> Note the following limitations for in, not-in, and array-contains-any:
> 
> - Firestore provides support for logical OR queries through the or, in, and array-contains-any operators. These queries are limited to [30 disjunctions based on the query's disjunctive normal form](https://cloud.google.com/firestore/docs/query-data/queries#limits_on_or_queries).
> - You can use at most one array-contains clause per disjunction (or group). You can't combine array-contains with array-contains-any in the same disjunction.
> - You can't combine not-in with not equals !=.
> - not-in supports up to 10 comparison values.

The easiest fix is to change library limitation for this:
https://github.com/invertase/react-native-firebase/blob/main/packages/firestore/lib/FirestoreQuery.js#L476C102-L476C134

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by shtelzerartem**
### Description

Increased amount of maximum disjunctions in firebase from 10 up to 30
 
### Related issues

- Fixes #7542

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Hi there! Thanks for proposing this - it looks valid, however even for small changes we need the CLA CI check to pass which means we need for you to follow the "details" link on the failing CLA check and sign the agreement - then I think this can go through

Thanks!

**Comment by shtelzerartem** [comment]
> Hi there! Thanks for proposing this - it looks valid, however even for small changes we need the CLA CI check to pass which means we need for you to follow the "details" link on the failing CLA check and sign the agreement - then I think this can go through
> 
> Thanks!

Signed CLA. And thanks!

**Comment by shtelzerartem** [comment]
@mikehardy
Actually, I noticed that there are tests failing because of this change, let me fix it first.

**Review by mikehardy — APPROVED** [review]
Nice! And of course with the tests :-). Thanks for patching those up - this looks great

**Comment by mikehardy** [comment]
I think a `lint:js --write` will auto-fix all those, either way I can shepherd this through on Monday when I roll through the PR queue again, it's pretty easy to pull locally + fix + repush then merge

**Pull request merged**
