### PR TITLE
feat(app, sdk)!: firebase-ios-sdk 10.4.0 / setAPNS / getToken on Simulator

### LINKED ISSUE #6830: [🐛][🔥] [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key
## Issue

Describe your issue here

As of this morning (EDT), when running our app in the iOS Simulator, we are seeing this Firebase Messaging Error message:

> NativeFirebaseError: [messaging/unknown] The operation couldn’t be completed. Invalid fetch response, expected 'token' or 'Error' key

**We have made no Firebase or React Native related changes to our dependencies or code base over night.**

The only change was locally running `pod install` for a patch version upgrade of a completely unrelated library (react-native-rate) on a working branch. However, even go back to the main branch without the lib upgrade, cleaning, running `yarn` and `pod install` creates the new issue on the `main` branch as well.

The error is thrown on the `messaging().getToken()` invocation.

The issue does not  replicate on Android it seems.

It is also not **_currently_** affecting our deployed environments STAGING and PROD.
However, those environments, did not yet see a build-deploy cycle today. (Last Staging CI Deployment run was 2 days ago).

So if this error is due to some deep iOS lib dependency of RN Firebase, while our `Podfile.lock` does not have any tracked changes related to RN Firebase, we are worried that the issue propagates with the next Deployment runs.

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

Relevant snippet from `Podfile.lock`:

```
  - Firebase/AnalyticsWithoutAdIdSupport (8.9.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics/WithoutAdIdSupport (~> 8.9.1)
  - Firebase/CoreOnly (8.9.1):
    - FirebaseCore (= 8.9.1)
  - Firebase/Messaging (8.9.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (~> 8.9.0)
  - FirebaseAnalytics/WithoutAdIdSupport (8.9.1):
    - FirebaseCore (~> 8.0)
    - FirebaseInstallations (~> 8.0)
 ```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 12.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 21.67 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1673461052290-0.6051340710415349/node
    Yarn: 1.22.17 - /var/folders/kb/0gc38wkn40bb3513d34xdym40000gp/T/yarn--1673461052290-0.6051340710415349/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9014738
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: javac 15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `13.0.1`

We are currently exploring the upgrade path, given the breaking change with `use_frameworks!` introduces in RN Firebase 15.x

- **`Firebase` module(s) you're using that has the issue:**
  - `Messaging`
- **Are you using `TypeScript`?**
  - `Y` & `4.6.2`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

firebase-ios-sdk 10.4.0 adds a new strict requirement that the app has an APNS token prior to requesting an FCM token

A valid APNS token requires:
- that the app registers for remote notifications
- that you wait long enough for async network activity such that the app's token receipt callback is called
- if you are on Simulator (not real device) you have: macOS 13+ && ios 16+ && Apple Silicon

If you cannot obtain a valid APNS token (typically: you are on an unsupported Simulator, see above, but you may have disabled swizzling): you *may* call `setAPNSToken` with an arbitrary string or with an APNS token fetched by other means, and FCM token APIs will function.

This PR was made with the help of the firebase-ios-sdk team, for which we are grateful. Thanks Aashish in particular 👋 

More information, from Aashish: https://github.com/firebase/firebase-ios-sdk/issues/10679#issuecomment-1402776795

### Related issues

Fixes #6830

### Release Summary

conventional commits

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [x] Yes
  - [] No

### Test Plan

The messaging tests had to change a lot to handle this!
Checked it on intel and M1 macs and Android

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Queuing this for merge in batch with AppCheck changes as both are likely breaking

**Comment by riccardoio** [comment]
@mikehardy Do you have an eta? (no rush, really appreciate your work)

**Comment by mikehardy** [comment]
ETAs are always hard in open source but this time I've got a hard deadline from Google to get AppCheck working with the PlayIntegrity provider on Android by "end of January", which is Tuesday next week. So, should be then :-). You can follow that one at #6847 

That said, no reason to wait if you don't want to wait, you can integrate this locally (and I would actually really appreciate any feedback from a tester on real devices...) by integrating the patch-package set from the PR (check the CI actions and follow the details link for "Create Test Patches"). I just re-based against main and re-pushed so the set should be as clean as possible (just app for the SDK bump and messaging for all the new APNS token handling...)

**Comment by mikehardy** [comment]
(latest re-push here is just rebasing against main again as the Podfile.lock moves with releases generating conflicts; and I made another release; no code changes at all)

**Pull request merged**
