### PR TITLE
fix(messaging): RemoteMessage.data may be JSON-serializable object as well as string

### LINKED ISSUE #7279: 🔥 Type Issue in Messaging  - Not a bug just a type fix
## Issue

Describe your issue here
Discovered a type issue through trial and error. Specifically FirebaseMessagingTypes.RemoteMessage.data has a type of { [key: string]: string }. When I accessed data I got back the following: 

  "data": {
    "link": "https://example.com",
    "fcm_options": {
      "image": "https://example.png"
    }

fcm_options returns an object not a string. My suggestion is to change the type on data to { [key: string]: string | object }.

This is just a type fix, so I'm not sure it's relevant to include the information below. If you do think it's relevant I would be glad to add more 
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [x] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - 17.5.0
- **`Firebase` module(s) you're using that has the issue:**
  - Messaging
- **Are you using `TypeScript`?**
  - YES 4.8.4

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by ccorneliusHsv**
### Description

Discovered through testing that the type for data on the RemoteMessage could be a string or an object.  This was 

### Related issues
Fixes #7279 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ X ] Yes
- My change supports the following platforms;
  - [ X ] `Android`
  - [ X ] `iOS`
- My change includes tests;
  - [ X ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ X ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ X] No

### Test Plan

Updated e2e test to include an object and string to reflect updated types option. 
---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
🔥

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This looks correct, thank you for posting this!

**Review by mikehardy — COMMENTED** [review]
And that's why we have tests 😆  thank you for adding the test change so it was covered or we may not have seen this

```
1) remoteMessage modular
       firebase v8 compatibility
         messaging().sendMessage(*)
           data
             accepts custom data value:
     NativeFirebaseError: [messaging/unknown] Value for fooObject cannot be cast from ReadableNativeMap to String
      at FirebaseMessagingModule.sendMessage (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.invertase.testing&modulesOnly=false&runModule=true&sourceMapURL=true:25[2691](https://github.com/invertase/react-native-firebase/actions/runs/6016676986/job/16457624689?pr=7316#step:19:2695):28)
      at Context.<anonymous> (/Users/runner/work/react-native-firebase/react-native-firebase/packages/messaging/e2e/remoteMessage.e2e.js:182:40)
```

**Comment by mikehardy** [comment]
Interesting - so, is it possible for it to truly be type `string | object` or is it more specific to say it may be `string | {[key: string]: string}` ?

Because the Java API for RemoteMessage.addData only accepts string/string parameters, implying that objects were not really contemplated as parameters: https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Builder#addData(java.lang.String,java.lang.String)

It's possible we can serialize the object to JSON prior to sending it down to native, and I think that's likely the best course - in lib/index.js checking if it is typof string (or similar?) and if it is not then doing a `JSON.serialize(param, null, 0)` on it before sending it down to the native layer.

What do you think?

**Review by mikehardy — CHANGES_REQUESTED** [review]
underlying API is string/string, so object must be serialized I think, which is easiest at javascript layer prior to sending it to native layer

**Comment by ccorneliusHsv** [comment]
@mikehardy I'm working on the solution you suggested, finishing up tests and validations to give me some confidence it's gonna work correctly. I do want to provide some info and to make sure that this PR suggestion is valid. We are using the Firebase console to send notifications and the following is what we are receiving . 

> iOS => Push Notification - onMessage 
{
  "data": 
  {
    "deep_link": "*************", 
    "marketing": "true", 
    "fcm_options": {"image": "https://*****.png"}
  }, 
 "from": "************", 
 "messageId": "1694100993860917", 
 "mutableContent": true, 
 "notification": {"body": "Body Example", "title": "Title Example"},
 "sentTime": "1694100993"
}


> Android  => Push Notification - onMessage 
{
  "collapseKey": "***************", 
  "data": 
  {
    "deep_link": "******", 
    "marketing": "true"
  }, 
  "from": "************", 
  "messageId": "0:1694103182522315%980f3695980f3695", 
  "notification": 
  {
    "android": 
    {
      "channelId": "marketing", 
      "imageUrl": "https://*****.png"
    }, 
    "body": "Body Example", 
    "title": "Title Example"
  }, 
  "sentTime": 1694103182513, "ttl": 2419200
}

So, we only see the type issue on the iOS notifications and we only see this issue when using the Firebase console to send notifications. Went through some sanity checks including looking at our Notifications Service to make sure we weren't modifying the notifications...and I don't see anything.  Just wanted to give an update and the additional info in case it might be helpful.

**Review by mikehardy — APPROVED** [review]
This is a subtle one but a valid one - I *think* this matches up with underlying SDK params now as well as actual experience of getting objects in RemoteMessage 🤞

**Pull request merged**
