### PR TITLE
v5.3.0

### PR DESCRIPTION
**Pull request by Salakar**
Changelog Preview: https://rnfirebase.io/docs/v5.3.x/releases/v5.3.x

### CODE REVIEW

**Comment by mikehardy** [comment]
I'm excited to see the Firestore changes required to track upstream even if it's a bit of a sidetrack from what appears to be such solid 6.x progress. The errors related to size in 17.x of firestore, fixed in 18 were a little worrying to me as I'm just about to integrate it to my app. Which is a segue to me offering to test this as I begin working with the firestore APIs starting Monday if you give me some very clear snippet of how exactly to npm install the version to do so (with https+git or an npmjs.com label or something)

**Comment by Salakar** [comment]
Hey @mikehardy 

I am trying to keep v5 updated as often as I can as I'm aware v6 is some time away, the changes above were definitely needed at least to fix a couple of things, with some minor feature support added just to keep people going 🙃

I'm hoping to have this published to npm by Monday/Monday lunch time, so it'll just be a case of installing v5.3.0 once it's published and following the upgrade guide (still todo but pretty much just update SDK versions).

-----

Firestore v6 work hasn't started properly yet also so it's not too bad doing v5 changes as some of it can be lifted over. Some major internals changes for it in v6, mainly focused at performance improvements - pretty big ones, that's not to say the current implementation is bad, just a lot more performance can be squeezed out of it.

**Comment by Salakar** [comment]
https://rnfirebase.io/docs/v5.3.x/releases/v5.3.x - release notes preview up. 

Migrating the starter then I'll publish

**Comment by mgenov** [comment]
Getting a really strange error when trying 5.3.0-rc1

```
ERROR: Unable to resolve dependency for ':react-native-firebase@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:16.0.1.
Show Details
Affected Modules: react-native-firebase


ERROR: Unable to resolve dependency for ':react-native-firebase@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:16.2.0.
Show Details
Affected Modules: react-native-firebase


ERROR: Unable to resolve dependency for ':react-native-firebase@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:16.1.0.
Show Details
Affected Modules: react-native-firebase
```

e.g messed dependencies of play-services-basement 16.1.0 and 16.2.0

This is the complete list of my dependencies:

```groovy
   implementation 'com.android.support:multidex:1.0.3'
   implementation("com.facebook.react:react-native:0.59.3")
   implementation project(':react-native-firebase')
   implementation 'com.google.firebase:firebase-core:16.0.8'
   implementation 'com.google.android.gms:play-services-base:16.1.0'
   implementation 'com.google.firebase:firebase-auth:16.2.0'
   implementation 'com.google.firebase:firebase-database:16.1.0'
   implementation 'com.google.firebase:firebase-firestore:18.2.0'

   compile (project(':react-native-device-info')) {
        transitive = true
   }

    implementation ('com.crashlytics.sdk.android:crashlytics:2.9.9') {
        transitive = true
    }
```

**Comment by Salakar** [comment]
@mgenov came across that myself as well today, have spent a few hours looking at this today frustratingly - should be ok now in rc3 if you could try that one - thanks

**Comment by mgenov** [comment]
Thanks @Salakar. The issue is resolved in rc3.

**Comment by mikehardy** [comment]
Some notes as I upgrade:
- making the firestore date -> timestamp default to the breaking behavior seems like a request for punishment in the form of a lot of issues on github, but that's a possibly naive and/or possibly incorrect view :smiley: 
- there are already updates to the gradle deps for firebase-perf (16.2.5) and firebase-config (16.5.0) and firebase-messaging (17.6.0)

running on android and ios (after a pod update / pod install) but *not* using Firestore yet seems fine so far with no regressions on the packages I'm using the heaviest and have gone through so far (analytics + auth)

I'll be doing newbie firestore stuff tomorrow and will chime in if I see anything

**Comment by Salakar** [comment]
@mikehardy 
> * making the firestore date -> timestamp default to the breaking behavior seems like a request for punishment in the form of a lot of issues on github, but that's a possibly naive and/or possibly incorrect view 😃

I do feel the potential issue this could cause for people but also this is was introduced by the native SDKs and not something I did, there is a setting that can be changed in your app via `firebase.firestore().settings({})` that can revert the behaviour but this is also deprecated - if someone upgrades their native sdks to versions not specified by this lib they'd be in for shock when it doesn't work at all - so thought best to do it now.

**Comment by Salakar** [comment]
This has been published now to v5.3.0 on npm for the final release. Thanks for the feedback.

**Pull request merged**
