### PR TITLE
docs(appcheck): add docs for appcheck iOS

### PR DESCRIPTION
**Pull request by rawatnaresh**
### Description

Updated docs for integrating AppCheck on iOS
### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
Very interesting! So the goal here is to add AppAttest functionality, but you've accomplished it 100% with documentation. That's an interesting approach 

Would a PR that added a "RNFirebaseAppCheckFactory" be better, perhaps? And you could instantiate it with a parameter specifying which factory you want? Default to "DeviceCheck" but also allow "AppAttest" or "AppAttestWithDeviceCheckFallback", and then instantiate them as needed?

Then the integration instructions would be an import statement (add the RNFirebaseAppCheckFactory) with explanations of the possible factory types?

Simply integration, much more robust solution since everyone could use working+tested Objective-C code

**Comment by rawatnaresh** [comment]
yeah that would be really great approach but I'm not familiar with writing obj-c code. sorry about that.

**Comment by mikehardy** [comment]
@rawatnaresh neither was I until I started proposing PRs to react-native modules. I'm still not great at it, but luckily react-native objective-c code is typically easy and "if it runs and passes tests, it works", which is not too high a bar

**Comment by mikehardy** [comment]
Closing in favor of the work I'm doing to actually add AppAttest support natively here #6847

**Pull request closed without merging**
