### PR TITLE
fix(expo): Update @react-native-firebase/auth iOS plugin

### PR DESCRIPTION
**Pull request by kreshnikalidema**
### Description
Fixes firebase auth plugin for Expo iOS. The current plugin doesn't work if the file is uploaded to EAS secrets, so it requires the `GoogleService-Info.plist` file to be present locally, in the root of the project folder to be able to initiate the build. After analyzing the code I realized that `@react-native-firebase/auth` iOS plugin does nothing more than `IOSConfig.Google.withGoogle` which is built-in `@expo/config-plugins`, and for this reason I have replaced it, also this replacement fixes the issue with EAS secret files.

### Related issues
https://github.com/invertase/react-native-firebase/issues/6785

### CODE REVIEW

**Comment by mikehardy** [comment]
Hey @kreshnikalidema 👋 !

This looks like a nice fix, lots of red/deleted lines and only a few green/added lines, my favorite type of PR if the functionality is maintained :-)

You state this:

>  that @react-native-firebase/auth iOS plugin does nothing more than IOSConfig.Google.withGoogle which is built-in @expo/config-plugins, and for this reason I have replaced it, also this replacement fixes the issue with EAS secret files.

Do you have a link ref to that `IOSConfig.Google.withGoogle` so I can make sure it still has the recaptcha URLs that the old style was adding? It should be linkable somewhere - it is difficult to review otherwise

Two other items:
- we need the CLA signed before we may accept any contributions from anyone, can you follow the instructions in the comment posted by the CLA bot above ☝️ ?
- you have not mentioned how you tested this, how did you prove to yourself that it was working after the change?

**Review by Wael-Ibn-Douma — APPROVED** [review]

**Comment by mikehardy** [comment]
@kreshnikalidema hey there 👋  this PR is still blocked on the CLA and the comments above - do you have any plans to complete it? Cheers

**Comment by kreshnikalidema** [comment]
@mikehardy  I apologize for the delayed reply. I have been very busy recently. I will deal with this today.

**Comment by mikehardy** [comment]
Hmm. This still seems useful. Anyone up for fixing this up to be current (in case that is needed) and supplying at as a PR with the CLA signed?

**Pull request closed without merging**
