### PR TITLE
#2207 fix Android notification with remote input

### PR DESCRIPTION
**Pull request by redexp**
fix for #2207

### CODE REVIEW

**Comment by mikehardy** [comment]
@redexp missing CLA
@Salakar obviously v5 is deprecated, and I'm not planning on doing a release unless someone posts an implementation of firebase crashlytics for it, but I'd merge this without release just so people know it looks good.

**Comment by redexp** [comment]
@mikehardy don't know why it shows that it not signed, but I sign it and if I click on "Details" it says "You have signed the CLA for invertase/react-native-firebase".

**Comment by mikehardy** [comment]
@redexp usually that indicates some sort of a mismatch between the email addresses in use, it is possible you have multiple email addresses registered with github and the CLA-bot is confused? There must be a FAQ on this somewhere :sweat_smile:  but I don't have a link handy sorry

**Comment by mikehardy** [comment]
@redexp I have official word from Invertase that they see you have signed the CLA so this is good to go! Thank you

**Comment by mikehardy** [comment]
I don't anticipate new releases on v5.x.x as mentioned before but it is officially in at least, and you can integrate master (or this specific commit hash, more safely) directly via a git dependency in your project, or as you choose perhaps by patch-package.

**Pull request merged**
