### PR TITLE
fix(crashlytics): Revert #4126

### PR DESCRIPTION
**Pull request by RyogaK**
### Description

The current exception won't be reported to crashlytics in both debug and release builds for now. Though I guess it was working at that time.
I think better to revert this line, because some problems reported after merged this code, and the original code is working at least in release builds for now.

Need to rethink the solution for debug builds I think.

### Related issues

#4374
#4126

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Why did you choose revert vs the appears-to-work solution here?

https://github.com/invertase/react-native-firebase/issues/4374#issuecomment-712252766

**Comment by RyogaK** [comment]
@mikehardy The new approach is currently being tested by some collaborators yet, so I think previous code is better than current code that seems not working for now until they decide the new approach is good.

**Comment by RyogaK** [comment]
@mikehardy 
I've seen both previous code and the new approach work in release builds, but I couldn't find a point where the new approach is better than the previous code, so I choose revert. I believe that the previous code that has proven track record of working is more reliable for now.

When new approach is tested enough and it is decided as better than this revert then, someone makes new PR I guess.

**Comment by mikehardy** [comment]
Yeah I was hoping the new code would have a better result in debug but it did not so I am inclined to agree. Belated thanks for making the pr in the first place, much appreciated

**Comment by RyogaK** [comment]
@mikehardy Is there any action I can do about this PR?

**Comment by mikehardy** [comment]
Nope just need to merge and release on our end. There was a ci failure I need to check so it will sit for 12hrs or so until start of the day for me tomorrow

**Comment by mikehardy** [comment]
Nope just need to merge and release on our end. There was a ci failure I need to check so it will sit for 12hrs or so until start of the day for me tomorrow

**Comment by mikehardy** [comment]
Superceded by #4426

**Pull request closed without merging**
