### PR TITLE
fix(admob, android): unity ads require Activity Context

### PR DESCRIPTION
**Pull request by zyzo**
### Description

Fix Admob crash from UnityAds with Admob Mediation.

Seems like a regression from https://github.com/invertase/react-native-firebase/pull/1892

Fixes https://github.com/invertase/react-native-firebase/issues/1792

### Related issues

#1792 
#1892

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by zyzo** [comment]
@mikehardy let me know if there is need for special logging in case of null Activity.

**Comment by mikehardy** [comment]
Thanks for this! I think rather than a regression this was a fix that landed on the v5 branch but never made it to the main branch! That's a shame but at least you are getting it now.

More than anything we need the CLA signed, we can't merge until that's done. The details link for the CLA check in the block of checks on the PR has more info to help you get it done

**Review by mikehardy — CHANGES_REQUESTED** [review]
Hi there - thank you for your patience!
This looks close, and while I think it would work, may I ask you to reshape it just a bit?

Specifically, now that I look closely it appears that `getCurrentActivity` being not-null is actually a requirement for the whole thing to work. So the change should not really be so concerned about whether it is null or not, rather since we use the Activity in three places now it should actually store it as a temporary variable, do the null check once, then use the temp variable in all three spots.

Specifically 
- the import of Context should not be necessary any more but you may need to import Activity
- the first `if (getCurrentActivity() == null)` check should be changed to (in pseudocode) 

```java
Activity currentActivity = getCurrentActivity();
if (currentActivity == null) { /* the existing error handling here, all the same */ }
currentActivity().runOnUiThread(() -> {
  // now just use currentActivity in place of getApplicationContext())
}
```

Unless I am missing something I think this will make for a very clean implementation and is even smaller than the proposed change.

What do you think?

**Comment by mikehardy** [comment]
for the avoidance of doubt: I'm +1 on the change idea in general though of course, looking forward to merging a fix here

**Comment by mikehardy** [comment]
@zyzo just in case you didn't see this :arrow_up:

**Comment by zyzo** [comment]
@mikehardy sure, I'll see what I can do tomorrow !

**Comment by zyzo** [comment]
@mikehardy ☝️

**Review by mikehardy — APPROVED** [review]
This looks really clean to me now, thank you!

**Comment by mikehardy** [comment]
As soon as CI finishes (it failed on the iOS e2e tests, which obviously has nothing to do with this PR, it should go green in a few minutes now that I've restarted it) I'll merge this and release

Thanks @zyzo !

**Comment by mikehardy** [comment]
Releasing as 10.8.1 right now, thanks!

**Pull request merged**
