### PR TITLE
feat(analytics): add method to retrieve the app instance id from the …

### PR DESCRIPTION
**Pull request by gabrielbull**
…service

### Description

Added method to retrieve the app instance id from the service. This is necessary when triggering GA events from a backend using the [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/ga4).

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Tested on both Android and iOS.

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! Thanks for this @gabrielbull - first let me say this is probably the cleanest first contribution I have ever seen, seriously, and that's a big help, thank you.

I'm a bit new to the GA4 thing - it appears that this is the relevant explainer for how the instance id is used, am I correct in thinking so?

https://support.google.com/analytics/answer/9213390?hl=en

If so it appears that setting the user-id would bet the first way to identify a user across properties, and the app instance id will be used as a fall back in certain analytics configurations? And you want to retrieve it here in order to pass it to e.g. cloud functions (or really any non-app location where you also want to log events related to this user?)

I *think* I'm understanding things but I want to make certain, and then I'll just re-read the docs and maybe add that link and a bit more explaining for anyone else coming at it with semi-fresh or totally fresh eyes, as I was

Otherwise looks almost good to go - I just approved the CI workflows so they are chewing through it now

**Comment by gabrielbull** [comment]
Hi @mikehardy. It's actually a bit different than the link you sent. It is a [required parameter](https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events?client_type=firebase#sending_events_2) for sending events to the Google Analytics Measurement Protocol. 

[Here is a cool tool](https://ga-dev-tools.appspot.com/ga4-event-builder/) you can use to create events and validate them using the [Measurement Protocol Validation Server](https://developers.google.com/analytics/devguides/collection/protocol/ga4/validating-events?client_type=gtag). 

For my specific use case (there are infinite use cases I'm sure), I'm using a Stripe webhooks to send purchase/subscription events to GA and this allows me to see the revenue on GA.

**Review by mikehardy — APPROVED** [review]
I thought about maybe putting more information (like a link to the doc you sent) explaining this would be needed for GA4 but I imagine since it's strictly required there and offered here with the obvious name that anyone who needs it won't have a feature discovery issue. So I think this is good to go right out of the gate and I learned some GA4 stuff. Great

**Comment by mikehardy** [comment]
Our CI has slowly fallen prey to entropy so it takes me a few attempts to get a clean run sometimes but this is marked for merge as soon as CI goes green and will go out as either v11.3.4 o whatever version is next. I literally just did a release tonight and I'd like to gather a bit more change before another, but knowing this will merge you should feel free to use the auto-generated patch-package set to integrate this locally until the new version comes out and you may evict them, if you don't already have a local patch installed - https://github.com/invertase/react-native-firebase/pull/5210/checks?check_run_id=2425065299

Thanks again

**Comment by gabrielbull** [comment]
Awesome news 🎉! And no worries about the patch-package or the release taking time. I've been using my own patch-package for a little while now.

**Comment by mikehardy** [comment]
Release 11.4.1 just went out with the change related to this among other fixes + features. Enjoy! :rocket:

**Pull request merged**
