### PR TITLE
chore(auth): fixed tests

### PR DESCRIPTION
**Pull request by dackers86**
Ci tests are currently failing on the auth module. This update should result in all tests passing

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Yeah I started seeing that yesterday and had it queued up but it was a head-scratcher for me. Thanks for looking into it! I had some PRs that merged and I wanted to release but not until this was sorted. Did they just ban the hard-coded user?

**Comment by dackers86** [comment]
My guess is that user had been added into the database. Either manually, or something have failed and not cleaned the user? Strange one!

**Comment by dackers86** [comment]
signInWithCredential() looks to have the same problem

**Comment by mikehardy** [comment]
Nope :-(

```

2020-09-04T14:07:49.0247990Z       ✓ it should error on login if user not found
2020-09-04T14:07:49.0347160Z     signInWithCredential()
2020-09-04T14:07:49.3792420Z       ✓ it should login with email and password
2020-09-04T14:07:49.5257070Z       ✓ it should error on login if user is disabled
2020-09-04T14:07:49.6943390Z       ✓ it should error on login if password incorrect
2020-09-04T14:07:50.0283810Z detox[5897] INFO:  at e2e/init.js:38:15 
2020-09-04T14:07:50.0337200Z  
2020-09-04T14:07:50.0337570Z detox[5897] WARN:  at e2e/init.js:39:15 
2020-09-04T14:07:50.0341250Z  ⚠️ A test failed:
2020-09-04T14:07:50.0383970Z detox[5897] WARN:  at e2e/init.js:40:15 
2020-09-04T14:07:50.0448110Z  ️   ->  it should error on login if user not found
2020-09-04T14:07:50.0471520Z detox[5897] WARN:  at e2e/init.js:47:13 
2020-09-04T14:07:50.0473680Z  ️   ->  Retrying in 1 seconds ... (1)
2020-09-04T14:07:55.3912930Z detox[5897] WARN:  at e2e/init.js:44:15 
2020-09-04T14:07:55.3914760Z     🔴  Retry #1 failed...
2020-09-04T14:07:55.3938950Z detox[5897] WARN:  at e2e/init.js:47:13 
2020-09-04T14:07:55.3941600Z  ️   ->  Retrying in 2 seconds ... (2)
2020-09-04T14:08:05.6918480Z detox[5897] WARN:  at e2e/init.js:44:15 
2020-09-04T14:08:05.6920350Z     🔴  Retry #2 failed...
2020-09-04T14:08:05.6929680Z detox[5897] WARN:  at e2e/init.js:47:13 
2020-09-04T14:08:05.6931060Z  ️   ->  Retrying in 3 seconds ... (3)
2020-09-04T14:08:20.9920120Z detox[5897] WARN:  at e2e/init.js:44:15 
2020-09-04T14:08:20.9944590Z     🔴  Retry #3 failed...
2020-09-04T14:08:20.9945860Z detox[5897] WARN:  at e2e/init.js:47:13 
2020-09-04T14:08:20.9947210Z  ️   ->  Retrying in 4 seconds ... (4)
2020-09-04T14:08:41.2585140Z detox[5897] WARN:  at e2e/init.js:44:15 
2020-09-04T14:08:41.2593610Z     🔴  Retry #4 failed...
2020-09-04T14:08:41.2610290Z detox[5897] WARN:  at e2e/init.js:47:13 
2020-09-04T14:08:41.2656080Z  ️   ->  Retrying in 5 seconds ... (5)
2020-09-04T14:09:06.5621960Z       1) it should error on login if user not found
2020-09-04T14:09:06.5650290Z 
2020-09-04T14:09:06.5737020Z detox[5897] INFO:  at e2e/init.js:53:11 
2020-09-04T14:09:06.5738710Z   ✨ Tests Complete ✨ 
2020-09-04T14:09:06.5753030Z detox[5897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onBeforeTerminateApp({
2020-09-04T14:09:06.5754690Z   deviceId: '7E67C931-571E-431B-92BD-2E5161E08E42',
2020-09-04T14:09:06.5755780Z   bundleId: 'io.invertase.testing'
2020-09-04T14:09:06.5761660Z })
2020-09-04T14:09:06.5795150Z detox[5897] DEBUG: [exec.js/EXEC_CMD, #10] /usr/bin/xcrun simctl terminate 7E67C931-571E-431B-92BD-2E5161E08E42 io.invertase.testing
2020-09-04T14:09:06.5804470Z detox[5897] DEBUG: [exec.js/EXEC_TRY, #10] Terminating io.invertase.testing...
2020-09-04T14:09:07.2082610Z detox[5897] TRACE: [exec.js/EXEC_SUCCESS, #10] 
2020-09-04T14:09:07.2102120Z detox[5897] DEBUG: [exec.js/EXEC_SUCCESS, #10] io.invertase.testing terminated
2020-09-04T14:09:07.2112270Z detox[5897] TRACE: [ArtifactsManager.js/LIFECYCLE] artifactsManager.onTerminateApp({
2020-09-04T14:09:07.2126160Z   deviceId: '7E67C931-571E-431B-92BD-2E5161E08E42',
2020-09-04T14:09:07.2127800Z   bundleId: 'io.invertase.testing'
2020-09-04T14:09:07.2128630Z })
2020-09-04T14:09:07.2207950Z 
2020-09-04T14:09:07.2232720Z   99 passing (2m)
2020-09-04T14:09:07.2240450Z   5 pending
2020-09-04T14:09:07.2255260Z   1 failing
2020-09-04T14:09:07.2258270Z 
2020-09-04T14:09:07.2261310Z   1) auth()
2020-09-04T14:09:07.2266910Z        signInWithCredential()
2020-09-04T14:09:07.2329140Z          it should error on login if user not found:
2020-09-04T14:09:07.2353880Z      TypeError: Cannot read property 'should' of undefined
2020-09-04T14:09:07.2360940Z       at failureCb (/Users/runner/work/react-native-firebase/react-native-firebase/packages/auth/e2e/auth.e2e.js:709:20)
2020-09-04T14:09:07.2362000Z       at tryCallOne (http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&sourceMapURL=true:6949:14)
2020-09-04T14:09:07.2368610Z       at http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&sourceMapURL=true:7050:17
```

**Comment by mikehardy** [comment]
@dackers86 exciting (?), it appears to have gotten through the auth section on e2e in ios. This could be the one...

**Review by mikehardy — APPROVED** [review]
success!

**Pull request merged**
