### PR TITLE
[BUGFIX][IOS][LINKS] Update linking restorationHandler implementation for iOS12

### PR DESCRIPTION
**Pull request by IljaDaderko**
### Summary
If project is used within Swift environment, there is an error thrown on iOS 12+ devices. Implementation needs to address this and this PR updates it as per official firebase https://firebase.google.com/docs/dynamic-links/ios/receive documentation for linking.

Fixes dynamic links for Swift based projects

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[IOS][ENHANCEMENT] [LINKS] - Updated universal link handling implementation for iOS 12

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
@Salakar something is not working on the detox patch in CI? https://ci.invertase.io/viewLog.html?tab=buildLog&buildTypeId=InvertaseOSS_ReactNativeFirebase_CiAndroidBuild&buildId=273

**Comment by Salakar** [comment]
CI back to normal, the failure relating to the detox patch was just a blip.

The current failure on here is because iOS is failing to build due to these chamges; see the logs of `ci.ios.build` - build error from the [logs](https://ci.invertase.io/viewLog.html?buildId=533&buildTypeId=InvertaseOSS_ReactNativeFirebase_CiIosBuild&tab=buildLog&_focus=198#_state=198):

image

And more errors above that on the logs

**Comment by IljaDaderko** [comment]
Had a typo, build passed locally for `test`. Fingers crossed for CI now.

**Comment by mikehardy** [comment]
I verified this vs the docs (thanks for the link @IljaDaderko ) and this looks clean. CI went green, I'm going to tag this for 5.4.x and +1 in it

I'll let it sit a couple days in case there any objections, then merge for release early next week I hope

**Comment by mikehardy** [comment]
@Salakar I don't have the Objective-C chops to adapt this v5 patch to your v6 code sadly, as it has skewed a bit, but you need to do the same thing right in this spot https://github.com/invertase/react-native-firebase/blob/master/packages/links/ios/RNFBLinks/RNFBLinksAppDelegateInterceptor.m#L55

**Comment by IljaDaderko** [comment]
@mikehardy I'll open pr to v6 as well, will try to do it some time tomorrow

**Comment by Salakar** [comment]
This is not required at all in v6, internally we swizzle the app delegate methods directly. So there's no longer any need to add it to the users project app delegate either, package is just install and go.

**Comment by mikehardy** [comment]
thank you @IljaDaderko ! this will be in 5.4.3

**Pull request merged**
