### PR TITLE
feat(crashlytics): add custom message ability to javascript stack traces

### PR DESCRIPTION
**Pull request by wilau2**
### Description

- Add ability to override the error message. Bringing back the `record custom error`.
- Alerting will be more usefull in firebase as well, it's sad to receive an Email with `index.bundle:123192038123:1239810238` 
- Easier triage in the the crashlytics dashboard 
- Add an initial line to the stack (the one that will be printed in the crashlytics UI, the aggregation works with this custom string as well)

### Related issues

- Alleviate the pain of not having sourcemap support in crashlytics
https://github.com/invertase/react-native-firebase/issues/2327
https://github.com/invertase/react-native-firebase/issues/1783

### Release Summary

- I made the parameter optional should not introduce any breaking change

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

image
image

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Cool! It is sad to see the bundle line numbers and character numbers ;-)

This seems fine, just need to figure out a couple CI checks
- Vercel is unrelated
- Android E2E is also unrelated, it's a flaky test I need to squish from a different PR
- Typedoc generation failure is new - not sure what's going on there and I need to triage

Holding off on approval until I know more on the typedoc problem - reasonably sure it's unrelated though, this all looks fine as I read the diffs

**Comment by mikehardy** [comment]
I have triaged all the CI failures and they are fixed on main branch now. Vercel and Typedoc generate were unrelated to this PR but were related to each other, fixed in the commit that fixed this #4600 

Android E2E flake fixed directly also         https://github.com/invertase/react-native-firebase/commit/e1b154a9315e8bd61cde0a44deb0635e99e5604d

This should be good to go, will rescan

**Review by mikehardy — APPROVED** [review]
Ok, LGTM - thanks!

**Comment by WookieFPV** [comment]
Awesome PR, I really like this feature.

How do you feel about going even a step further?
Instead of <unknown> it could also send a customizable string.
crashreporting

**Comment by mikehardy** [comment]
I am always open to "reasonable" PRs (where yes "reasonable" is fuzzy, but in general I mean as, maintains compatibility with firebase-js-sdk APIs, is not a breaking change, is well tested and documented, helps dev etc. This is an area that is kind of specific to us as we have react-native specific issues with stacks because of bundling, so I'm open to developer experience help in this area

**Pull request merged**
