### PR TITLE
fix(auth, android): fixed issue with apple sign-in on android

### LINKED ISSUE #3952: 🔥 Access to FIRAuthErrorUserInfoUpdatedCredentialKey with Apple Sign In
## Issue

Hello.  I am integrating Apple Sign in now.  It works great except for one small piece.  It's the flow from Firebase Anonymous -> Link User -> User already exists in Firebase -> Create new account.

When calling the code below and the firebase user already exists, the call fails which I think is expected because I am trying to reuse the nonce that was used in the first call to link accounts.  However I thought I should get an updated credential in the error response.

```
  const appleCredential = auth.AppleAuthProvider.credential(idToken, nonce)
  const linkResponse = await auth().currentUser.linkWithCredential(appleCredential)
  const signInResponse = await auth().signInWithCredential(appleCredential)
  (error: NativeFirebaseError: [auth/unknown] Duplicate credential received. Please try again with a new credential.)
```

Error
```
NativeFirebaseError: [auth/unknown] Duplicate credential received. Please try again with a new credential.
```

I can successfully sign in with Apple if I sign in again, however the user need to authenticate to Apple again.  

I found this issue and it looks the native side should return an updated credential key in this scenario that I can use on my next call without having to reauth with Apple.

`error.userInfo[FIRAuthErrorUserInfoUpdatedCredentialKey]` returned in the error.  Currently `error.userInfo` does not return this key.  This key would prevent another request to sign in.

https://github.com/firebase/firebase-ios-sdk/issues/4434

I see you closed a similar issue but I think firebase has implemented the native side. 

Thank you for your consideration.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:
(also saw the same issue on the latest version)
```json
    "@react-native-firebase/analytics": "^6.7.2",
    "@react-native-firebase/app": "^6.7.1",
    "@react-native-firebase/auth": "^6.7.1",
    "@react-native-firebase/crashlytics": "^6.7.1",
    "@react-native-firebase/dynamic-links": "^6.7.1",```
    "react-native": "0.61.5",

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.09 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /Users/someone/.rvm/gems/ruby-2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28
      Build Tools: 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.5
  npmGlobalPackages:
    *react-native*: Not Found```

<!-- change `[ ]` to `[x]` to select an option(s) -->

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

<!-- Thanks for reading this far down ❤️  -->
<!-- High quality, detailed issues are much easier to triage for maintainers -->

<!-- For bonus points, if you put a 🔥 (:fire:) emojii at the start of the issue title we'll know -->
<!-- that you took the time to fill this out correctly, or, at least read this far -->

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

### PR DESCRIPTION
**Pull request by nealmanaktola**
### Description

This fixes an issue with Apple sign on Android. iOS was fixed with this commit. iOS was fixed with this PR https://github.com/invertase/react-native-firebase/pull/4359. Note the solution is different. On iOS, it looks like we bubble the auth credentials back to js land and then retry login. Here, we attempt another login on auth collision errors

Also, note this deviates from the iOS solution. I am unable to grab the actual credentials from the AuthCredential object and return an error. So, instead, I proceed with a login

### Related issues

Fixes #3952 on Android

### Release Summary

Call `signInWithCredential` with updated credential when `linkWithCredential` throws `FirebaseAuthUserCollisionException`

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
This looks good to me! Thank you for your patience, merging this and will release it in an hour or so

**Comment by mikehardy** [comment]
I'm working on the auth emulator now in #4552 , which lets me re-enable the auth e2e tests, and it pointed out an error here.
In the non-Apple cause it fails and causes a NullPointerException, crashing the app now:

```
11-15 16:37:44.494 31029 31319 E Auth    : com.google.firebase.auth.FirebaseAuthUserCollisionException: The email address is already in use by another account.
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzem.zza(com.google.firebase:firebase-auth@@20.0.0:5)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzfx.zza(com.google.firebase:firebase-auth@@20.0.0:21)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzfq.zza(com.google.firebase:firebase-auth@@20.0.0:35)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzfs.zza(com.google.firebase:firebase-auth@@20.0.0:74)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzel.zza(com.google.firebase:firebase-auth@@20.0.0:61)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzp.zza(com.google.firebase:firebase-auth@@20.0.0:3)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzi.zza(com.google.firebase:firebase-auth@@20.0.0:2)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzgb.zza(com.google.firebase:firebase-auth@@20.0.0:29)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzfn.zza(com.google.firebase:firebase-auth@@20.0.0:83)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zza.zza(com.google.firebase:firebase-auth@@20.0.0:92)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zza.zza(com.google.firebase:firebase-auth@@20.0.0:241)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzf.zza(com.google.firebase:firebase-auth@@20.0.0:8)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzgb.zza(com.google.firebase:firebase-auth@@20.0.0:34)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzfn.zza(com.google.firebase:firebase-auth@@20.0.0:77)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zza.zza(com.google.firebase:firebase-auth@@20.0.0:85)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zza.zza(com.google.firebase:firebase-auth@@20.0.0:239)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzp.zza(com.google.firebase:firebase-auth@@20.0.0:11)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zza.zza(com.google.firebase:firebase-auth@@20.0.0:50)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zza.zzc(com.google.firebase:firebase-auth@@20.0.0:156)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzep.zza(com.google.firebase:firebase-auth@@20.0.0:156)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzbt.zza(com.google.firebase:firebase-auth@@20.0.0:29)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.firebase.auth.api.internal.zzbs.accept(Unknown Source:6)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.android.gms.common.api.internal.zach.doExecute(com.google.android.gms:play-services-base@@17.3.0:2)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.android.gms.common.api.internal.zah.zaa(com.google.android.gms:play-services-base@@17.3.0:9)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.3.0:192)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zab(com.google.android.gms:play-services-base@@17.3.0:157)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa(com.google.android.gms:play-services-base@@17.3.0:125)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(com.google.android.gms:play-services-base@@17.3.0:144)
11-15 16:37:44.494 31029 31319 E Auth    : 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-15 16:37:44.494 31029 31319 E Auth    : 	at com.google.android.gms.internal.base.zap.dispatchMessage(com.google.android.gms:play-services-base@@17.3.0:8)
11-15 16:37:44.494 31029 31319 E Auth    : 	at android.os.Looper.loop(Looper.java:193)
11-15 16:37:44.494 31029 31319 E Auth    : 	at android.os.HandlerThread.run(HandlerThread.java:65)
11-15 16:37:44.496 31029 31319 E AndroidRuntime: FATAL EXCEPTION: pool-53-thread-1
11-15 16:37:44.496 31029 31319 E AndroidRuntime: Process: com.invertase.testing, PID: 31029
11-15 16:37:44.496 31029 31319 E AndroidRuntime: java.lang.NullPointerException: null reference
11-15 16:37:44.496 31029 31319 E AndroidRuntime: 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(com.google.android.gms:play-services-basement@@17.3.0:2)
11-15 16:37:44.496 31029 31319 E AndroidRuntime: 	at com.google.firebase.auth.FirebaseAuth.signInWithCredential(com.google.firebase:firebase-auth@@20.0.0:144)
11-15 16:37:44.496 31029 31319 E AndroidRuntime: 	at io.invertase.firebase.auth.ReactNativeFirebaseAuthModule.lambda$linkWithCredential$28$ReactNativeFirebaseAuthModule(ReactNativeFirebaseAuthModule.java:1310)
11-15 16:37:44.496 31029 31319 E AndroidRuntime: 	at io.invertase.firebase.auth.-$$Lambda$ReactNativeFirebaseAuthModule$s2BlkFr6NYa4r5jx1U5v1tfWQT0.onComplete(Unknown Source:6)
11-15 16:37:44.496 31029 31319 E AndroidRuntime: 	at com.google.android.gms.tasks.zzj.run(com.google.android.gms:play-services-tasks@@17.1.0:4)
11-15 16:37:44.496 31029 31319 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-15 16:37:44.496 31029 31319 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

```

I'm going to wrap it in a try/catch with a reject in the style of the other rejects but I'm not sure what this indicates about the functionality - @nealmanaktola - you attest that this works for you on upgrade of anonymous to users to regular users from an apple sign in flow?

**Comment by nealmanaktola** [comment]
@mikehardy yep i can attest to that. hmm. i'll take a look to see if there is a cleaner fix, but this should work for now

**Comment by mikehardy** [comment]
cool - I think it's just that one set of use cases (which are exercised in the E2E tests but which I had temporarily disabled, so we didn't notice) works a little different than your use case. I'm confident enough in my java that I think both cases will be handled now but I will of course welcome any deeper thinking on your part, or (after the next release) a quick check to make sure we are still handling the apple sign on android flow since E2E is not exercising that apparently

**Comment by nealmanaktola** [comment]
@mikehardy it looks like with the latest native update with firebase auth bom v26 this fix does not work. I originally tested with the v25 and it worked.`getUpdatedCredential` returns null now.  I think we should revert this commit, what do you think?

**Comment by mikehardy** [comment]
Hi @nealmanaktola! but doesn't that imply that it is not working at all? Is there anything else we need to do, or does reverting it mean that things work as expected for android + sign in with apple?

**Comment by nealmanaktola** [comment]
@mikehardy yeah, unfortunately, that means it is not working at all with the latest native firebase auth sdk. I also don't know of a possible fix.

**Comment by mikehardy** [comment]
Reverting this and related #4552 in #5694

**Pull request merged**
