### PR TITLE
[IOS][LINKS] Apply new restorationHandler implementation

### PR DESCRIPTION
**Pull request by IljaDaderko**
### Summary
@Salakar this is universal linking issue we talked about with you earlier. Same one I opened react-native issue for https://github.com/facebook/react-native/issues/22716

I basically applied same implementation as apple has documented here https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623072-application?language=objc

And this fixed issues I was having in XCode 10 / ios 12. I tested this on a real device. I was not able to test with earlier iOS versions, but judging by apple's documentation this should be supported by iOS 8+ and previous implementation used `Any` instead of `UIUserActivityRestoring`, so there shouldn't be any issues here as well. And finally `restorationHandler` is not used as far as I can tell, it just needs to be passed in.

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [x] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - https://github.com/invertase/react-native-firebase-docs/pull/151
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan
Implement the change, check if it works on iOS devices that are running versions lower than 12. Has to be ran on a real device due to nature of simulator.

### Release Plan

[IOS][ENHANCEMENT] [LINKS] - Updated universal link handling implementation for iOS 12

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by IljaDaderko** [comment]
Related PR in react-native https://github.com/facebook/react-native/pull/22764

**Comment by Vanclief** [comment]
Will this be merged soon? Experiencing same issue,  @IljaDaderko will be our hero if we can get this working.

**Comment by mikehardy** [comment]
Hi there! I'm helping maintain the v5 branch along with @Salakar and I believe we have CI all sorted and tests green etc so the v5 branch can tolerate change now. If you rebase to current v5.x.x and push this again, I can check into it and try to get it merged for you. @IljaDaderko what do you think?

**Comment by IljaDaderko** [comment]
@mikehardy 👍 I completely forgot about this PR. I'll likely close it tomorrow and will submit new PR with few changes that are needed to support Swift (similar to one I submitted for rn Linking https://github.com/facebook/react-native/pull/22764)

**Comment by mikehardy** [comment]
works for me - thanks!

**Comment by IljaDaderko** [comment]
Closing in favour of https://github.com/invertase/react-native-firebase/pull/2216 cc @mikehardy

**Pull request closed without merging**
