### PR TITLE
Implement multiple databases

### PR DESCRIPTION
**Pull request by Chenjh1992**

### CODE REVIEW

**Comment by Salakar** [comment]
Thanks for the effort on this one,  took a look at this and it looks good.  Are you able to confirm the test app has trsts still passing and if possible add some multi instance tests as well? 

I've created two new databases on the test project you can use:

https://rnfirebase-2.firebaseio.com/
https://rnfirebase-3.firebaseio.com/

**Comment by Chenjh1992** [comment]
Hi @Salakar 
I don't have permission to access these projects. It showing:

> The project 'rnfirebase-2' either does not exist, or XXX doesn't have permission to view it."

**Comment by akshetpandey** [comment]
Implements #634

**Comment by Salakar** [comment]
@Chenjh1992 you shiuld have access in the tests repo,  they just need any auth to read or write,  i.e. anonymous auth

**Comment by Chenjh1992** [comment]
Web SDK: https://firebase.google.com/docs/reference/js/firebase.database
```
firebase.database() can be called with no arguments to access the default app's 
Database service or as firebase.database(app) or firebase.database(URL) to access
the Database service associated with a specific app or database URL.
```
@Salakar this implement would only support firebase.database(URL) but not firebase.database(app). So it required future work to keep consistent with google API.

**Comment by Chenjh1992** [comment]
I tested on
https://rnfirebase-2.firebaseio.com/
https://rnfirebase-3.firebaseio.com/
which can write/read data on two databases individually, but I didn't perform testing across two different firebase app.

**Comment by Salakar** [comment]
@Chenjh1992 have you managed to get support in for firebase.database(URL) and firebase.database(app). yet?

Thanks

**Comment by chrisbianca** [comment]
@Chenjh1992 @akshetpandey I've recreated this PR so that it's on a branch: https://github.com/invertase/react-native-firebase/pull/675

That way, we can take a look at getting support for both URL and App before merging it back into master.

I'll close this PR down.

**Comment by Chenjh1992** [comment]
@Salakar @chrisbianca Sounds good. I'll probably start working on support `firebase.database(app)` late Dec or early Jan

**Comment by atu** [comment]
How can I do if I want to use it right now?

**Comment by atu** [comment]
@Chenjh1992 do you need help with this?

**Comment by Chenjh1992** [comment]
@atu Sorry for the late reply. Unfortunately I don't have time to merge it to upstream. If you really need it, you can folk it and make the change. That's what my team doing now and it working well on live.

**Comment by akshetpandey** [comment]
@atu : This was already merged, see #675

**Comment by atu** [comment]
@akshetpandey do you mean already merged in master and inside a release? I'm struggling to make it work.

**Comment by atu** [comment]
@Chenjh1992 sounds great. Do you mean merging this branch to master? or just using the branch by itself?

**Comment by chrisbianca** [comment]
This hasn't made it into a release of react-native-firebase yet.  At the minute, we have it earmarked for the 4.2 milestone.

**Comment by Chenjh1992** [comment]
@atu just change your `package.json` point to that branch. 
btw, this branch is based on 3.1.1 not the latest. If you need any future on latest version, please rebase it by yourself.

**Comment by akshetpandey** [comment]
I am in the process of rebasing this change on 3.3.0... may be we can get it merged in sooner...

**Comment by atu** [comment]
@akshetpandey that would be fantastic :)

**Comment by chrisbianca** [comment]
FYI, this is here: https://github.com/invertase/react-native-firebase/pull/881

**Comment by Chenjh1992** [comment]
@atu hasShards just a internal flag, you don't need it.
`firebase.database()` would access the default database 
`firebase.database(url) e.g firebase.database(https://your_shard_database_url.firebaseio.com/).ref()` would access your shard database

**Comment by atu** [comment]
@Chenjh1992 Interesting. What about if there is more than 100,000 connection on the default database? Then people can't sign in anymore.

**Comment by akshetpandey** [comment]
Creating an instance is not the same as a connection. Connections will be handled by native firebase. Also can have upto 100,000 parallel connections per shard. Its unlikely that you will run into that issue but keep and eyes on the load graph in firebase console and if you are getting close to it, you will have to reshard that shard.

**Comment by Chenjh1992** [comment]
I don't think you would hit 100,000 limited on connection unless all your users are listening to default database and keep sync with it. I suggest do not use default firebase to syncing user data. Instead, do it in shard database. Basically, default firebase is more likely read-only data or global params, only developer able to change it, and you can handle users' game state in shard database.

**Comment by georgewwindsor** [comment]
"Error, Client dosnt have permission to access this data". anyone got advice here?

**Pull request closed without merging**
