### PR TITLE
Handle IOS notifications with custom action data in background when app is killed

### LINKED ISSUE #1542: Schedule background notification
It is possible to set schedule notification with react-native-firebase and receive it in background when app was closed? If yes so how or it should be only possible with push notification?

I created schedule notification listener but only get notif when app is open.

I tried package https://github.com/zo0r/react-native-push-notification and here everything working ;/

### LINKED ISSUE #1598: onMessage not called on iOS when app is killed by user
### Issue

I am trying to send a data message to the device. When the app is in the foreground/background this works as expected. But if the user has killed the app, when the app is next started none of the previous messages have arrived. I expected that the app would just get the messages waiting when it restarted. Push notifications are working as expected but I need a away of notifying my app of any messages (for example the user may receive a push but not tap on it and open the app manually, so no data would be sent to app in that case)

### Environment

1. Application Target Platform:

iOS (12.0 version)

2. Development Operating System:

Mac os High Sierra
3. Build Tools:

Xcode 10

4. `React Native` version:
0.56

5. `React Native Firebase` Version:

iOS (12.0 version)

6. `Firebase` Module:

messaging

7. Are you using `typescript`?

yes

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

### PR DESCRIPTION
**Pull request by dchersey**
### Summary

Handling iOS notifications when app is killed  requires native code. This is because iOS will wake the app only long enough to process the notification, and the RNNativeBridge does not load quickly enough to delegate handling to the javascript code.  Furthermore there is no opportunity in the existing notification registration code to register "categories" that enable custom notification actions in iOS.

This PR adds 2 delegate protocols that enable the native code to register a delegate to 
1) Define notification categories to enable custom actions on the lock screen or notification banner
2) Handle the actual notifications with action payload when the notification is responded to

There is no impact on code that does not register these delegates, and no impact on android code

example implementations for this to handle chat message quick-reply:

AppDelegate.h
```objective-c
@interface AppDelegate : UIResponder <UIApplicationDelegate,RNFirebaseNativeNotificationDelegate,RNFirebaseNativeMessagingDelegate>
```
AppDelegate.m
```objective-c
#pragma "RNFirebaseNativeMessagingDelegate"
- (void)registerFirebaseNotificationCategoriesAndActions: (UNUserNotificationCenter *) center {
  UNNotificationAction *replyAction = [UNTextInputNotificationAction actionWithIdentifier:@"REPLY_MESSAGE"
                                                                                    title:@"Reply"
                                                                                  options:UNNotificationActionOptionNone
                                                                     textInputButtonTitle: @"Send"
                                                                     textInputPlaceholder: @"Type your reply..."];
  NSArray *notificationActions = @[replyAction ];
  
  // create a category
  UNNotificationCategory *messageCategory =
  [UNNotificationCategory categoryWithIdentifier:
   [NSString stringWithFormat: @"%@.answer", [[NSBundle mainBundle] bundleIdentifier]]
                                         actions:notificationActions
                               intentIdentifiers:@[]
                                         options:UNNotificationCategoryOptionCustomDismissAction];
  
  NSSet *categories = [NSSet setWithObject:messageCategory];
  [center setNotificationCategories: categories];
} 


#pragma "RNFirebaseNativeNotificationDelegate"
- (void)firebaseNotificationResponseReceived:(NSDictionary *) response {
    
    NSLog(@"Native response received: %@",response);
    
    if ([response[@"action"] isEqualToString: @"REPLY_MESSAGE"]) {
        [self replyToMessage: response];
    }
    
    
}
```

### Checklist

- [n/a] Supports `Android`
- [X] Supports `iOS`
- [n/a] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [n/a] Flow types updated
- [n/a] Typescript types updated

### Test Plan

1. Implement the above example code on AppDelegate
1. Send a test notification using FCM with payload
```json
    {
      "notification": {
        "body": "Test notification",
        "title": "Test title",
        "sound": "default",
        "click_action": "answer",
        "badge": 0
      }.compact,
      "data": {
        "stuff": "stuff needed to process the action"
      }.compact
    }
```

Run on a device using a release build (background apps work in debug mode but killed apps do not) and use the mac console to monitor the NSLog statements above. Test with background and killed apps.  For foreground notifications, existing RNFirebase javascript code can be used to respond. 

### Release Plan
[IOS][ENHANCEMENT][NOTIFICATIONS] - Handle IOS notifications with custom action data in background when app is killed

[CATEGORY][type] [LOCATION] - Message

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by PrimeTimeTran** [comment]
@dchersey does this apply to data messages as well as notifications?

**Comment by Salakar** [comment]
@dchersey thanks for this PR, on my initial review your approach makes sense. 

I did though notice that you make use of [UserNotifications](https://developer.apple.com/documentation/usernotifications?language=objc) which requires iOS 10+ but the current min supported version by RNFB is iOS 9. 🙈 

RNFB v6.0.0 will be dropping support for iOS 9, so I could only make use of this PR then really - are you ok to delaying this until then?

**Comment by dchersey** [comment]
> @dchersey does this apply to data messages as well as notifications?
No, the only custom handler I implemented is for 
```objective-c
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
```
which is only invoked for message notifications with a custom category action that provides a response. 

My understanding is that IOS does not provide a way to receive `content_available` (silent) messages when the app is killed ... even if you want to store the action for later use.  So this only works for running or background apps, and I haven't tested this but I expect RNFB already handles this?

@Salakar regarding IOS 9, the code I modified already referenced UNNotificationCenter at `RNFirebase/messaging/RNFirebaseMessaging.m#162` so I think the implementation I patched must already depend on 10. I can wait until v6.0.0.0 -- in fact I think I have to because custom reply actions are also part of IOS 10 so the functionality would not work without it. 

I know this has been a big hole for RN apps to date on iOS ... Slack currently has a similar problem with their mobile app.  So long as you agree with the approach I am comfortable using my fork and rebasing as needed to keep up until 6.  Thanks!

**Comment by dchersey** [comment]
Just a quick FYI -- I suspect there may be a problem with the way this PR affects handling of data messages (content_available) without a notification component... so-called "silent notifications" on iOS . I am investigating and will post an update shortly.

**Comment by dchersey** [comment]
> Just a quick FYI -- I suspect there may be a problem with the way this PR affects handling of data messages (content_available) without a notification component when the app is in the foreground or running in the background... so-called "silent notifications" on iOS . I am investigating and will post an update shortly.

Update on this -- data messages are working fine in the foreground and background.

**Comment by Salakar** [comment]
Hey @dchersey 

Just a quick note to say I've not forgotten about this and that v6 is now on master, messaging & notifications is not there yet but I'll ping you as soon as it lands on master.

**Comment by dchersey** [comment]
what is the status of this?

**Comment by mikehardy** [comment]
messaging and notifications still aren't ported to v6 yet, but there are only a couple modules left in front of it. I suspect/guess it will be 1-2 months (initial to complete) for those modules. You can check/subscribe the v6 pinned issue or changelog to keep track of v6 progress

**Comment by dchersey** [comment]
> messaging and notifications still aren't ported to v6 yet, but there are only a couple modules left in front of it. I suspect/guess it will be 1-2 months (initial to complete) for those modules. You can check/subscribe the v6 pinned issue or changelog to keep track of v6 progress

Ok great ... I rebased onto 5.3.1 and found some conflicts which I resolved and will update the PR when I finish testing them

**Comment by mikehardy** [comment]
Hello again :-), I'm helping maintain v5 during the transition, and just finished a major fuzz-busting campaign on the v5 branch

I haven't reviewed this code yet, but if you rebase to v5.x.x current we should have solid CI support and that may give me the confidence to merge this in before v6 lands.

@dchersey can you give that a shot? Then I'll see what size / what compatibility impact this has for v5 while it's in "maintenance mode"

**Comment by mikehardy** [comment]
I was able to point this at the v5.x.x branch and it actually builds clean and would likely test clean as well if CI hadn't had an issue. If this is okay as an approach / design, we could merge this and release it in v5 straightaway since it has no impact on existing users

**Comment by dchersey** [comment]
Yes, I agree!

**Comment by mikehardy** [comment]
Ok - then I'll leave this to @Salakar for review from the "how do I feel about this totally new feature's design" perspective. But it doesn't blow up the branch and seems it would be trivially forward-ported after.

**Comment by dchersey** [comment]
Thanks!

**Comment by onkarjanwa** [comment]
@dchersey I tried the changes but it did not do anything.

Were you able to receive notification when app(IOS) is killed through data message? I am using `"react-native-firebase": "^5.5.6",`.

**Comment by dchersey** [comment]
My changes did not address the data message issue, only native interactive messages (with the custom response buttons on the notification and lock screen).

My app did not use data messages, but I believe a similar approach could be made to work for them if you want to give it a try.   I’m happy to share what I learned.

**Comment by onkarjanwa** [comment]
> My changes did not address the data message issue, only native interactive messages (with the custom response buttons on the notification and lock screen). My app did not use data messages, but I believe a similar approach could be made to work for them if you want to give it a try.   I’m happy to share what I learned.
> […](#)
> On Nov 14, 2019, 9:21 AM -0500, Onkar Lal Janwa ***@***.***>, wrote: @dchersey I tried the changes but it did not do anything. Were you able to receive notification when app(IOS) is killed through data message? I am using "react-native-firebase": "^5.5.6",. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

It will be great help if you could share anything that can help me regarding the issue.

**Comment by dchersey** [comment]
Pinging this PR again .... any chance of getting it merged?

**Comment by russellwheatley** [comment]
Hey @dchersey, thank you for your pull request. We’re no longer actively supporting `<= v5` development so I’m going to go ahead and close this. If this PR change still applies to the latest version of React Native Firebase then please feel free to raise a new PR targeting the latest version with your changes.

**Pull request closed without merging**
