### PR TITLE
Update quick-start.md

### PR DESCRIPTION
**Pull request by JaioSkura**
We found this issue in many projects after upgrading to firebase 6 and choosing wix's library for local notification. It is not easy to realize what is happening because the only way to follow it is with the logs in logCat. We hope this will help people and safe their time.

### Checklist

- [x] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[CATEGORY][type] [LOCATION] - Message

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Ehesp** [comment]
Thanks for the PR. I believe however this should be something document on the Wix side of things, rather than this library. This library handles FCM messages as the underlying SDKs intended, whereas external local notification libraries are attempting to override that behaviour.

cc @Salakar for thoughts.

Also, your PR has a fair few grammar/typos on it which would need sorting if it were to be merged.

**Comment by Salakar** [comment]
Also, can you try see if this behaviour happening on 6.4.0-rc4?

**Comment by JaioSkura** [comment]
@Ehesp I have been thinking about this, but I really think that should be in this documentation, as long as react-native-firebase/messaging' does not provide local notification functionality and 'react-native-notifications' is recommended as a library for that purpose. Wix team should not be aware that we are using both libraries together.

Is just my point of view, maybe I am wrong and we can sugest to them to change their library to avoid having this behavior in producction. I don't know if this is posible.

**Comment by Ehesp** [comment]
> Is just my point of view, maybe I am wrong and we can sugest to them to change their library to avoid having this behavior in producction. I don't know if this is posible.

I've no idea to be honest. I think something like this would be better placed in a guide/blog post somewhere? 

Also, which version are you using? We've just done a load of changes on 6.4 rc releases.

**Comment by JaioSkura** [comment]
@Salakar  yeah, I sow this new PR announcement in Discord channel, but couldn`t try yet. I will do it and let you know. Anyway, in that PR there are not included local notifications, are they?  We should continue using wix/react-native-notifications, or any other library who provides that functionality, aren't we?

**Comment by Ehesp** [comment]
You can display local notifications directly from FCM, only when the app is in the background (standard behaviour).

**Comment by JaioSkura** [comment]
> > Is just my point of view, maybe I am wrong and we can sugest to them to change their library to avoid having this behavior in producction. I don't know if this is posible.
> 
> I've no idea to be honest. I think something like this would be better placed in a guide/blog post somewhere?
> 
> Also, which version are you using? We've just done a load of changes on 6.4 rc releases.

yes, I will test it and let you know. Thanks!

**Comment by JaioSkura** [comment]
> You can display local notifications directly from FCM, only when the app is in the background (standard behaviour).

Yes I know, but I need to take only data and then decide if I show the notification or not. And apart from that, I also need to show notificactions even ir the app is in foreground. I will let you know what happens with 6.4.0-rc0.
Thanks a lot!

**Comment by JaioSkura** [comment]
Hi again people!

I try again with  6.4.0-rc4, and it seems to be fixed, even if I don't see why. Do you know why? just curiosity...


By the way, so great job!!!

**Comment by Salakar** [comment]
Probably fixed in RC4 as we now create our own `C2D_MESSAGE` listeners

If you're happy this is working for you now can you close this PR? Thanks for submitting it though!

**Pull request closed without merging**
