### PR TITLE
docs(hermes): hermes support

### PR DESCRIPTION
**Pull request by iqqmuT**
### Description

Updates docs about Hermes support.

### Related issues

Relates to #3549 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
I agree with this change - thank you. Of course we still need to get react-native-0.64 compatibility working but that's on my list for today (or tomorrow) - I will hold this for just a moment until that lands so people are not confused trying 0.64 and wondering why it doesn't work

**Comment by mikehardy** [comment]
Related #5031 / #5027

**Comment by mikehardy** [comment]
Just released react-native-firebase v11.1.2 with react-native 0.64 tested and working, this has no blockers - thanks!

**Comment by MohammadAzimi** [comment]
@mikehardy 
_**To support the Hermes JavaScript engine, React Native 0.64.0 or newer is required.**_
is it just about `@react-native-firebase/database` or all the modules?  https://github.com/invertase/react-native-firebase/issues/3549
To be more clear can I use other modules like `@react-native-firebase/crashlytics` with Hermes on react-native <= 0.64.0?

**Comment by mikehardy** [comment]
@MohamadKh75 database required proxy support so I think other modules would work, thinking a bit more advanced, if you get a newer version of the hermes engine to somehow work with older react-native (probably not recommended, I think they do their releases together) after hermes added proxy support all modules should work.

I will say that although I'm successfully using react-native 0.64.0 + 11.2.x here + hermes on iOS and Android all of this stuff is a bit experimental and new so I'm not sure exactly which versions are compatible with what, I just know that database package here needed proxy support and Hermes only recently got it

**Comment by MohamadKh75** [comment]
I guess I was mentioned wrong 😁

cc @MohammadAzimi @mikehardy

**Pull request merged**
