### PR TITLE
fix(analytics): update superstruct dependency

### LINKED ISSUE #8152: [🐛] Incompatibility of superstruct versions when using @react-native-firebase/app and @solana/web3.js.
**Problem Description**

The project uses two dependencies:
	•	@react-native-firebase/app, which relies on superstruct@^0.6.2.
	•	@solana/web3.js, which relies on superstruct@^2.0.2

When integrating both libraries, there is a version conflict because each library expects a different, incompatible version of superstruct: 
Once I import `import analytics from '@react-native-firebase/analytics';`
I get an error `_index.default is not a function (it is undefined)`

Yes, I know that different versions should be handled by the package manager - yarn, npm and so on, but I really don't know why it doesn't happen.

**Suggested Fix**

Upgrade the superstruct version in `@react-native-firebase/app` to be compatible with `@solana/web3.js` (e.g., ^2.0.2).

### PR DESCRIPTION
**Pull request by exzos28**
### Related issues

- Fixes #8152

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Hey! You might have cracked this one.

- I agree with the move to analytics
- the new-style struct typing looks correct

Let's see what CI thinks...

**Comment by exzos28** [comment]
Could you restart "Testing E2E Android" if necessary? It looks like the emulator did not start for some reason.

**Comment by mikehardy** [comment]
android CI failure was unrelated, re-running it
if the iOS runs completed I think this is good to go
Fantastic! This one has personally bothered me for a long time as I'm the one usually updating dependencies and I hated seeing it stuck. Much appreciated.

**Comment by RohovDmytro** [comment]
I do have an error while running the app, after resetting node_modules, yarn.lock and rebuilding the app from fresh.

````
 ERROR  TypeError: 0, _superstruct.define is not a function (it is undefined), js engine: hermes [Component Stack]
````

**Comment by mikehardy** [comment]
> rebuilding the app from fresh

@RohovDmytro 👋 looking in to this, what exact command are you running to rebuild the app from fresh?

**Comment by mikehardy** [comment]
When I last ran this, this afternoon, it was already using 21.60 and did not have a build failure:

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by RohovDmytro** [comment]
> > rebuilding the app from fresh
> 
> @RohovDmytro 👋 looking in to this, what exact command are you running to rebuild the app from fresh?

Resetting watchman cache, deleting node modules, yarn lock, running yarn install and then expo prebuild, and starting metro server with a reset config. I can provide the exact command line combo a bit later, if that would be important.

**Comment by RohovDmytro** [comment]
The app does build, but crashes in production and yields the error above during development.

**Comment by mikehardy** [comment]
I wonder fi you have the opposite problem of the issue that prompted the PR here, #5146 
That is, perhaps some other module of yours requires the old superstruct but now we rely on the new one?
Or perhaps there is some other expo-specific difference?

The app my script builds run fine in release and debug from completely clean setups (similar to what your commands do) - that's the whole point of that repro script really - to start from completely clean, do a reproducible series of steps, and have a full react-native-firebase integration run in debug and release modes. And it's working for me 🤔

**Comment by RohovDmytro** [comment]
> That is, perhaps some other module of yours requires the old superstruct but now we rely on the new one?

`supestruct` is used only via /analytics package.

├─ @react-native-firebase/analytics@npm:21.6.0
│  └─ superstruct@npm:2.0.2 (via npm:^2.0.2)
│
└─ @react-native-firebase/analytics@npm:21.6.0 [6c1df]
   └─ superstruct@npm:2.0.2 (via npm:^2.0.2)
   
That was the main reason I've assumed it would be enough to quickly blame open source and get away with commenting in PR discussion :)

Through years I've accumulated many ways of resetting caches. Let me try the bigest-badast--reset, maybe that will help :)

Either way, I would provide more actionable details or fix the issue my myself. Thanks for taking a look into it, @mikehardy.

**Comment by exzos28** [comment]
@RohovDmytro Did you update @react-native-firebase/analytics and @react-native-firebase/app **as well**?
Maybe attach your yarn.lock, I'll take a look.

**Comment by RohovDmytro** [comment]
Biggest-baddest-reset did not work. My next assumptions:
- I am using react-native 0.75.*
- I am using hermes
- Old arch


@exzos28 The amount of my dependencies in the current project made me mentally unstable. Please, be careful when looking at it. Thanks.

[yarn.lock.zip](https://github.com/user-attachments/files/17869751/yarn.lock.zip)

**Comment by RohovDmytro** [comment]
Downgrading to 21.5.0 makes the project work (event without rebuilding, wow!). Another assumption: do we have latest and greatest code under `21.6.0` tag?

I have to move on with my sprint and will stop pretending to be helpful. The final straw from me is to rename the project current repository into `@react-native-firearse/*`, but that's also might be as helpful as previous comments.

I will post more if I'll find more.

**Comment by exzos28** [comment]
Interesting point - I also have react-native 75 and an older architecture. 
And only updating superstruct allowed to use analytics package.

**Comment by mikehardy** [comment]
I looked through your yarn.lock @RohovDmytro and it all looks normal, unfortunately nothing jumps out at me there
My reproductions of success are

- the test app here with react-native 0.74.x + old architecture

https://github.com/invertase/react-native-firebase/blob/0103e12714de3c106128859eeadaf0fe07f9674c/tests/package.json#L32

And my make-demo.sh script which is the newest everything - rn0.76.2 + new architecture

and they both work - I just can't trigger this, and we haven't had others mention it yet either, so I suspect this is local somehow but I know what you mean by all the react-native project cleaning stuff (I've had PRs merged into react-native-clean-project - it's a constant battle). So it seems there may be something to this.

Unfortunately without a reproduction I can't move further with it, but I'll be listening in case something is posted

**Comment by mikehardy** [comment]
@LouisSyfer please be specific, "same issue" doesn't mean much when attached to a merged PR (which is not an issue, and has lots of discussion on it, with no resolution)

**Comment by LouisSyfer** [comment]
Ok sorry @mikehardy !
I have a very similar problem as described below. The dev build failed when I want to test it with Expo Go. I just removed the last version of all firebase package I have installed (21.6.1), and reinstalled the 21.2.0 version. The build is ok now. 
Sorry for the misanderstanding

**Comment by exzos28** [comment]
Is it possible to use react-native-firebase/* with Expo Go? wow

**Comment by exzos28** [comment]
@LouisSyfer If possible, please create an Issue with details and a reproducible repo and let's continue the discussion there.

**Comment by mikehardy** [comment]
Interesting.
In fact, it *may* be possible to use react-native-firebase in Expo Go with our new fallback support to firebase-js-sdk - at least on the web platform. Unsure on ios/android.
Historically there is no support for Expo Go though, as we use native modules not packed in the Expo Go app

**Comment by mikehardy** [comment]
I think you're going to need expo-dev-client and get busy with `prebuild`

**Comment by LouisSyfer** [comment]
Expo-dev-client is installed. 
I think maybe the latest versions of react-native-firebase are not compatible with SDK 52.

**Comment by mikehardy** [comment]
>  You suggested expo-dev-client. Can you elaborate how it can be used to debug or fix an issue?

That was working off the hypothesis that this was happening in Expo Go, and I hoped that building natively / locally with a `--prebuild` might do the trick.

Apparently not, unfortunately.

**Comment by RohovDmytro** [comment]
Summary:

`define` is undefined! :)

**Comment by exzos28** [comment]
I tried to create an repro and I was unable to reproduce the error.
I just initialized an empty expo project and installed expo-dev-client.

I ran it on android.

Put `console.log(define)` inside `node_modules/@react-native-firebase/analytics/lib/structs.js` and it exists: `[Function define].`

Repository:
https://github.com/exzos28/rnfirebase-superstruct

You can try to reproduce the error.

**Comment by exzos28** [comment]
@mikehardy I noticed that superstruct2.0 started using cjs modules, but Expo supports them ([link](https://github.com/expo/expo/blob/6c7ff2502b7300697671077ba2210e0f62aa4c9c/packages/%40expo/metro-config/src/ExpoMetroConfig.ts#L204)).

**Comment by exzos28** [comment]
Guys, could you run:
- `npx expo customize metro.config.js`;
- edit your metro.config.js like this:
```
const { getDefaultConfig } = require('expo/metro-config');
const config = getDefaultConfig(__dirname);
console.log(config.resolver.sourceExts)
module.exports = config;
```
- execute `npx expo`;
- and print here your logs.

**Comment by RohovDmytro** [comment]
@exzos28 wow. You're awesome. Very nice catch!

Indeed, the problem, obviously, was in metro.config :)

For historical reasons I had this:

````
config.resolver.assetExts.push('cjs');
config.resolver.sourceExts.push('mjs');
````

Removing this lines fixed an issue for me.

And this was breaking superstruct. It is still strange as billion other deps are working fine, but anyway, thanks you for your idea!

**Comment by exzos28** [comment]
@RohovDmytro that's strange.
I mean, you had already had mjs (and I hope cjs) in config.resolver.sourceExts.

Could you check, what is the result value contains in `config.resolver.sourceExts` after these pushes?

**Comment by RohovDmytro** [comment]
Input:

````javascript
config.resolver.assetExts.push('cjs');
config.resolver.sourceExts.push('mjs');

console.log(config.resolver.sourceExts);
console.log(config.resolver.assetExts);
````

Output:

````
[
  'ts',  'tsx',  'mjs',
  'js',  'jsx',  'json',
  'cjs', 'scss', 'sass',
  'css', 'mjs'
]
[
  'bmp',  'gif',  'jpg',  'jpeg',
  'png',  'psd',  'svg',  'webp',
  'm4v',  'mov',  'mp4',  'mpeg',
  'mpg',  'webm', 'aac',  'aiff',
  'caf',  'm4a',  'mp3',  'wav',
  'html', 'pdf',  'yaml', 'yml',
  'otf',  'ttf',  'zip',  'heic',
  'avif', 'db',   'cjs'
]
````

**Pull request merged**
