### PR TITLE
docs: note the v6 template init java package / ios bundle names

### PR DESCRIPTION
**Pull request by mikehardy**
This is the smallest PR ever, so I am rudely skipping your well-constructed PR template :-)

That said, you may still think the proposed wording chunk I added is terrible and reject, fine by me. Might be interesting to note what the ios bundle is called as well but I didn't check (sorry)

### CODE REVIEW

**Comment by Salakar** [comment]
Thanks for this @mikehardy - this is a good change so don't worry - best to be clear in the docs that the package name is based on the specified `<projectName>`

iOS is the same, so if you'd like to update this PR to mention that also that would be cool :) 

PR has 2 approvals anyway if you just want to go ahead and squash merge yourself, thanks.

**Comment by mikehardy** [comment]
Great - I'll wait till the #2126 thing is sorted out so I know I can actually do the thing and look at iOS, then I'll add the ios bit and hit the merge button

**Comment by mikehardy** [comment]
In XCode, it comes out like so: `org.reactjs.native.example.firebaseanalyzertests` FWIW

**Comment by mikehardy** [comment]
Okay, I triple-checked that my edits look good afterwards, going to squash and merge. Blame me later if it's terrible :-)

**Pull request merged**
