### PR TITLE
fix(dynamic-links,ios): resolveLink() does not always resolve

### PR DESCRIPTION
**Pull request by melvynhills**
### Description

Current implementation does not cover the case where `[[FIRDynamicLinks dynamicLinks] handleUniversalLink:linkURL completion:completion]` can return  `NO` without calling the completion block at all. ([See native iOS SDK method here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m#L443)).

### Related issues

`resolveLink()` promise never gets resolved when using a non-dynamic link. Android behaves correctly.

### Checklist

- I read the [Contributor Guide](/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Test just hangs forever without the fix.

### CODE REVIEW

**Comment by mikehardy** [comment]
@melvynhills Of course! I completely missed that it wasn't just using a completion handler but also had a return value 🤦  https://firebase.google.com/docs/reference/ios/firebasedynamiclinks/api/reference/Classes/FIRDynamicLinks#return-value_4

The original PR containing the error was by me here #3814  (incidentally, glad someone seems to be using it :-) )

I did a comparative re-read on the Android side https://firebase.google.com/docs/reference/android/com/google/firebase/dynamiclinks/FirebaseDynamicLinks#public-abstract-taskpendingdynamiclinkdata-getdynamiclink-uri-dynamiclinkuri and I don't believe it has this defect

I am restarting the CI Action 'Testing E2E / Android" which failed to run the tests completely because it's flaky, not because these tests had problems (they were not even executed during the run, so it's unknown)

**Comment by melvynhills** [comment]
> @melvynhills Of course! I completely missed that it wasn't just using a completion handler but also had a return value 🤦 https://firebase.google.com/docs/reference/ios/firebasedynamiclinks/api/reference/Classes/FIRDynamicLinks#return-value_4

Yeah sync+async combined APIs are kinda weird tbh!

> I did a comparative re-read on the Android side https://firebase.google.com/docs/reference/android/com/google/firebase/dynamiclinks/FirebaseDynamicLinks#public-abstract-taskpendingdynamiclinkdata-getdynamiclink-uri-dynamiclinkuri and I don't believe it has this defect

Indeed it doesn't. You handled it correctly by throwing `Dynamic link not found` in Android bridge module.

> I am restarting the CI Action 'Testing E2E / Android" which failed to run the tests completely because it's flaky, not because these tests had problems (they were not even executed during the run, so it's unknown)

Yeah they passed on my machine. Unhandled link is throwing `Dynamic link not found` on Android as well.

**Comment by mikehardy** [comment]
@Ehesp would love a review on this one so we have the required 2 and can merge, @melvynhills discovered (and fixed!) an obvious error in my original PR, with what appears to be the obvious fix and e2e cover

**Comment by giorgiofellipe** [comment]
@mikehardy @Salakar is this intended to be published anytime soon?

**Comment by melvynhills** [comment]
@giorgiofellipe it's been merged on July 5th, see above

**Comment by giorgiofellipe** [comment]
@melvynhills 
Yes, my bad. I realized right after commenting.

Btw, its not resolving short links, any clue why? Always returning `Error: [dynamicLinks/not-found] Dynamic link not found`;

**Comment by mikehardy** [comment]
@giorgiofellipe not sure why it is not working in your project, but I'm definitely resolving short links in my project in a live release, it should be working

**Pull request merged**
