### PR TITLE
docs(crashlytics): notes on what to expect for crashes

### PR DESCRIPTION
**Pull request by mikehardy**
### Summary

Related to #3084 and other user requests about the crash APIs

This is documentation only

Possibly worth mentioning that I frequently advise people "there is an edit button at the top of each docs page" but that's wrong for v6! I wasn't aware that the docs are auto-generated from the types defs but they are I think? Which is why I'm doing a PR against this file

Is there any way to hook up an edit button to go to the types files so my assertion about edit buttons is true again? Otherwise I can give more nuanced advice, but that edit button was a neat trick...

### Release Plan

[TYPES][ENHANCEMENT] [Crashlytics] - Add docs noting what traces will look like

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Salakar** [comment]
> Possibly worth mentioning that I frequently advise people "there is an edit button at the top of each docs page" but that's wrong for v6! I wasn't aware that the docs are auto-generated from the types defs but they are I think? Which is why I'm doing a PR against this file

Edit button is correct still, it's only the reference docs that don't have an edit button, instead each example has a `< >` button top right of the code block that will take you to the specific line in the relevant `.d.ts` file that can be edited;

image

Though I've just noticed a bug with that, the url it goes to has a double `/packages/` in it for some reason, perhaps @Phaen / @Ehesp could take a look, was working a while back, looks like it may be a underlying graphql change as it purely renders the `sourceUrl`, e.g. https://github.com/invertase/invertase/blob/master/packages/documentation/src/reference/kinds/Property.js#L41

**Comment by mikehardy** [comment]
Ah! I had not noticed that code block icon. Does that work if there are not examples? Is it possible to have an edit button at the top for the whole types file also? I have a pretty high hit-ratio on users making docs PRs after I beseech them so the easier it is, the more free docs PRs we'll get I'm thinking

**Comment by Salakar** [comment]
> Ah! I had not noticed that code block icon. Does that work if there are not examples? Is it possible to have an edit button at the top for the whole types file also? I have a pretty high hit-ratio on users making docs PRs after I beseech them so the easier it is, the more free docs PRs we'll get I'm thinking

@Phaen has done a PR internally to fix the broken links, Pablo could you take a look at adding the edit button onto reference pages also when you have some time, can copy the button from the normal pages and just change the link to point to the `sourceUrl` generated from the gatsby plugin iirc - thanks!

**Comment by Salakar** [comment]
Also PR LGTM, so will merge, thanks Mike!

**Pull request merged**
