### PR TITLE
docs(messaging): a little typo fix

### PR DESCRIPTION
**Pull request by benlondon**
### Description

A little typo fix in the Server Integration page of the messaging docs.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [] No

🔥

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Nice! Thank you

**Comment by mikehardy** [comment]
Needs CLA signed (even for typos, yes...) then can merge

**Comment by benlondon** [comment]
That's done now, should be good for merge!

**Comment by mikehardy** [comment]
:zap: ! Thanks

**Pull request merged**
