### PR TITLE
docs(footer): fixed typo twitter link.

### PR DESCRIPTION
**Pull request by m1y474**
### Description

Fix a documentation typo.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- This is a breaking change;
  - [ ] Yes
  - [x] No

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
:facepalm: nice catch, thank you

**Comment by mikehardy** [comment]
@m1y474  Could you sign the CLA please? Yes it is a tiny change but, the rules are the rules :laughing: - thank you!

**Comment by m1y474** [comment]
@mikehardy 
thanks for reply.
I signed the CLA, am I right about this screen you are talking about?
(Sorry for my poor English...)

**Comment by mikehardy** [comment]
That is what I mean @m1y474 - it appears there is an issue with *how* it was signed, the users are not connected somehow? The comment from the CLA bot has clickable links, text reproduced here

----
miyata seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by m1y474** [comment]
I changed the git history and it went crazy, so I'm going to raise the PR again.

**Pull request closed without merging**
