### PR TITLE
[android][database] database improvements

### LINKED ISSUE #893: [WEB SDK COMPAT] await .push() returns null, but works on web sdk
### Issue

Given the code:

```js
const messageRef = await firebase.database().ref('xxx/123/messages').push(message)
// messageRef = null
```

If I use `await` it returns null. But on web sdk it works just fine.
Just converted from firebase to react-native-firebase and faced this compatibility problem.
If I don't use `await` it works fine, but it should match the web.

Related but closed: #147, #696 

### Environment

iOS (not tested on Android)

1. Application Target Platform: macOS High Sierra

2. Development Operating System: iOS 11

3. Build Tools: ?

4. React Native version: 0.54

5. RNFirebase Version: 3.3.1

6. Firebase Module: Database

### LINKED ISSUE #1498: Firebase.database().ref().on() fires only once with Live Reload
```console
> react-native info
  OS: Windows 10
  Node: 8.9.4
  npm: 6.1.0

Packages: (wanted => installed)
  react: ^16.3.2 => 16.4.1
  react-native: ^0.55.3 => 0.55.3
```
```json
// package.json
{
    "dependencies": {
        "react": "^16.3.2",
        "react-native": "^0.55.3",
        "react-native-firebase": "^4.3.6",
        "react-native-google-signin": "^1.0.0-rc5",
        "react-navigation": "^2.14.2",
        "react-redux": "^5.0.7",
        "redux": "^4.0.0",
        "redux-thunk": "^2.3.0"
    }
}
```

```
// /android/app/build.gradle
dependencies {
  implementation(project(':react-native-firebase')) {
    transitive = false
  }

  implementation('com.crashlytics.sdk.android:crashlytics:2.9.3@aar') {
    transitive = true
  }

  // RNFirebase required dependencies
  implementation "com.google.firebase:firebase-core:16.0.3"
  implementation "com.google.android.gms:play-services-base:15.0.1"

  // RNFirebase optional dependencies
  implementation "com.google.firebase:firebase-ads:15.0.1"
  implementation "com.google.firebase:firebase-auth:16.0.3"
  implementation "com.google.firebase:firebase-config:16.0.0"
  implementation "com.google.firebase:firebase-crash:16.2.0"
  implementation "com.google.firebase:firebase-database:16.0.2"
  implementation "com.google.firebase:firebase-firestore:17.1.0"
  implementation "com.google.firebase:firebase-functions:16.1.0"
  implementation "com.google.firebase:firebase-invites:16.0.3"
  implementation "com.google.firebase:firebase-storage:16.0.2"
  implementation "com.google.firebase:firebase-messaging:17.3.1"
  implementation "com.google.firebase:firebase-perf:16.1.0"

  implementation "com.facebook.react:react-native:+"
  implementation "com.android.support:appcompat-v7:27.1.1"
  implementation 'com.android.support:support-annotations:27.1.1'

  implementation fileTree(dir: "libs", include: ["*.jar"])
  implementation "com.facebook.react:react-native:+"  // From node_modules
  
  implementation(project(":react-native-google-signin")){
    exclude group: "com.google.android.gms" // very important
  }
  implementation 'com.google.android.gms:play-services-auth:16.0.0'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
  from configurations.compile
  into 'libs'
}

apply plugin: 'com.google.gms.google-services'
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

I'm on an **Android**, **Connected Device**, with **Live Reload enabled**
I use Firebase for **Auth** and **Realtime Database**

**After Live Reload fires** (each time I save a file, basically), `firebase.database().ref().on()` **stops working.**

Here is my code:

I have a Redux Action to retrieve datas from the logged user
```javascript
// AppRedux.js
const reducer = (state = initialState, action) => {
    switch (action.type) {
        case 'setCurrentUser':
            return { ...state, currentUser: action.value }
            break;
        // { ... }
    }
}

const store = createStore(reducer, applyMiddleware(thunkMiddleware))
export { store }

const setCurrentUser = (user) => {
    return {
        type: "setCurrentUser",
        value: user
    }
}

const watchUserData = () => {
    return function(dispatch) {
        const { currentUser } = firebase.auth()

        if (currentUser) {
            console.log(currentUser.uid) // I always have the right uid, so firebase.auth() always works
            const ref = firebase.database().ref('users/' + currentUser.uid)

            ref.on('value', (snapshot) => {
                const user = snapshot.val()
                console.log(user) // I get there only once !

                dispatch(setCurrentUser(user))
            }, (error) => {
                console.log(error)
            })
        }
    }
}
export { setCurrentUser, watchUserData }
```

And I call this action in a pretty simple Component (screen)
```javascript
// Main.js

// { ... other imports}
import { watchUserData } from '../redux/AppRedux'


const mapStateToProps = (state) => {
    return {
        currentUser: state.currentUser
    }
}
const mapDispatchToProps = (dispatch) => {
    return {
        watchUserData: () => dispatch(watchUserData())
    }
}

class Main extends React.Component {
    constructor(props) {
        super(props)
    }

    componentWillMount() {
        this.props.watchUserData()
    }

    render() {
        const { currentUser } = this.props

        return (
            <View>
                <Text>Hello { currentUser && currentUser.firstname }!</Text>
            </View>
        )
    }
}
export default connect(mapStateToProps, mapDispatchToProps)(Main)
```

This piece of code works perfectly.. **only once**. When Live Reload fires, it won't work anymore.

Note that `firebase.auth()` still works and gives me the right `uid`, but `firebase.database().ref('users/' + currentUser.uid).on('value')` won't fire anymore, _even if I sign out then sign in again_.
Also note that **it works perfectly with *Hot Reloading* whereas it doesn't with *Live Reloading***.

I have to `npm run android` (which is equal to `react-native run-android`) for it to fire again.. until the next Live Reload.

### PR DESCRIPTION
**Pull request by Salakar**
### Summary

Includes the following fixes and associated tests:

 - Database listeners now correctly tearing down between RN reloads, additionally the correct react context is now used rather than old references to former instances (fixes handler on a dead thread event issue)
   - Fixes #1498 #1611 #1609
 - Fixed an issue where `Reference.toString()` incorrectly contains `//` instead of `/` when joining the parent and child paths
 - Rework `.push()` behaviour to match WebSDK and correctly return a Reference instance in all scenarios
   - Fixes #893 #1464 #1572

### Checklist

- [x] Supports `Android`
- [ ] ~Supports `iOS`~
- [x] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] ~Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)~
- [ ] ~Flow types updated~
- [ ] ~Typescript types updated~

### Test Plan

N/A

### Release Plan

 - [ANDROID] [BUGFIX] [DATABASE] - Database listeners now correctly tearing down between RN reloads. (Fixes #1498 #1611 #1609)
 - [JS] [BUGFIX] [DATABASE] - Fixed an issue where `Reference.toString()` incorrectly contains `//` instead of `/` when joining the parent and child paths.
 - [JS] [BUGFIX] [DATABASE] - Rework `.push()` behaviour to match WebSDK and correctly return a Reference instance in all scenarios. (Fixes #893 #1464 #1572)
 - [JS] [ENHANCEMENT] [UTILS] - Added a `firebase.utils().database.cleanup()` utility method which removes all database listeners.

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Salakar** [comment]
I still need to update/add more tests for database before I merge this, but if anyone with the tagged issue could test it that'd be super helpful👌

**Comment by FinCendikia** [comment]
I've tried it, still got the same messages from android logcat.
I am using 
"react-native": "0.57.1"
and
"react-native-firebase": "^5.0.0"

> W/MessageQueue: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at com.google.firebase.database.zza.zza(com.google.firebase:firebase-database@@16.0.2:1029)
        at com.google.firebase.database.obfuscated.zzcd.zza(com.google.firebase:firebase-database@@16.0.2:47)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:286)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:346)
        at com.google.firebase.database.obfuscated.zzk.zza(com.google.firebase:firebase-database@@16.0.2:5782)
        at com.google.firebase.database.obfuscated.zze.zza(com.google.firebase:firebase-database@@16.0.2:2164)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:256)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:5303)
        at com.google.firebase.database.obfuscated.zzn$zzc$2.run(com.google.firebase:firebase-database@@16.0.2:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by FinCendikia** [comment]
I've tried it, still got the same messages from android logcat.
I am using 
"react-native": "0.57.1"
and
"react-native-firebase": "^5.0.0"

> W/MessageQueue: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at com.google.firebase.database.zza.zza(com.google.firebase:firebase-database@@16.0.2:1029)
        at com.google.firebase.database.obfuscated.zzcd.zza(com.google.firebase:firebase-database@@16.0.2:47)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:286)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:346)
        at com.google.firebase.database.obfuscated.zzk.zza(com.google.firebase:firebase-database@@16.0.2:5782)
        at com.google.firebase.database.obfuscated.zze.zza(com.google.firebase:firebase-database@@16.0.2:2164)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:256)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:5303)
        at com.google.firebase.database.obfuscated.zzn$zzc$2.run(com.google.firebase:firebase-database@@16.0.2:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by FinCendikia** [comment]
I've tried it, still got the same messages from android logcat.
I am using 
"react-native": "0.57.1"
and
"react-native-firebase": "^5.0.0"

> W/MessageQueue: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at com.google.firebase.database.zza.zza(com.google.firebase:firebase-database@@16.0.2:1029)
        at com.google.firebase.database.obfuscated.zzcd.zza(com.google.firebase:firebase-database@@16.0.2:47)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:286)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:346)
        at com.google.firebase.database.obfuscated.zzk.zza(com.google.firebase:firebase-database@@16.0.2:5782)
        at com.google.firebase.database.obfuscated.zze.zza(com.google.firebase:firebase-database@@16.0.2:2164)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:256)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:5303)
        at com.google.firebase.database.obfuscated.zzn$zzc$2.run(com.google.firebase:firebase-database@@16.0.2:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by FinCendikia** [comment]
I've tried it, still got the same messages from android logcat.
I am using 
"react-native": "0.57.1"
and
"react-native-firebase": "^5.0.0"

> W/MessageQueue: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {822cef3} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at com.google.firebase.database.zza.zza(com.google.firebase:firebase-database@@16.0.2:1029)
        at com.google.firebase.database.obfuscated.zzcd.zza(com.google.firebase:firebase-database@@16.0.2:47)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:286)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:346)
        at com.google.firebase.database.obfuscated.zzk.zza(com.google.firebase:firebase-database@@16.0.2:5782)
        at com.google.firebase.database.obfuscated.zze.zza(com.google.firebase:firebase-database@@16.0.2:2164)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:256)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:5303)
        at com.google.firebase.database.obfuscated.zzn$zzc$2.run(com.google.firebase:firebase-database@@16.0.2:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by FinCendikia** [comment]
Tried it and still got the same messages from android logcat.

>  W/MessageQueue: Handler (android.os.Handler) {97259ec} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {97259ec} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at com.google.firebase.database.zza.zza(com.google.firebase:firebase-database@@16.0.2:1029)
        at com.google.firebase.database.obfuscated.zzcd.zza(com.google.firebase:firebase-database@@16.0.2:47)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:286)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:346)
        at com.google.firebase.database.obfuscated.zzk.zza(com.google.firebase:firebase-database@@16.0.2:5782)
        at com.google.firebase.database.obfuscated.zze.zza(com.google.firebase:firebase-database@@16.0.2:2164)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:256)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:5303)
        at com.google.firebase.database.obfuscated.zzn$zzc$2.run(com.google.firebase:firebase-database@@16.0.2:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)


But PR #1535 works for me 😕

**Comment by FinCendikia** [comment]
Tried it and still got the same messages from android logcat.

>  W/MessageQueue: Handler (android.os.Handler) {97259ec} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {97259ec} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:631)
        at android.os.Handler.sendMessageAtTime(Handler.java:600)
        at android.os.Handler.sendMessageDelayed(Handler.java:570)
        at android.os.Handler.post(Handler.java:326)
        at com.google.firebase.database.zza.zza(com.google.firebase:firebase-database@@16.0.2:1029)
        at com.google.firebase.database.obfuscated.zzcd.zza(com.google.firebase:firebase-database@@16.0.2:47)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:286)
        at com.google.firebase.database.obfuscated.zzab.zza(com.google.firebase:firebase-database@@16.0.2:346)
        at com.google.firebase.database.obfuscated.zzk.zza(com.google.firebase:firebase-database@@16.0.2:5782)
        at com.google.firebase.database.obfuscated.zze.zza(com.google.firebase:firebase-database@@16.0.2:2164)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:256)
        at com.google.firebase.database.obfuscated.zzn.zza(com.google.firebase:firebase-database@@16.0.2:5303)
        at com.google.firebase.database.obfuscated.zzn$zzc$2.run(com.google.firebase:firebase-database@@16.0.2:86)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)


But PR #1535 works for me 😕

**Comment by cookees** [comment]
how do i run this fix on my app without waiting for approval

**Pull request merged**
