### PR TITLE
feat(auth, multi-tenant): add multi-tenant (tenantID) support

### PR DESCRIPTION
**Pull request by xianlinbox**
### Description
When I working on the firebase auth, I found I can't set tenant id which is quite critical for working with Google Identity platform. In the repository discussion channel. there are 2 questions related with this also.

1. https://github.com/invertase/react-native-firebase/discussions/4462
2. https://github.com/invertase/react-native-firebase/discussions/4964

Then  I checked the[ Firebase iOS SDK,](https://github.com/firebase/firebase-ios-sdk/pull/6142) which actually provided tenantId for user to set it. So I created this PR to open this capability to React native Lib users.

### Related issues

No

### Release Summary

Support set tenant it in Firebase auth module.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [x] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan
`yarn tests:jest`

Test Suites: 8 passed, 8 total
Tests:       1 skipped, 95 passed, 96 total
Snapshots:   0 total
Time:        20.6 s

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by xianlinbox** [comment]
@mikehardy here is the new PR with my correct email, I will sign CLA here. Thanks very much for reviewing the code.

**Comment by Ehesp** [comment]
Awesome thanks for this.

**Comment by mikehardy** [comment]
Thank you! We still have some underlying CI issues which are very new - just last couple days - I have hopes of triaging those so this is fully green but there should be nothing wrong with this PR as it is, I'm planning on merging it - cheers @xianlinbox

**Comment by mikehardy** [comment]
There was an iOS compile error inadvertently hidden by the way we were calling xcodebuild

I just added these changes and pushed to your branch:
- rebased to current master
- fixed the incorrect use of unix pipes that hid compile errors
- fixed the compile error
- exposed the user.tenantId property for those that use multi-tenant
- added a simple E2E test that will always run, and some commented out ones that implementors may play with if they have access to a live firebase project with multi-tenant setup (we do not)


If it passes CI I think it will be good to go

**Comment by mikehardy** [comment]
This is out as of v11.1.0 - please test and if there's anything wrong let us know - cheers!

**Comment by kwong70** [comment]
Do we need to manually set the tenantId or is it auto-populated when a user signs in?

**Pull request merged**
