### PR TITLE
feat(messaging,android): save notification payload for messages that arrive in the foreground

### PR DESCRIPTION
**Pull request by aranda-adapptor**
### Description

Without this change, if another library shows a local notification for a foreground message, the payload is lost when the user opens the notification. In particular, the code in `ReactNativeFirebaseMessagingModule` `onNewIntent` and `getInitialNotification` will never be able to find the `RemoteMessage`.

Many people migrating from v5 want to show foreground notifications. This is possible with libraries such as `react-native-push-notification`, however tapping the notification to open the app will not find the payload for `onNotificationOpenedApp` and `getInitialNotification`. A small change is also required in `react-native-push-notification`: https://github.com/zo0r/react-native-push-notification/pull/1510

### Related issues

I can't find a specific issue at the moment, but I'm sure I saw some in the past!

### Checklist

- I read the [Contributor Guide](/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ X] Yes
- My change supports the following platforms;
  - [X ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ X] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X ] No

### CODE REVIEW

**Comment by mikehardy** [comment]
@aranda-adapptor we are missing the CLA signing on this so it is blocked. It just received the required approvals though, so you signing the CLA is the only thing missing

**Comment by mikehardy** [comment]
@aranda-adapptor please sign the CLA here for merge

**Comment by aranda-adapptor** [comment]
@mikehardy apologies, just got back from vacation. CLA signed.

**Comment by mikehardy** [comment]
Hi @aranda-adapptor ! Now I think it needs an update to the current code on master but I don't have the button to do that, so you may have to do it yourself, or @Salakar perhaps

**Comment by aranda-adapptor** [comment]
@mikehardy OK, latest changes from master merged. Took me a while to see the button for it right there, and I'm used to only doing that manually when there are conflicts.

**Pull request merged**
