### PR TITLE
feat(auth): add initial support for Apple auth provider

### LINKED ISSUE #2884: [Feature Request] Sign In With Apple
Looks like Firebase now supports sign in with apple:
image

Would be great to support that here and update the docs! Let me know if there's anything we can do to help 😄

### PR DESCRIPTION
**Pull request by Salakar**
### Summary

Implements Apple Authentication support for Firebase Authentication, tested usage via our [`@invertase/react-native-apple-authentication`](https://github.com/invertase/react-native-apple-authentication) package.

Fixes #2884.

### Checklist

- [x] Supports `iOS`
- [x] Typescript types updated

### Test Plan

Test code:
```js
import appleAuth from '@invertase/react-native-apple-authentication';
import { firebase } from '@react-native-firebase/auth';

// ...

const appleAuthRequestResponse = await auth.performRequest({
  requestedScopes: [
    AppleAuthRequestScope.EMAIL, 
    AppleAuthRequestScope.FULL_NAME
  ],
});

const { nonce, identityToken } = appleAuthRequestResponse;

if (identityToken) {
  const appleCredential = firebase.auth.AppleAuthProvider.credential(identityToken, nonce);
  const userCredential = await firebase.auth().signInWithCredential(appleCredential);

  console.warn(`Firebase authenticated via Apple, UID: ${userCredential.user.uid}`);
}
```

Output:
image

### CODE REVIEW

**Comment by MorgadoKnivet** [comment]
@Salakar I have a problem.
[auth/invalid-credential] The supplied auth credential is malformed or has expired.

 "@invertase/react-native-apple-authentication": "^0.1.0",
    "@react-native-firebase/app": "^6.2.0",
    "@react-native-firebase/auth": "^6.2.0",
    "@react-native-firebase/firestore": "^6.2.0",
    "@react-native-firebase/storage": "^6.2.0",
    "react-native": "0.60.5",

Screen Shot 2019-12-07 at 23 36 35
Screen Shot 2019-12-07 at 23 36 47

**Comment by mikehardy** [comment]
The text of errors is preferred over images - hard to see those when mobile etc - they can be made to look good as formatted text when you paste by enclosing in triple-backticks

I see credential revoked in the image though? seems like whatever you were doing you might need to get the user to retry as maybe too much time went by between apple sign-in and using the token with firebase?

**Comment by MorgadoKnivet** [comment]
I'm sorry, @mikehardy.

NativeFirebaseError: [auth/invalid-credential] The supplied auth credential is malformed or has expired.

I put a then/catch in return of await firebase.auth().signInWithCredential(appleCredential) to avoid/ cancel red screen.  I tried some times login with Apple, without success, with error. I logged in with email / password, logged out and tried again. Same problem.
` 
.then((response) => {
                    console.log("firebaseUserCredential")
                    console.log(response)
                    return {success:true, response}
                })
                .catch((error) => {
                    console.log(error)
                    return {success:false, error: ""}

                } )
`

**Comment by mikehardy** [comment]
Hmm - I'll see what I can see. I'm still on v6 but my goal for the evening was to apply essentially the exact same changeset from v6 to v5 and use it, so I'm working on this right now. The v5 and v6 auth code for react-native-firebase are effectively identical so if there is a problem I *should* see it. I have it successfully working with expo-apple-authentication + react-native-firebase v5 so all the other potential variables should be pretty isolated out.

Can you confirm that you can get the react-native-apple-authentication auth package example working independently? To confirm you have all the apple dev stuff set up correctly? There is so much to do there, I imagine it can go wrong fairly easily

**Comment by MorgadoKnivet** [comment]
Yes I Can. What's the best way to show you this?

Response of       const appleAuthRequestResponse = await auth.performRequest({
        requestedOperation: AppleAuthRequestOperation.LOGIN,
        requestedScopes: [
          AppleAuthRequestScope.EMAIL,
          AppleAuthRequestScope.FULL_NAME,
        ],
      });


authorizationCode: "ccff3f6c343c74763af32678c8915cb74.0.nrvxw.xF_UQAVbXQbEWH4_VEG8kA"
authorizedScopes: []
email: "morg.guilherme@gmail.com"
fullName:
familyName: "Morgado"
givenName: "Guilherme"
middleName: null
namePrefix: null
nameSuffix: null
nickname: null
__proto__: Object
identityToken: "eyJraWQiOiJBSURPUEsxIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJodHRwczovL2FwcGxlaWQuYXBwbGUuY29tIiwiYXVkIjoiY29tLm1vbnRhbmFzbGltcGlhcyIsImV4cCI6MTU3NTc3NjQ3OCwiaWF0IjoxNTc1Nzc1ODc4LCJzdWIiOiIwMDE1NzYuMWE2ZDcyMmZlOGNmNDA3NDhhZjRmYmVlMTZiYjA3M2UuMjM1MiIsIm5vbmNlIjoiZGYyYzY2NDExM2NiNzM4MzRkMGQyY2NjZjg4M2ZlYTQ0MWFhN2U0ZWJjNjA4ZTY1NTJkOGMyNzAyNzU1NDkyZCIsImNfaGFzaCI6IjR2R0laeEtTN3VOc1NkcWxSMTNVOEEiLCJlbWFpbCI6Im1vcmcuZ3VpbGhlcm1lQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsImF1dGhfdGltZSI6MTU3NTc3NTg3OH0.RM2m21uu3YXIQtUAYLc2R2hYbhehPnLIoWrkNpzD9yUiBf1MHdnr90Lu659jPpzAGnwtlhz6i-2I8IgXu4NFuFDQBg1-n8SiUW_JDcUW6NiYlNBedW_Ouh5HWzVrIoiatUjWTurnQB7Ii5bktgAUwIaROHAUAjoZreaqjES8HEAUqpkFGZLkXY_XGYZfoW6yFjxRi5HCHOC-8Cb41dKUZDupoWXp9KSd859M3ttTRbH4-_BETOhRm7CVWkWfUu2ANFbYwh2lj1-z4gW8P6NiiMWR6gFelrLCwpuCQTVaJu3qJu57y6Juq1roqj-VK67qCrnCKCdRh_wzD_LfEc0hFA"
nonce: "gbv2ILhpv7fEOBjTxn0gtjkZyL4wG-nR"
realUserStatus: 1
state: null
user: "001576.1a6d722fe8cf40748af4fbee16bb073e.2352"

**Comment by mikehardy** [comment]
that's plenty good enough - maybe too good - I'm not sure if any of that is privileged information or not 😅 - but I believe you and congratulations getting all that working, what a pain right? I work pretty methodically so it will be a little while until I have results / attempted reproduction on my side, but is my current task, so hopefully before too long (matter of hours? maybe tomorrow morning? I'm UTC-5 time

**Comment by MorgadoKnivet** [comment]
I`m thinking in privileged information, but I need it hahahahaha.
Thanks you for you help, I will delete the tokens hahaha

**Comment by mikehardy** [comment]
In Rio - cool - I'm in Ecuador and just met a group of mobile devs and VCs from Sao Paolo, things are really hopping over there in Brazil. Sorry @MorgadoKnivet though - I was unable to reproduce a problem, it all worked for me on v5 using the react-native-firebase patch I've posted in the gist for the linked feature request issue. That's not super helpful I bet, except to say that it seems to be possible to make it work. Why it isn't working is either a project-specific thing or an issue in the react-native-firebase v6 implementation, but I'd be surprised as I'm sure @Salakar checked it. 🤔

**Comment by mikehardy** [comment]
I just modified my v5.5.6 patch to match the v6 implementation and it's still working for me. 99% sure it's project-specific unfortunately as I'm now using the same style and the same module

**Comment by Salakar** [comment]
Definitely tested and worked on v6, screenshot in PR is from v6.

I'd suggust redownloading your google services plist file off the firebase console now that youve enabled apple auth, had a similar issue but worked for me after doing this, though it might have just been a side effect of a rebuild and cache clearing 🤷‍♂️

Also make sure your Firebase app id you made to get the credentials on the firebase console matches your bundle identifier name.

**Comment by mikehardy** [comment]
I did not re-download a plist for any of the new auth providers I used, and it worked for me, but it can't hurt. `npx react-native-clean-project clean-project-auto` is good for a full cache-busting but it is network-heavy to rebuild after of course.

**Comment by MorgadoKnivet** [comment]
Thanks again, people.
I tried downloading the GoogleService-Info.plist again, but without result. Clean cache, but without effect too. I will try de npx react-native-clean-project.

**Comment by Salakar** [comment]
It was a day before I tried again after I had the issue, maybe it takes sone time after enabling apple auth on the firebase console? No idea to be honest, are you on the latest version of RNAppleAuth too?

**Comment by MorgadoKnivet** [comment]
I  was in 0.2.0 version, but, after a yarn add and pod install, lib update to "@invertase/react-native-apple-authentication": "^0.1.0",

**Comment by mikehardy** [comment]
I am on 0.1.0, and it was immediate for me :-), I got all the apple stuff configured in tandem with console, rebuilt provisioning profiles and added entitlement, added the lib + code and done. Significantly, @MorgadoKnivet affirmed above he had the example working form the auth library, so it's something about the integration with firebase. Maybe not passing in the credential nonce correctly or similar?

**Comment by Salakar** [comment]
Interesting, are you specifying a `requestedOperation` specifically? I wasn't and it was working fine, like in the guide here: https://github.com/invertase/react-native-apple-authentication/blob/master/docs/FIREBASE.md

I noticed @MorgadoKnivet is specifying a `requestedOperation` in the code snippet, doubt that it makes any difference.

Only other thing I did before it was working was bin my Podfile.lock file, and fresh pod install again before rebuilding, perhaps a small firebase ios sdk version change fixed it?

**Comment by mikehardy** [comment]
I scan for and install pod version updates frequently so that could be it. I know for certain I am on absolutely latest ios firebase sdk pods. Or at least I was as of last night (they move quickly!). I am not doing a requestedOperation, I am using it about exactly as the example too

**Comment by MorgadoKnivet** [comment]
I will list steps to step I did.
- My app was rejected in Apple because have login with facebook and gmail (firebase) and haven't with apple.
- Yesterday, I started studying how to to sign with Apple and and set up the app in Certificates, Identifiers & Profiles, add Sign in with apple how "Enable as a primary App ID"
- I activated Apple Sign-In in firebase auth
- I created a key in developer.apple, keys.
- I made the "Configure Sign In with Apple", in developer.apple, more.
- I downloaded the @invertase/react-native-apple-authentication"
- Login data with Apple is returned successfully.
- I started the config with RNF
- I updated the RNF to 6.2 versions.
- I added the Capability to login with Apple on XCode
- The error : [auth/invalid-credential] The supplied auth credential is malformed or has expired. The error happens

**Comment by Salakar** [comment]
> Only other thing I did before it was working was bin my Podfile.lock file, and fresh pod install again before rebuilding, perhaps a small firebase ios sdk version change fixed it?

Try this @MorgadoKnivet, and also removing "requestedOperation"

**Comment by MorgadoKnivet** [comment]
I removed request operation, delete pod folder, delete Podfile.lock, install again and not working. I will cry hahahah.

```
 try {
        const appleAuthRequestResponse = await apple.performRequest({
            requestedScopes: [AppleAuthRequestScope.EMAIL, AppleAuthRequestScope.FULL_NAME],
          });

      console.log('appleAuthRequestResponse', appleAuthRequestResponse);

      const { identityToken, nonce } = appleAuthRequestResponse;
      if (identityToken) {
        // 3). create a Firebase `AppleAuthProvider` credential
        const appleCredential = firebase.auth.AppleAuthProvider.credential(identityToken, nonce);
    
        // 4). use the created `AppleAuthProvider` credential to start a Firebase auth request,
        //     in this example `signInWithCredential` is used, but you could also call `linkWithCredential`
        //     to link the account to an existing user
        const userCredential = await firebase.auth().signInWithCredential(appleCredential);
    
        // user is now signed in, any Firebase `onAuthStateChanged` listeners you have will trigger
        console.warn(`Firebase authenticated via Apple, UID: ${userCredential.user.uid}`);
      } else {
        // handle this - retry?
      }

      console.warn(`Apple Authentication Completed, ${this.user}, ${email}`);
    } catch (error) {
      if (error.code === AppleAuthError.CANCELED) {
        console.warn('User canceled Apple Sign in.');
      } else {
        console.log(error);
      }
    }
```

**Comment by mikehardy** [comment]
How frustrating! I can only think of three other things, low-probability so up to you to try or not

- I also set up all the OAuth flow (JWT stuff) in the firebase console and apple developer thing. The service keys, the callback handlers, the outbound email domain, domain verification and all of that. Serious pain in the butt. I don't think it should matter, I was just planning on doing apple sign-in for iOS<13 and Android later so thought I'd do all the config at once
- watch Xcode console to see if anything else is popping up under the covers, who knows?
- make a new firebase back-end project and use the rnfbdemo scripts to make the most minimal possible demo to reproduce? https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-v6.sh (or I guess for iOS only you could just make the bundle id match in Xcode and put your main plist file in there...might work)

**Comment by MorgadoKnivet** [comment]
I needed to focus on other features that eventually became more important, sorry for not trying to fix the error. During the week, I'll be back in it. Thanks, @mikehardy  and @Salakar

**Comment by mikehardy** [comment]
v5.6.0 is out on npmjs.com with this change in the main distribution for those that are still on v5

My patch file for react-native-firebase is now empty except a silly function timeout change I need because I have a slow-___ function, and all software is up to date, enjoy

**Comment by r0b0t3d** [comment]
@MorgadoKnivet I got this error when having multiple configs and **the bundle id in Xcode and firebase app are not match**. After correcting it, the error is gone.

**Comment by MorgadoKnivet** [comment]
@r0b0t3d You are my Hero

**Comment by luigi0229** [comment]
@r0b0t3d 
You saved me as well. Thanks for taking the time to share this. Highly appreciated.

**Comment by Berezhnov** [comment]
> @r0b0t3d
> You saved me as well. Thanks for taking the time to share this. Highly appreciated.

Hey, how you solve this? I have exactly the same bundle id in my Google-Services.plist and in Xcode for app.

**Comment by luigi0229** [comment]
@Berezhnov Hey - I think i tried editing the App on Firebase and adding the bundle ID, but that didn't do it. I ended up creating a new iOS app from firebase, adding the new bundle ID to it and completing the initial setup, and then re-downloading the Google-Services.plist file from that new iOS app. That did it for me. Let me know if that works for you.

**Comment by henokweldemicael** [comment]
@r0b0t3d @MorgadoKnivet @mikehardy OMG we were having this EXACT issue and worked on it for 3 days. Our issue was the bundle mismatch as well. Thank you all! Gotta love the open-source community.

**Pull request merged**
