### PR TITLE
Update installation-android.md

### PR DESCRIPTION
**Pull request by ckalpit**
updated version of com.google.firebase:firebase-perf from 11.0.0 to 11.0.4

### CODE REVIEW

**Comment by Ehesp** [comment]
@ckalpit This should be 11.2.0 actually, mind updating?

**Comment by ckalpit** [comment]
I am not sure if it will be compatible, my simple logic to set 11.0.4 is because other firebase libraries are also using 11.0.4 hence to avoid build time issues made it 11.0.4, also its working on my project.

we need to change all firebase libraries to 11.2.0 and run the project then we can do that too.

**Comment by Ehesp** [comment]
Yeah for new users though, 11.2.0 is what we want to target. Hopefully existing users like yourself will know!

**Comment by ckalpit** [comment]
So, I hope it will be accepted and merged soon because if someone is trying to use v2 they do not have any other build issues regarding this library.

**Comment by Salakar** [comment]
Merging as this is for the v2 docs, v3 only is 11.2.x+ - so this is fine.

**Pull request merged**
