### PR TITLE
Remove unavailable firebase reference

### PR DESCRIPTION
**Pull request by hillkim**
fix storage  reference

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [x] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
@hillkim we need you to sign the CLA then I can merge this

**Comment by hillkim** [comment]
@mikehardy Sorry am not following. What is it that needs to be signed exactly?

**Comment by hillkim** [comment]
@mikehardy  Cool! I found it!

**Comment by mikehardy** [comment]
merged thank you!

**Pull request merged**
