### PR TITLE
fix(app, android): firebase-android-sdk 29.0.3 to fix underlying NPE in 29.0.2

### PR DESCRIPTION
**Pull request by kenMarquez**
### Description

I'm updating the latest version of this library in our app so we can collect ANR issues using the latest version of Firebase Crashlytics, so when reading the Firebase Android BoM documentation I saw that they sent a patch yesterday to avoid a crash (NullPointerException) with the previous version of the firebase analytics library:
https://issuetracker.google.com/issues/210908929

So I think it will be wonderful to have the most stable version. 👍🏽 

image

### Release Summary

- firebase-android-sdk 29.0.3
- Add ANR collection support documentation

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

No breaking changes, only internal changes in the android firebase analytics library

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

🔥

### CODE REVIEW

**Review by mikehardy — DISMISSED** [review]
This is great, thanks! DIdn't realize they had a crash bug in 29.0.2 - they don't do formal releases on github so there is nothing to "watch" and I don't get notified 😅 - until I release this, please know that you can a) use the patch-package set from the actions here or b) you can do the override in your build.gradle to make sure you don't have any NullPointerExceptions - https://rnfirebase.io/#android

I'm going to edit the title to just be a fix though, it's only a patch release from them, should only be a patch release from us :-). Cheers!

**Comment by mikehardy** [comment]
Even for small fixes we need the CLA signed if you could? The details link on the CLA comment + action have more info on how

**Comment by kenMarquez** [comment]
@mikehardy Yes, of course! The CLA is already added it!

I see the Documentation / Spelling & Grammar job failed, i see the documentation is having an issue with the word `ANR` , 

Adding this word in the .spellcheck.dict.txt file should work, right?

**Comment by mikehardy** [comment]
Yep, adding it to the spelling dictionary sounds perfect

**Comment by kenMarquez** [comment]
Done @mikehardy, I am really amazed by all the checks you have set up in the library,
congratulations! is an amazing job

**Review by mikehardy — APPROVED** [review]

**Comment by mikehardy** [comment]
Awesome thanks. And yeah, quality is really really important for a library this fundamental. The automation is the only way to have confidence we maintain the level we expect while making changes

**Pull request merged**
