### PR TITLE
feat(template): upgrade to React Native 0.61.4

### PR DESCRIPTION
**Pull request by bobinrinder**
### Summary

Noticed the `template` is a little out of date...
Updated the `template` for `0.61.4` according to https://react-native-community.github.io/upgrade-helper/?from=0.60.5&to=0.61.4

### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan

As far as I can see there are no tests for this.
Maybe someone can do a little more extensive Android testing.

### Release Plan

[GENERAL][ENHANCEMENT] [template] - Upgrade to React Native 0.61.4

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Ehesp** [comment]
Thanks for doing this! We'll get it looked at.

**Comment by Salakar** [comment]
Thank you for this 🎉 will land this for v6.1.0

**Comment by mikehardy** [comment]
Just in time for 0.61.5 :rofl: - but joking aside, that one is just moving the patch version https://react-native-community.github.io/upgrade-helper/?from=0.61.4&to=0.61.5 and in general: awesome getting help to keep things fresh

**Comment by Salakar** [comment]
> Just in time for 0.61.5 🤣 - but joking aside, that one is just moving the patch version https://react-native-community.github.io/upgrade-helper/?from=0.61.4&to=0.61.5 and in general: awesome getting help to keep things fresh

Aye I saw, rip, will sort before release 👏

**Pull request merged**
