### PR TITLE
fixed in-query

### PR DESCRIPTION
**Pull request by devwheelty**
### Checklist

- [ ] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[CATEGORY][type] [LOCATION] - Message

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Ehesp** [comment]
Little confused about this one... it's just a plain object, so doing `OPERATORS.in` or `OPERATORS['in']` should make no difference.

What error are you having? ESLint complains when it has quotes as it's a single word.

**Comment by devwheelty** [comment]
I needed to execute "where" and the error "firebase.firestore().collection().where(_, *) 'opStr' is invalid. Expected one of '==', '>', '>=', '<', '<=', 'array-contains', 'array-contains-any' or 'in'." appears. I began debug to understand what the problem was and saw that the error was in the check "if (! This._modifiers.isValidOperator (opStr)) {(line 356)" and noticed that the problem could be due to the fact that the key "in" in the OPERATORS object does not see this key

**Comment by Ehesp** [comment]
Could you show me your full query code please?

**Comment by devwheelty** [comment]
@Ehesp    db.collection('products').doc("9uFiheGtsDWfJm3rHDal").get().then(resProduct => {
    let colorsId = resProduct.data().colors;
    let colorCollectionRes = db.collection('colors').where('id', 'in', colorsId).get().then( resColor => resColor.docs.map(c => c.data()))
  })

I have collections Products and Colors. Sub collection colors in product not suitable for me
types:
Product{:
id: string,
name: string,
colors: Array[ string ], // array colors id
img: string
}
Color{
id: string,
img: string
}

**Comment by Ehesp** [comment]
I don't think that's the issue, it's a basic object key check - whether it has quotes or not shouldn't matter. Are you sure that the code you posted above is the one which causes issues?

**Pull request closed without merging**
