### PR TITLE
[v6] Implement Crashlytics

### PR DESCRIPTION
**Pull request by Salakar**
**[crashlytics]** 

**Fixes**: #1643, #1848, #1964, #1920, #1884, #1783, #1966, #1940, #1447 

**Features/Bugs Todo:**
- [x] Capture JS Exceptions with stack traces automatically
- [x] Capture Unhandled Promise Rejections with stack traces automatically
- [x] [Android] `.crash()` not captured in debug due to RN RedBox; see [#1921](https://github.com/invertase/react-native-firebase/issues/1921)
- [x] Support [advanced user identifier features](https://boards.invertase.io/admin/board/react-native-firebase/p/support-crashlytics-advanced-user-identifier-features)
- [x] [Android] Enable Crashlyics NDK reporting by default ([gist](https://gist.github.com/kelset/45c1a739722c9cdb5ffcfa858addb845))
- [x] Support toggling native crash logging off/on (e.g. disable in DEV)
  - [Disable Crash Reporting](https://firebase.google.com/docs/crash/disable-sdk)
- [x] Support toggling JS crash logging off/on (e.g. disable in DEV)

---

**Migration to v6 Todo:**

- [x] JS
- [x] iOS
- [x] Android
- [x] Tests (>=95%)
- [x] 100% Firebase API cover
- [x] Flow Types
- [x] TS Types
- [x] Update Readme

---

**Other Todo (non-crashlytics specific):**

As v6 is still very much WIP; some internals don't exist yet that are required by Crashlytics; these have been implemented as part of this PR. Also fixed some minor internals/tests issues that have been flagged during work on Crashlytics.

- [x] [**ios**] Static framework support for all modules
- [x] [**ios**] Implement CocoaPods Firebase RN modules auto-loader script
- [x] Implement `firebase.json` config loader; Android & iOS
- [x] [**tests**] Fix false positive tests that catch errors (tests did not check that errors actually threw) 
- [x] [**android**] Cleanup manifest permissions for all modules
- [x] [**android**] Implement Content provider base class
- [x] [**android**] Investigate/fix issue where `setDataCollectionDefaultEnabled` is false by default in Firebase - it disables Crashlytics reporting

---

Additionally supports all Crashlytics features from https://github.com/corymsmith/react-native-fabric/issues/214 and more - if anyone wants to migrate.

### CODE REVIEW

**Comment by stevenjohn** [comment]
Do we have an ETA for this merge please? We cant implement FB until this is fixed. Thanks :)

**Comment by Salakar** [comment]
> Do we have an ETA for this merge please? We cant implement FB until this is fixed. Thanks :)

@stevenjohn what Firebase services do you intend to use? This change is only going to be compatible with v6 - only a few Firebase services are complete and production ready on v6.

**Comment by stevenjohn** [comment]
> > Do we have an ETA for this merge please? We cant implement FB until this is fixed. Thanks :)
> 
> @stevenjohn what Firebase services do you intend to use? This change is only going to be compatible with v6 - only a few Firebase services are complete and production ready on v6.

Crashlytics - thats the main reason...

**Comment by Salakar** [comment]
@stevenjohn this should help you get started with this: [[Firebase Crashlytics for React Native](https://invertase.io/blog/firebase-crashlytics-for-react-native?utm_source=github&utm_medium=changelog)]

**Comment by mikehardy** [comment]
@Salakar - I am really excited about the javascript level crash reporting (stacks, unhandled promise rejections) but I am using unmigrated 5.x modules. Just looking for a yes or no here but the tracking issue for 6.x #2025 says "if all the Firebase services that you use are already listed there then you are good to migrate to the v6.0.0" - now if I was hard-headed, would there be any possible way to use some 5.x and some 6.x packages as an unholy mix? I'm guessing the answer is a simple clear "no" but wanted to make sure.

**Comment by Salakar** [comment]
@mikehardy to be honest; I've not tried mixing them but I can only imagine there would be some native SDK version conflicts, though maybe not with the latest v5.3.0 release as they are both on the same versions now I believe.

I'd say if you want to try then go for it; don't let me hold you back 😅 that comment is purely there so that we don't get swamped with issues saying it doesn't work with both etc. If you do try please let me know your findings (on [this issue](https://github.com/invertase/react-native-firebase/issues/2025)) and I can update the changelog to reflect.

**Comment by mikehardy** [comment]
>  I can only imagine there would be some native SDK version conflicts, though maybe not with the latest v5.3.0 release

This was the thing that made me think "maaaybe" - I think every part of everything is up to current now... if I try it I'll publish results. Thanks!

**Comment by sampsonjoliver** [comment]
@mikehardy I'm interested in results if you have any! I _might_ try this as well

**Comment by mikehardy** [comment]
I haven't tried it yet and I must be honest my project's roadmap is so deep right now I doubt I'll get to it before v6 is out for all the modules I use unless this somehow becomes a diagnostic road block for us on crashes more than the testing time, but I'll certainly report back if I try.

**Comment by ashishfeels** [comment]
[Android] .crash() not captured in debug due to RN RedBox; see #1921
is this issue has been fixed i'm unable to get stack traces fro debug mode idk why ?
@Salakar  and hats-off for such a wonderful module.

**Comment by fjmorant** [comment]
> I haven't tried it yet and I must be honest my project's roadmap is so deep right now I doubt I'll get to it before v6 is out for all the modules I use unless this somehow becomes a diagnostic road block for us on crashes more than the testing time, but I'll certainly report back if I try.

@mikehardy Any result??

**Comment by mikehardy** [comment]
@fjmorant I haven't tried personally after going deeper into v5 (actually doing some releases) and doing a v6 demo. They are not going to work together

**Comment by fjmorant** [comment]
> @fjmorant I haven't tried personally after going deeper into v5 (actually doing some releases) and doing a v6 demo. They are not going to work together

Thx , that’s what I thought

**Pull request merged**
