### PR TITLE
[v5] Android: Notifications: add support for channelId & image fields

### PR DESCRIPTION
**Pull request by mcuelenaere**
### Checklist

- [X] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan

Send a test notification to the device with the app in foreground and `console.log()` the message.

### Release Plan

[ANDROID][ENHANCEMENT] [NOTIFICATIONS] - channelId is parsed in remote notifications
[ANDROID][ENHANCEMENT] [NOTIFICATIONS] - imageUrl is parsed in remote notifications

### CODE REVIEW

**Comment by mikehardy** [comment]
I don't believe this is necessary? 

https://github.com/invertase/react-native-firebase/blob/v5.x.x/android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java#L83


https://rnfirebase.io/docs/v5.x.x/notifications/reference/AndroidNotification#channelId


Please feel free to re-open if I am wrong, but please start by opening an issue with a clear description of the problem being solved - there is no context here

**Comment by mcuelenaere** [comment]
The issue here is that the following code:
```javascript
firebase.notifications().onNotification(notification => {
  console.log(notification);
});
```
will never include the Android notification channelId (`notification.android.channelId`), since the code required to populate it was absent.

As a result, if a remote notification comes in (for a specific notification channel) while the app is in the foreground, we can never show it with the correct notification channel (since the JS side is unable to obtain the proper `channelId`).

I cannot re-open this issue (lack of permissions).

**Comment by mikehardy** [comment]
Ah okay, I see what you mean - and I reopened it before I just read some more. This begs the question then, in general should those two areas of code - android-specific remote-message-parsing and local-notification-construction be in sync? It looks to me like they are out of sync at the moment? @Salakar / @Ehesp - ?

**Comment by mcuelenaere** [comment]
The same is true for `RemoteMessage.getImageUrl()` and `largeIcon`, although that's not a 1-on-1 mapping; it should probably be put in the `bigPicture` field.

Do you want me to do this in a separate PR?

**Comment by mikehardy** [comment]
One PR is fine by me - thanks for checking on other attributes - note that we specifically have an Android CI issue right now that is backing up v5 releases so even if this were merged (I'm +1 on it, for what it's worth) you'll need to either use patch-package to pull the patch in or depend on git pinned to the v5.x.x branch or the post-merge commit hash until we get releases moving again. Not ideal, sorry

**Comment by mikehardy** [comment]
I have approved, I requested a review from @Ehesp and/or @Salakar  just in case, and CI will fail on ci.android.test no matter what at the moment, whether this change would pass or not.

**Comment by mikehardy** [comment]
Okay, I'm going to merge this in now that there has been a second set of eyes - sorry I misunderstood at first but thank  you for being persistent! :-)

You can depend on the commit hash from git in your package.json until we get this released and you'll be guaranteed to get reproducible builds that way. We'll hopefully get v5 android e2e tests sorted out in CI soon so we can release a 5.5.7 with this in it

**Comment by mikehardy** [comment]
Or actually - I can't override the required status but @Salakar maybe this and the compile fix https://github.com/invertase/react-native-firebase/pull/2476 could be merged by you regardless? I'm using #2476 daily and this one seems fine also - I'll handle fallout if not

**Comment by Salakar** [comment]
Done 💥  

😄

**Comment by mikehardy** [comment]
Thanks man - I'll try to finish up v5 RN60 upgrade but my work project has some nifty iOS issue right now that's fully consuming.

**Pull request merged**
