### PR TITLE
Allows react-native-firebase to be used via Podfile with use_frameworks!

### PR DESCRIPTION
**Pull request by MoOx**
Ref https://github.com/invertase/react-native-firebase/issues/252#issuecomment-501692286

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan

I tested this  like that:

- installed rnfirebase v5 via yarn
- modified podspec in `node_modules/react-native-firebase/ios` after install (as in the pr)
- run `pod install` (cocoapods read the podspec)
- I can build my app without the 3 tricks mentionned in https://github.com/invertase/react-native-firebase/issues/252#issuecomment-501692286

### Release Plan

[IOS][BUGFIX] [ios/RNFirebase.podspec] - Allows react-native-firebase to be used via Podfile with use_frameworks!

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
Thanks for this! The podspec is obviously fundamental to the project so I need to very carefully test this one out, but I appreciate the PR, and if it fixes (at minimum) our header search path issues, oh man that will be helpful :-)

**Comment by MoOx** [comment]
@mikehardy take your time, my trick referenced is perfect & enough for me atm.

**Comment by cmcewen** [comment]
Just wanted to say I tried this out and it worked for me as well. Thanks @MoOx!

**Comment by mikehardy** [comment]
I appreciate the success report, thank you for testing and reporting back

**Comment by mikehardy** [comment]
This should be in 5.5.4 - thanks @MoOx !

**Comment by martintreurnicht** [comment]
@MoOx You are a champ my friend, this saved me so much time!

**Comment by mikehardy** [comment]
released 5.5.4 with use_frameworks support today!

**Comment by namvoeh** [comment]
I got this error after upgrading to 5.5.4, my project has `use_framework!`
```
▸ Compiling RNFirebaseInstanceId.m
▸ Compiling RNFirebaseAdMobRewardedVideo.m
▸ Compiling RCTConvert+UIBackgroundFetchResult.m
▸ Compiling RNFirebaseAdMob.m
▸ Compiling RNFirebaseLinks.m
▸ Compiling RNFirebaseFirestoreCollectionReference.m
** ARCHIVE FAILED **


The following build commands failed:
CompileC /Users/distiller/Library/Developer/Xcode/DerivedData/EHLife-gjmlboqelaiuboeparmweacbgttk/Build/Intermediates.noindex/ArchiveIntermediates/EHLife/IntermediateBuildFilesPath/RNFirebase.build/Release\ Staging-iphoneos/RNFirebase.build/Objects-normal/armv7/RNFirebaseAdMobRewardedVideo.o RNFirebase/admob/RNFirebaseAdMobRewardedVideo.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
```

**Comment by MoOx** [comment]
I just tried & didn't get any issue while creating an archive via Xcode. 

Here is my podfile (cleaned to keep firebase stuff only as I have things I cannot share)

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
swift_version = '4.2'

target 'ADM' do
  use_frameworks!

  # React-Native
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  # React-Native dependencies
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  # Firebase
  pod 'Firebase', '~> 5.20.0'
  pod 'Firebase/Core', '~> 5.20.0'
  pod 'Firebase/Analytics', '~> 5.20.0'
  pod 'Firebase/DynamicLinks', '~> 5.20.0'
  pod 'Firebase/Messaging', '~> 5.20.0'

  # React-Native libraries
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
end

post_install do |installer|
  # see also ios/fastlane/Fastfile 'compileBitcode' option for fastlane
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

Note here that I removed private stuff that are not interesting. I just kept the last part which is mandatory for me as I have some other deps that can't work with ENABLE_BITCODE.
Maybe you can try this & see if this change a thing?

**Comment by namvoeh** [comment]
@MoOx cause you are using `pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'` to setup `react-native-firebase`, I am using another way which is recommended https://rnfirebase.io/docs/v5.x.x/installation/ios#Option-1:-Link-React-Native-Firebase-(Recommended)

your current way is not recommended according to https://rnfirebase.io/docs/v5.x.x/installation/ios#Option-2:-Cocoapods-(Not-Recommended)

**Comment by MoOx** [comment]
@namvoeh this might become the new recommended approach, see https://github.com/invertase/react-native-firebase/issues/2223#issuecomment-505970964

If you don't use RNFirebase from podfile, I don't see how the change in this PR might affect you. Podfile is only used when using the method I used, that you seems not to use.

**Comment by namvoeh** [comment]
you are right. Moreover, RN 0.60 will support cocoapods integration by default https://github.com/facebook/react-native/releases/tag/v0.60.0-rc.3.

**Comment by IljaDaderko** [comment]
@MoOx I started getting this error with v5.5.4 https://github.com/firebase/firebase-ios-sdk/issues/1916

I think it is due to introduction of recursive header search path made in this pr https://github.com/invertase/react-native-firebase/pull/2235/files#diff-1b2b06e7c58d8929c91f917ce51a7454R28

I assume it is due to this path as this is the comment that solved issue for many people https://github.com/firebase/firebase-ios-sdk/issues/2260#issuecomment-461601816 and it mentions it.

I wanted to make a PR that removes this change, but am not sure about consequences, could you suggest if it's alright to do it, as this will become bigger issue now since 0.60 is out and uses CocoaPods

**Pull request merged**
