### PR TITLE
Fix wrong RNFirebaseDatabase implementation

### PR DESCRIPTION
**Pull request by zoontek**
`RNFirebaseDatabase` => `RNFirebaseDatabaseReference` in `RNFirebaseDatabaseReference.m`

screen shot 2017-08-10 at 22 26 51

### CODE REVIEW

**Comment by egunsoma** [comment]
Can this bug cause something like DB events not firing on iOS device?

**Comment by zoontek** [comment]
No, this bug only appear when you don't use the Firebase Database SDK

**Comment by phips28** [comment]
please merge!

**Comment by chrisbianca** [comment]
Just released v2.1.2 which addresses this issue more thoroughly
@zoontek thanks for raising - most people have the database enabled which is why it's not come up previously.

**Pull request closed without merging**
