### PR TITLE
crash fix

### PR DESCRIPTION
**Pull request by Jobeso**
to get the library working we need to take these versions otherwise the app would crash

### CODE REVIEW

**Comment by chrisbianca** [comment]
@Jobeso do you have the error message from the crash?  I'm keen to understand what was different between 11.0.0 and 11.0.4 that fixed the problem.

**Comment by Jobeso** [comment]
@chrisbianca Unfortunately there is no error. We were able to build and install the app but not to start it. It crashes instantly. Maybe because of an dependency but with the 11.0.4 version it works.

**Comment by chrisbianca** [comment]
If you use `adb logcat` you'll be able to find the error from the device logs.  It may take a bit of digging but it would be useful for us to understand what the problem is.

**Comment by Jobeso** [comment]
Hey,
here are the logs you were asking for. I hope this helps.

`08-04 14:00:38.389  2365  3176 I Icing   : Usage reports 0 indexed 0 rejected 0 imm upload false
08-04 14:00:38.392  2122  3617 I UpdateIcingCorporaServi: UpdateCorporaTask done [took 389 ms] updated apps [took 389 ms]
08-04 14:00:38.498  3632  3632 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
08-04 14:00:38.499  3632  3632 D AndroidRuntime: CheckJNI is ON
08-04 14:00:38.513  3632  3632 D ICU     : No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
08-04 14:00:38.541  3632  3632 E memtrack: Couldn't load memtrack module (No such file or directory)
08-04 14:00:38.541  3632  3632 E android.os.Debug: failed to load memtrack module: -2
08-04 14:00:38.541  3632  3632 I Radio-JNI: register_android_hardware_Radio DONE
08-04 14:00:38.550  3632  3632 D AndroidRuntime: Calling main entry com.android.commands.am.Am
08-04 14:00:38.558  1621  2092 I ActivityManager: START u0 {flg=0x10000000 cmp=de.tellonym.app/.MainActivity} from uid 0 on display 0
08-04 14:00:38.622  3632  3632 D AndroidRuntime: Shutting down VM
08-04 14:00:38.630  1294  1600 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x933 imply creation of host color buffer
08-04 14:00:38.637  1621  2282 I ActivityManager: Start proc 3641:de.tellonym.app/u0a83 for activity de.tellonym.app/.MainActivity
08-04 14:00:38.641  3641  3641 I art     : Not late-enabling -Xcheck:jni (already on)
08-04 14:00:38.650  1621  1640 D         : HostConnection::get() New Host Connection established 0x7f1e9b258e80, tid 1640
08-04 14:00:38.706  3641  3641 D AndroidRuntime: Shutting down VM
08-04 14:00:38.706  3641  3641 E AndroidRuntime: FATAL EXCEPTION: main
08-04 14:00:38.706  3641  3641 E AndroidRuntime: Process: de.tellonym.app, PID: 3641
08-04 14:00:38.706  3641  3641 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbr; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbr' appears in /data/app/de.tellonym.app-1/base.apk)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5153)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4748)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4688)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-04 14:00:38.706  3641  3641 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-04 14:00:38.710  1621  1984 W ActivityManager:   Force finishing activity de.tellonym.app/.MainActivity
08-04 14:00:39.016  1621  1984 I WindowManager: Screenshot max retries 4 of Token{cba4162 ActivityRecord{7ca682d u0 de.tellonym.app/.MainActivity t72 f}} appWin=Window{cd6fe5 u0 Starting de.tellonym.app} drawState=1
08-04 14:00:39.021  1621  1621 W art     : Long monitor contention event with owner method=void com.android.server.am.ActivityManagerService.crashApplication(com.android.server.am.ProcessRecord, android.app.ApplicationErrorReport$CrashInfo) from ActivityManagerService.java:12502 waiters=0 for 298ms
08-04 14:00:39.104  1621  3367 I OpenGLRenderer: Initialized EGL, version 1.4
08-04 14:00:39.126  1621  2852 I AccountManagerService: getTypesVisibleToCaller: isPermitted? true
08-04 14:00:39.144  1294  2025 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
08-04 14:00:39.165  1294  1600 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
08-04 14:00:39.173  1294  1600 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
08-04 14:00:39.437  2365  2696 I Icing   : Indexing 8E09C8DAA63BF05A55BD199B035C8815AAF1E3E3 from com.google.android.googlequicksearchbox
08-04 14:00:39.487  2365  2696 I Icing   : Indexing 897AC81A6D9524F926355F9189954FB3C84139FB from com.google.android.gms
08-04 14:00:39.517  2365  2696 I Icing   : Indexing done 8E09C8DAA63BF05A55BD199B035C8815AAF1E3E3
08-04 14:00:39.521  1621  1635 W ActivityManager: Activity pause timeout for ActivityRecord{7ca682d u0 de.tellonym.app/.MainActivity t72 f}
08-04 14:00:39.539  2365  2696 I Icing   : Indexing done 897AC81A6D9524F926355F9189954FB3C84139FB
08-04 14:00:39.686  1621  1640 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
08-04 14:00:44.170  2365  3655 W PlatformStatsUtil: Could not retrieve Usage & Diagnostics setting. Giving up.
08-04 14:00:45.330  1621  1773 I ActivityManager: Killing 2578:com.android.email/u0a29 (adj 15): empty #17
08-04 14:00:49.561  1621  1635 W ActivityManager: Activity destroy timeout for ActivityRecord{7ca682d u0 de.tellonym.app/.MainActivity t72 f}`

**Comment by Jobeso** [comment]
@chrisbianca Is that helpful or do you need additional information?

**Comment by chrisbianca** [comment]
@Jobeso Yes, this shows that the app crashed because of a missing google library.  See this line:

```
08-04 14:00:38.706  3641  3641 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbr; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbr' appears in /data/app/de.tellonym.app-1/base.apk)
```

As for what exactly caused it, that's impossible for me to say without replicating your setup.  I'd assume that one of the libraries in 11.0.0 didn't have a dependency listed so wasn't pulling it through automatically.  Something that might have been fixed in a later version.

I'd take it that you changed nothing else in your setup other than the library version?

**Comment by Jobeso** [comment]
Hey,
I am glad that this helped. The only thing I needed to change was this to version 11.0.4 to get it to work so now it is running perfectly wothout problems.

chrisbianca <notifications@github.com<mailto:notifications@github.com>> schrieb am Mo. 7. Aug. 2017 um 09:21:

@Jobeso<https://github.com/jobeso> Yes, this shows that the app crashed because of a missing google library. See this line:

08-04 14:00:38.706  3641  3641 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzbr; or its super classes (declaration of 'com.google.android.gms.common.internal.zzbr' appears in /data/app/de.tellonym.app-1/base.apk)


As for what exactly caused it, that's impossible for me to say without replicating your setup. I'd assume that one of the libraries in 11.0.0 didn't have a dependency listed so wasn't pulling it through automatically. Something that might have been fixed in a later version.

I'd take it that you changed nothing else in your setup other than the library version?

**Comment by chrisbianca** [comment]
Thanks @Jobeso I've merged this PR now

**Pull request merged**
