### PR TITLE
Updated typings for PhoneAuthListener

### PR DESCRIPTION
**Pull request by sowdri**
I've fixed the typings for `PhoneAuthListener`. Let me know if further changes are required. Thanks,

### CODE REVIEW

**Comment by sowdri** [comment]
#1181

**Comment by sowdri** [comment]
Guys, any updates on this? thanks,

**Comment by chrisbianca** [comment]
Thanks for this - sorry for the delay in getting it merged.

**Comment by Salakar** [comment]
@sowdri thanks for sorting this; will be landing in the [v4.3.0 release](https://github.com/invertase/react-native-firebase/releases/tag/v4.3.0)

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
@sowdri this is now live in the [v4.3.0 release](https://github.com/invertase/react-native-firebase/releases/tag/v4.3.0), thanks again!

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Pull request merged**
