### PR TITLE
[FIX][TYPESCRIPT][functions] add overload constructor for changing functions region or app

### PR DESCRIPTION
**Pull request by tkow**
#1963

fix constructor of functions module.

### Summary

We must do unnecessary cast functions type when it's not.

### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [ ] Flow types updated
- [x] Typescript types updated

### Release Plan

[ TYPES] [BREAKING][FUNCTIONS] - add overload constructor type of functions for changing region or app

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
@tkow I'm planning a 5.4.x release shortly, and a v5.5.x which will allow small breaking changes. You listed this as a breaking change but the new type signature lists all parameters as optional, so I don't believe this is breaking. What do you think?

If I am right and it is not breaking, we can ship this in a v5.4.x release shortly

**Comment by tkow** [comment]
@mikehardy I think so, too. It should be not broken unless changing native firebase sdk.

**Comment by mikehardy** [comment]
@Salakar I hate to keep pointing TeamCity things which are sort of meta, but as it's new CI hopefully it's helpful? It's blocker for merges though either way.

Anyway, I updated this one from branch on the way to merge, but it didn't get updated status. So I looked and it looks like all the 3 compatible agents for ci.analyse are disconnected? https://ci.invertase.io/viewQueued.html?itemId=981&buildTypeId=InvertaseOSS_ReactNativeFirebase_CiAnalyse&tab=queuedBuildOverviewTab

**Comment by mikehardy** [comment]
thank you @tkow ! merged, and will be in 5.4.3

**Pull request merged**
