### PR TITLE
[iOS] disable logging to application console in production

### PR DESCRIPTION
**Pull request by hakonk**
Thanks for making this lib! 

With regards to logging, I have seen that `NSLog` is called on several occasions. As this will lead to printing to the console in production, I believe an improvement can be to toggle logging using preprocessor macros. As a suggestion, I've replaced the `NSLog` statements with a macro called `DLog`. This solution is based on: https://obt.io/programming/2012/01/alternatives-nslog

Alternatively, one can add other log levels if that is desired.

### CODE REVIEW

**Comment by Salakar** [comment]
@hakonk welcome and thanks for this 🎉 

We're just sorting a couple CI issues then we'll get the ball rolling on this 👍 

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by hakonk** [comment]
Awesome! Let me know if you need anything from me 😄

**Comment by Salakar** [comment]
@hakonk ok I think CI issues have been sorted - could you pull in master on your PR branch and sync back up - so that the CI triggers.

Thanks 👍

**Comment by Salakar** [comment]
Thanks, this CI failure is not related, I'll sort and re-run.

**Pull request merged**
