### PR TITLE
docs(auth): update docs to handle error

### PR DESCRIPTION
**Pull request by CyrusZei**
### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by CyrusZei** [comment]
https://github.com/invertase/react-native-firebase/CONTRIBUTING.md is dead 
CleanShot 2022-02-04 at 18 59 54@2x
?

**Comment by mikehardy** [comment]
> https://github.com/invertase/react-native-firebase/CONTRIBUTING.md is dead


@CyrusZei  Should be here - where was this link, so it may be updated? https://github.com/invertase/react-native-firebase/blob/main/CONTRIBUTING.md

**Comment by CyrusZei** [comment]
This link when you are doing a PR

CleanShot 2022-02-06 at 18 16 58@2x

**Comment by CyrusZei** [comment]
I looked at the one in the repo for the path to the contributor guide
CleanShot 2022-02-06 at 18 28 43@2x

**Comment by CyrusZei** [comment]
Same with this link.

If you want I can go over and find all the dead links? and report them in as issues ?

CleanShot 2022-02-06 at 18 37 59@2x

**Pull request closed without merging**
