### PR TITLE
fix(analytics,android): fixed analytics reporting in android

### PR DESCRIPTION
**Pull request by WadhahEssam**
### Description

- Fixed analytics issue where events are not reported if the value of `analytics_auto_collection_enabled` is not set in firebase.json file.

### Related issues

#4784 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests; (not needed)
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change. (not needed)
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### Note
I am not really that familiar with contributing to open source libraries, hope that was helpful.

### CODE REVIEW

**Comment by mikehardy** [comment]
Thanks for posting this up! I need to check iOS now as well to see how it is handling this, might have the equivalent problem, I'm scanning my comms queue from overnight to see if anything more important is waiting but otherwise this is the highest priority actual task, should be shortly

**Comment by WadhahEssam** [comment]
I have published an app in both platform, and noticed that android events are not reported, but iOS worked just fine, ( I had to republish the app) and now I have many users who are in a version without any analytics enabled, so thanks for taking this seriously

**Comment by mikehardy** [comment]
Yeah I am in the same boat - I have an android release build live on the store now in a work project that has no analytics at the moment.

This is triggered when you have a firebase.json, but that firebase.json does not have the key present. In that case the groovy method from firebase-json.gradle will always return false, which is incorrect.

I went a different direction with a fix though - rather than add another method I copied the stringValue method style from just below your proposed method, and enforced that callers send a default value to return if it doesn't exist and I modified the 3 callers in the various packages. This is a bit more compact in usage because some things default to true (analytics collection) and some to false (admob delay init). Now it is explicit in the code what the default is because you send it in, and you don't need a separate "does it exist?" check in calling code

ios works differently because it is additive, not replacing - if there is no value, nothing is added so the SDK default "wins". The Android style is replacing a placeholder in an AndroidManifest.xml so if there was no value the implementation silently "failed" to a false and put that in the placeholder spot.

I probably wouldn't have noticed this problem for a while regardless, all the internet points are yours!

**Comment by WadhahEssam** [comment]
makes total sense, I just didn't want to mess with a code outside of this issue scope, Thanks @mikehardy

**Comment by mikehardy** [comment]
Yeah - that thought is normally correct, you mention you are relatively new to open source, your idea there - keep the change very small - is actually the exact right place to start

Normally I would have made comments and asked for / given explicit approval for widening the change a bit and worked with you for the change but this is a big deal so I wanted to try to move faster so I could make sure to get a release out today

**Pull request closed without merging**
