### PR TITLE
Add support for Sign-in with Apple

### PR DESCRIPTION
**Pull request by mikehardy**
### Summary

Apple just got all prickly with regard to social auth and requiring you implement their Sign in with Apple if you have social auth c.f. https://github.com/invertase/react-native-firebase/issues/2884

This is a straight port of the v6 change from https://github.com/invertase/react-native-firebase/pull/2979, tested and working in my work project

My project does not use flow but those are generated automatically. My project does use Typescript and those types are working.

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [x] Flow types updated
- [x] Typescript types updated

### Test Plan

I added this as a dependency in my work project, here is the package.json snippet:

```json
    "react-native-firebase": "git+https://github.com/mikehardy/react-native-firebase.git#v5.x.x",
```

I cleaned node_modules + yarn.lock, made sure my patch-package file no longer had my local testing integration, reinstalled and built everything, then exercised my work project which uses Apple Sign-in.

### Release Plan

[IOS][FEATURE] [Auth] - Add Sign in with Apple support

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
@Salakar  Unfortunately I can't make the build work on CI without doing (or finishing) the port of the tests project to react-native 60, because this requires Xcode 11 :-(

If you look at the diff of just the first commit you'll see the same clean diff from your v6 one and I can only promise that I've tested it locally

FWIW, I think we should really just hold our breath and do a v5.5.7. I'm using the most current commit in my work project and it all checks out.

If you agree I'll do version commits for you (for google version tracking) following the release-process but you'll have to push all the "danger!" red buttons that let's it release anyway.

**Comment by Salakar** [comment]
Lets just release it, go go :)

**Comment by mikehardy** [comment]
I swear I'll mop up if it turns to :hankey: :wink: - but I also think it will be fine. Exciting!

**Comment by mikehardy** [comment]
This should be 5.6.0 actually, it will now require react-native 0.60 because of Xcode 11. You might break the release into chunks and do a 5.5.7 of everything before my change, then 5.6.0 with my change? Just to give 0.59 people the most before we drop them

**Comment by Salakar** [comment]
What you suggest makes sense, up to you how you want to version it, 

You also have publish access 😬 I won't be able to pick anything up publishing wise myself until mid week otherwise, but can sort if not done by then, so no pressure.

**Comment by mikehardy** [comment]
The problem is the approvals required to publish despite CI being non-functional - although I suppose if the branch itself were un-protected I could push to it and do the npm? If that's what you meant, I can definitely do that (slowly...methodically...) and get a 557 and 560 out

**Comment by Salakar** [comment]
> If that's what you meant, I can definitely do that (slowly...methodically...) and get a 557 and 560 out

Yis, this. Ping me on Discord if you need me to press buttons on GitHub, will spot it quicker

**Comment by mikehardy** [comment]
That close is a github technicality as I groom my fork's v5.x.x tree and slowly step through commits to test them and push and release etc. Pay no mind...

**Comment by mikehardy** [comment]
released as v5.6.0

**Pull request closed without merging**
