### PR TITLE
feat(firestore): add support for subcollection types

### PR DESCRIPTION
**Pull request by paulmand3l**
### Description

Adding a way to specify a type for getting a subcollection from a documentRef. This mirrors the firestore().collection typescript annotation.

### Release Summary

Adding support for type annotation when getting document subcollections

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [X] `Android`
  - [X] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [X] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X] No

### Test Plan

Before: 
image

After:
image

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

:fire:

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
Hmmm 🤔 this does not appear to be supported by the upstream types:

https://github.com/firebase/firebase-js-sdk/blob/b5a1a6054f464859f3536453c5bc457632ca5851/packages/firestore-types/index.d.ts#L252

...yet neither is our typing for the `firestore().collection` declaration. I can't think of a reason why this proposed typing would be invalid - seems like it would be valid in any + all cases, yet it is a bit bothersome to deviate from the firebase-js-sdk typings.

Could you open an issue with them upstream to propose this same change upstream and link it here?

**Comment by paulmand3l** [comment]
Opened an issue and PR upstream:

https://github.com/firebase/firebase-js-sdk/issues/7043
https://github.com/firebase/firebase-js-sdk/pull/7044

**Comment by paulmand3l** [comment]
Do you think the "stops listening when unsubscribed" test failure is related to this code change, or is that test instability?

**Comment by mikehardy** [comment]
I'm certain your change would not fail the CI, we do have some tests that flake from time to time. I can re-trigger that no problem.

Great work on the issue + PR over there (getting both the collection() methods, perfect) - we'll see what they say. I recorded my support there but also acknowledged I have no real sway in their repo. Hopefully they like it

**Comment by paulmand3l** [comment]
@mikehardy whats the best way to handle this? Still no word from upstream.

**Comment by mikehardy** [comment]
I pinged the related issue, perhaps that nudge will help

**Comment by mikehardy** [comment]
This appears to be the most-upstream issue to subscribe to - https://github.com/googleapis/nodejs-firestore/issues/1792

This can be reopened / handled whenever upstream alters their typing

**Pull request closed without merging**
