### PR TITLE
fix(app, android): bump google play-services-auth to 21.0.0

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

May fix crash seen but not reproduced upstream

### Related issues

- https://github.com/firebase/firebase-android-sdk/issues/5768#issuecomment-2020388078

### Release Summary

conventional commit

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

Local run of e2e test + CI

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
@efstathiosntonas - here's a PR for the play services auth bump you're looking for, you'll be able to use the patch set immediately of course, but also I'm preparing to do a release as I have another small fix lined up I want to launch as well

**Comment by efstathiosntonas** [comment]
Perfect, thanks Mike!!

**Comment by mikehardy** [comment]
still experiencing a non-blocking failure on lower android APIs (which I'm just experimenting with in CI, and they still aren't working) but API34 looks good so far in CI and it passes locally, will have this released probably in the next 10 mins or so

**Comment by mikehardy** [comment]
made it through auth related tests, that's sufficient in this case

**Comment by efstathiosntonas** [comment]
Thank you for the fast response on this one Mike. I think there's an issue on google tracker with the same stacktrace and they also suggest upgrading to 21, will find it tomorrow and post the link here just for reference.

**Comment by efstathiosntonas** [comment]
found it but it seems it's not fixed with 21.0.0 according to comment no.20 🤔

https://issuetracker.google.com/issues/295792458#comment20

**Comment by efstathiosntonas** [comment]
@mikehardy just a heads up, the upstream issue link on the CHANGELOG leads to 404

**Pull request merged**
