### PR TITLE
feat(android): don't call ad of AdmobBanner multiple times

### PR DESCRIPTION
**Pull request by JeffGuKang**
### Summary

Fix to call Ad multiple times in android related to #3299
Google Admob treats this is cheating in my case. 

### Checklist

- [x] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/\*\*/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[ANDROID] [BUGFIX] [ADMOB] - Did a thing to fix a thing with a Firestore thing

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by sendyputra** [comment]
@Ehesp please merge thisbecause is important to avoid banned from admob account

**Comment by JeffGuKang** [comment]
> @Ehesp please merge this because is important to avoid banned from admob account

I almost got banned cause this issue. 
You can fix this temporarily to use the [patch-package](https://github.com/ds300/patch-package).

**Comment by Salakar** [comment]
My only issue with this was that if you update your unit/request options props on your ad component it will now no longer request a new ad with the new unit/options?

Only changing the size prop will work now?

Don't want to block this PR though as this may not be an issue in a real world app, so change approved.

**Comment by JeffGuKang** [comment]
@Salakar I didn't care about changing unitID/request options from init props. I am testing another way.

**Comment by mikehardy** [comment]
Perhaps request of a new ad should always be explicit, and then just documented as such, if "ad requests via side effect" is a path to banning

**Comment by JeffGuKang** [comment]
I agree it is good to control `Banner` by explicitly using `loadAd` to avoid unintended ban.

**Comment by sughandj** [comment]
@JeffGuKang I was wondering if this is getting merged soon, I'm having the same issue as well.

**Comment by Salakar** [comment]
I'll ship this as a minor version rather than a patch just to be safe, release coming shortly.

**Comment by Salakar** [comment]
Shipped, v7.2.0 admob should appear shortly once CI runs.

**Comment by michuotvn** [comment]
it's still not work, android app still request ads so much. the show rate only ~20%
Screen Shot 2020-07-13 at 07 49 42
[https://github.com/invertase/react-native-firebase/issues/3929](url)

**Comment by JeffGuKang** [comment]
> it's still not work, android app still request ads so much. the show rate only ~20%
> Screen Shot 2020-07-13 at 07 49 42
> [https://github.com/invertase/react-native-firebase/issues/3929](url)

This PR solved multiple request ads on Android when mount Admob banner. Not related entire request. 
If you put the banner to Page, the ad will be loaded whenever the Page is mounted. 

And my case is exactly same. 
image

**Pull request merged**
