### PR TITLE
Modify Firestore.Statics interface to include static methods on TypeScript

### PR DESCRIPTION
**Pull request by originerd**
### Summary

Fix types for Statics.

To include static methods, it should be defined with `typeof` keyword. Otherwise, these can't be used.

- before fixing it
image
- after fixing it
image

### Checklist

- [ ] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [ ] Flow types updated
- [x] Typescript types updated

### Release Plan

[CATEGORY][type] [LOCATION] - Modify Firestore.Statics interface to include static methods on TypeScript

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Ehesp** [comment]
Hey @originerd this is a good catch! It also applies to all of the other modules too so I'll look at getting them changed/checked out.

**Comment by Ehesp** [comment]
Does this still work correctly when the type needs constructing? E.g:

```
const ts = new firebase.firestore.Timestamp(123, 123345);
```

**Comment by originerd** [comment]
@Ehesp I checked the other modules, too. And they are using `interface`s or `class`es without `static` methods. So, I didn't change them.

And `const ts = new firebase.firestore.Timestamp(123, 123345);` works.

image

**Comment by Ehesp** [comment]
Right cool that makes sense. Thanks for this, I'll get it merged up 👍

**Pull request merged**
