### PR TITLE
fix(remote-config): error calling getValue() before fetch

### PR DESCRIPTION
**Pull request by AlexeyVlasenko**
### Description

remoteConfig().getValue() errored when it invokes before fetch values success/failed, because this._values is undefined.
Added check for the correct type of "target" to hasOwnProperty method to prevent this issue.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [-] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [-] `jest` tests added or updated in `packages/\*\*/__tests__`
- [-] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [-] No

### CODE REVIEW

**Comment by AlexeyVlasenko** [comment]
> Interesting - this looks good to me but since this is a common function I'd like a second pair of 👀

As an option, we can check is ```this._values !== undefined``` inside `getValue()` method.

**Comment by Salakar** [comment]
> > Interesting - this looks good to me but since this is a common function I'd like a second pair of 👀
> 
> As an option, we can check is `this._values !== undefined` inside `getValue()` method.

I'd prefer we did this rather than change a function in core 😅 would you mind making this change instead?

**Comment by AlexeyVlasenko** [comment]
> > > Interesting - this looks good to me but since this is a common function I'd like a second pair of 👀
> > 
> > 
> > As an option, we can check is `this._values !== undefined` inside `getValue()` method.
> 
> I'd prefer we did this rather than change a function in core 😅 would you mind making this change instead?

Not a problem!

**Comment by Salakar** [comment]
Thank you :) LGTM, waiting for CI then I'll merge.

**Comment by Salakar** [comment]
LGTM GIF

**Pull request merged**
