### PR TITLE
Issue #572 - Fix for Storage.putFile() with content:// paths

### PR DESCRIPTION
**Pull request by peterdivvito**

### CODE REVIEW

**Comment by chrisbianca** [comment]
@peterdivvito Thanks for flagging this and the PR.  All looks good and makes sense, but just want to check that you confirmed it still works for file:// paths as well?  

Out of curiosity, have you had a chance to try the same on iOS yet?

**Comment by chrisbianca** [comment]
I've just given this a try with a file:// path using my own app, and it looks like by using `putStream` you lose access to the size of the file being uploaded and as such can no longer present a percentage uploaded indicator which isn't ideal.

**Comment by chrisbianca** [comment]
With putStream, it will never be possible to know the size of the stream, so this makes sense.

I think switching this so that it goes back to using `putFile` for files, and `putStream` for `content://` URLs is the way to go.  I'm just making and testing the changes and will push up a commit shortly.

**Comment by chrisbianca** [comment]
@peterdivvito See: https://github.com/invertase/react-native-firebase/commit/0391b2834d85c9681dad1171a0ff05c2e0a42fb4

If you're able to confirm that this works for your streams (it should do as I'm using your code) then I'll close this and the issue off.

Note, I've made the change on master rather than the 3.0.x branch.  We're currently prepping the 3.1.0 release which will go out in the next couple of days.

**Comment by peterdivvito** [comment]
Hi @chrisbianca ,

I was just thinking about what you said concerning the upload progress and thought I'd check out the api docs and saw this under putFile().

The source of the upload. This can be a file:// scheme or any content URI. A content resolver will be used to load the data. 

Have you tried just passing the URI straight to this?

**Comment by peterdivvito** [comment]
I just tried that out and it worked a treat.

**Comment by chrisbianca** [comment]
Just tested this and all works well, thanks!
I'll get this merged over to master.

**Pull request merged**
