### PR TITLE
 feat(auth): Add Expo support for phone auth #6167 

### PR DESCRIPTION
**Pull request by pduggi-cf**
Add @react-native-firebase/auth config plugin, which enables captcha for phone auth by modifying Info.Plist.
        The config plugin is automating the [reCAPTCHA verification steps](https://firebase.google.com/docs/auth/ios/phone-auth#set-up-recaptcha-verification) from the firebase iOS docs.
    Add docs to the Phone Auth page for Expo users.

Sorry for some reason the checklist didn't show up here when I created the PR. I'll try to find it.

Related: https://github.com/invertase/react-native-firebase/issues/5936

Updating PR #6167

### CODE REVIEW

**Comment by pduggi-cf** [comment]
@nandorojo thanks for the original PR

**Comment by mikehardy** [comment]
Hey @pduggi-cf this seems great! Thanks for picking it up and pushing it forward, I appreciate it.
I also appreciate your patience, I was traveling and I am just now getting caught back up so I can process PRs again.

It looks like this is just missing the CLA signed by you - can you do that by following either the Details link in the failing check on it or in the comment above? Thanks!

**Comment by pduggi-cf** [comment]
@mikehardy 
image

I have signed it a while ago not sure why it says my CLA signature is still pending

**Comment by mikehardy** [comment]
> x Prashanth kumar Duggishetti

In my experience that is usually because the CLA was somehow signed with a different user (keyed by email address) than was expected here. Perhaps you are missing an email alias in your github account or something similar?

**Comment by pduggi-cf** [comment]
image

image

I am not sure what to do now...

**Comment by DoctorJohn** [comment]
It looks like to two commits [Dev dependies to yarn](https://github.com/invertase/react-native-firebase/pull/6472/commits/8a1016c8ac2ca1b5fbdbb89551619305660e375c) and [yarn.lock](https://github.com/invertase/react-native-firebase/pull/6472/commits/92c24a6a22184e10cdba35c4b10beee9ad49bba2) are not associated with your email address. I would try to [set up your email address in git](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-in-git) and then recommit those two commits and force push.

**Comment by nandorojo** [comment]
Hey @pduggi-cf! Just wondering if you're planning on trying to fix the CLA here again. I'd love to get this merged and use it in a Solito example app. Thanks again for picking it up.

**Comment by pduggi-cf** [comment]
@nandorojo sorry, for some reason I thought this was already merged, I'll get to it later today. Thanks for bringing it back

**Comment by mikehardy** [comment]
There is a conflict now and the CLA is still not signed, but I did add hacktoberfeft-accepted tag in case someone wants that ;-)

**Comment by pduggi-cf** [comment]
Running around due to a medical emergency, might take a while

**Comment by mikehardy** [comment]
Superceded by #6645

**Pull request closed without merging**
