### PR TITLE
[iOS] get user input from notification action

### PR DESCRIPTION
**Pull request by blankg**
### Summary

In iOS when creating notification actions with input, the input is not passed to JS. This PR extracts the user input if available and passes it to JS notification_opened in the results property which now aligns the api with Android.

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

- [iOS] [ENHANCEMENT] [NOTIFICATIONS] - get user input from notification action

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Salakar** [comment]
Hey, thanks for this 🎉 

Small issue; types & Android show `NotificationOpen.results` as an Object, you're returning a string here so would be inconsistent with android;

See: 
https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotifications.java#L265
&
https://github.com/invertase/react-native-firebase/blob/master/src/modules/notifications/Notification.js#L16

However; I suspect though Android is incorrectly returning an Object, of the format `{ resultKey: "users input here" }` which is pretty pointless - it should be returning a string, we can change this though on Android;

https://github.com/invertase/react-native-firebase/blob/4be1ae70ded749f98fa09dae8ae5dbfab0061950/android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotifications.java#L265 can become;

```java
notificationOpenMap.putString("results", remoteInput.getString("resultKey"));
```

And then the types updated to reflect that. 

If you don't mind making the above change that'd be great 👌 otherwise I can look at it for v6.

**Comment by blankg** [comment]
Hi @Salakar , Don't mind making the change just thinking it would be a breaking change on the Android api.
Would it be better to return the same object in iOS for 5.x version, and later this can be changed to string in 6.x?

**Comment by Salakar** [comment]
Ye sorry, you're right - that'd be better, I can sort the correction change for v6

**Comment by Salakar** [comment]
Thanks for making the change, I'll go ahead and merge this and tag it to v6 for the resultKey removal change.

**Comment by Salakar** [comment]
Hey @blankg this is now live in v5.2.1. Thanks again.

---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:

  - 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
  - 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
  - 👉  Star this repo on GitHub ⭐️

**Comment by HeribertoAlves** [comment]
Hello @blankg I know this is not the appropriate place but I was wondering how do you create notification actions with input for IOS. Am I missing something? Because we cannot create this in react-native as Android. You create natively on XCode, right? Do you have an example of how to do it?

**Pull request merged**
