### PR TITLE
[android][database] Remove all db references and listeners onCatalystInstanceDestroy

### PR DESCRIPTION
**Pull request by Salakar**
Potential fix for #1498

cc @pistou , @barbarosh , @shashankvaibhav

### CODE REVIEW

**Comment by barbarosh** [comment]
@Salakar Looks like a good solution, but I think we should have this same solution and for iOS ?

**Comment by Salakar** [comment]
@barbarosh I'd like someone to test and confirm this works before I look into iOS - I'm not even sure if iOS has the same issue - can someone confirm?

**Comment by barbarosh** [comment]
@Salakar onHostDestroy isn't calling on a restart js part in dev mode.

**Comment by shashankvaibhav** [comment]
@Salakar You can use this method. It gets triggered when after hot reloading. I tried to use the code you wrote in onHostDestroy under this method but still no benefit.

@Override 
public void onCatalystInstanceDestroy() {
      
 }

**Comment by barbarosh** [comment]
@Salakar It can be useful as example https://github.com/gre/react-native-view-shot/blob/master/android/src/main/java/fr/greweb/reactnativeviewshot/RNViewShotModule.java#L53

**Comment by Salakar** [comment]
Am trying something else - will push to this branch for you guys to test, give me a few mins.

**Comment by barbarosh** [comment]
@Salakar I tried this code 

```

  @Override
  public void onCatalystInstanceDestroy() {
    super.onCatalystInstanceDestroy();
    Iterator refIterator = references.entrySet().iterator();
    while (refIterator.hasNext()) {
      Map.Entry pair = (Map.Entry) refIterator.next();
      RNFirebaseDatabaseReference nativeRef = (RNFirebaseDatabaseReference) pair.getValue();
      nativeRef.removeAllEventListeners();
      refIterator.remove(); // avoids a ConcurrentModificationException
    }
}
```
It worked, bot I worried, it code can clearify new subscriptions while starting new JS instance ?

**Comment by shashankvaibhav** [comment]
Guys in this method removeAllEventListeners() thers is a if statement with condition hasListeners.
It gives me false value after hot reload. This is the reason it is not going inside and removing listeners.

**Comment by Salakar** [comment]
Can you locally replace the two files I've just changes and let me know how you get on?

**Comment by shashankvaibhav** [comment]
@Salakar Sorry but didn't work. Same problem no data after hot reload.

**Comment by Salakar** [comment]
@shashankvaibhav can you comment out the highlighted lines below (the iterator section) and try:

image

**Comment by shashankvaibhav** [comment]
@Salakar Didn't work.

**Comment by Salakar** [comment]
Worked for @barbarosh though 🙈 

Can you push up a reproducible project that I can clone and work off please - and I can take a look

**Comment by armanatz** [comment]
@Salakar I tried this PR out and even commented out the lines you mentioned above. Still the same issue

**Comment by Salakar** [comment]
@armanatz ok thanks for confirming also - I'll try reproduce on my end - will take time to setup though, I've also not experienced this issue myself so am not 100% sure if this is even the cause.

**Comment by barbarosh** [comment]
@Salakar for me worked solution with  onCatalystInstanceDestroy callback, but i tried only for reload event from dev menu, I not check with hot reload

**Comment by armanatz** [comment]
@barbarosh Interesting because this PR doesn't work for me with dev menu reload

**Comment by Salakar** [comment]
@barbarosh @armanatz what RN versions are you each using?

**Comment by armanatz** [comment]
@Salakar I am on `react-native@0.57.0` and `react-native-firebase@5.0.0`.

**Comment by barbarosh** [comment]
@Salakar I am on react-native@0.55.4 and react-native-firebase@4.3.8.

**Comment by Salakar** [comment]
See new PR #1619

**Pull request closed without merging**
