### PR TITLE
docs(releases): remove instance id / add installations appdistribution

### PR DESCRIPTION
**Pull request by nidelson**
### Description

On the Releases page, the link to the `Instance ID` is broken, as the package no longer exists in `main`.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### CODE REVIEW

**Comment by nidelson** [comment]
Happy with my first contribution to this project!
\o/

**Review by mikehardy — CHANGES_REQUESTED** [review]
Hmm :thinking: - IID was basically taken over by Installations though, and I realize App Distribution isn't in here either - the most correct change is to switch IID for Installations and App Distribution then - sorry to ask, but do you think you could do that instead?

**Comment by nidelson** [comment]
Certainly! 1min

**Review by mikehardy — APPROVED** [review]
This is fantastic, thanks a bunch for the second round with the complete changes!

**Comment by nidelson** [comment]
@mikehardy i applied prettier to ensure code standard. o/

**Pull request merged**
