### PR TITLE
[Crashlytics][ENHANCEMENT] v5.x.x

### PR DESCRIPTION
**Pull request by bthurlow**
### Summary

Wanted to help improve crashlytics js reporting so I implemented a variation of react-native-fabric's custom exception.  I also added two missing methods that are in the crashlytics api but were not included in RNFirebaseCrashlytics.

Also, I addressed #1643 in the documentation to hopefully make it more clear how to use this module.

### Checklist

- [ ✔️ ] Supports `Android`
- [ ✔️ ] Supports `iOS`
- [ ✔️ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ✔️ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
https://github.com/invertase/react-native-firebase-docs/pull/168
- [ ? ] Flow types updated
Pretty sure I updated those as I searched the entire project for any files related to crashlytics.
- [ ✔️ ] Typescript types updated

### Test Plan

Implemented and ran e2e tests on android.  Need help on iOS.
Android e2e results:
image

Also ran android code through a debug version of a production app successfully.
Crashlytics Examples:
image
image

### Release Plan

[GENERAL][ENHANCEMENT][CRASHLYTICS]
- Added recordCustomError method which allows you to specify your own filename, linenumber, class, and fuction as well as any additional data you which to show in the stack trace.
- Added setUserName method to allow you to set the user name to be attached to any following errors.
- Added setUserEmail method to allow you to set the user email to be attached to any following errors.

🔥 
---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by bthurlow** [comment]
I signed the CLA so I'm not sure why it is not picking it up.

**Comment by sampsonjoliver** [comment]
Are there any plans to release an update to v5.x.x with these changes for Crashlytics, now that they've been approved in 6.x.x? Would be a big help to our org while we wait for the rest of 6.x (we are using FCM, which I understand will be migrated to 6.x last) :)

**Comment by Salakar** [comment]
Hey @bthurlow - firstly thanks for sending this, sorry that it's slight duplication of the work already done for v6.

@sampsonjoliver I'm ok with merging this, say for a v5.4.0 release, but the API changes again in v6 so wondering if this will cause confusion in v6;

If `recordCustomError` could be changed to accept an `Error` instance only then I think this provides a better migration path to v6; 

v6 changelog for crashlytics: https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#crashlytics

Would also appreciate a review of this from other people as well

Thanks

**Comment by mikehardy** [comment]
Hi there! I've just finished working to make the v5 branch "releasable", and I'm going to help maintaining it. As mentioned above this could be included in a v5 release but it seems there is just an API change needed to provide a good upgrade path to the change already in v6? @bthurlow what do you think? If you rebased to current v5.x.x and altered the signature it seems like it could go in quickly esp since you already have some testing support

**Comment by mikehardy** [comment]
I've just rebased via github to get CI going, still needs an API change though per comments above

**Comment by mikehardy** [comment]
Special note: we have a problem with crashlytics + iOS + CI right now, so the tests you needed need to skip iOS and only go for android, which is sad yes. It looks like this:

```javascript
  describe('recordError()', () => {
    it('should record an error with a code and message', async () => {
      // failing from XCode 10.1 -> 10.2
      if (device.getPlatform() !== 'ios') {
        await firebase.crashlytics().recordError(1234, 'Test error');
      }
    });
```

**Comment by mikehardy** [comment]
@Salakar I looked into these and shaped them up for current status of v5.x.x. I compared the code here vs v6 and your comment about the API changing. I think since the whole crashlytics API changes, and this API for v5 perfectly matches the existing v5 API it's okay. From a user perspective this doesn't change my migration workload really. So I'd be okay with merging it for the v5.4 release I'm packaging up

**Comment by mikehardy** [comment]
Thank you @bthurlow ! We should have a 5.4.3 out soon and this will be in it. I will personally use the setUserEmail / setUserName ones, so I appreciate this

**Comment by bthurlow** [comment]
A special thank you to you @mikehardy for getting it release ready!

**Comment by sampsonjoliver** [comment]
Awesome work everyone, this is fantastic :)

**Comment by mikehardy** [comment]
I wish I had complete success to report, but unfortunately as I was doing pre-release testing on android (which is not normally covered in CI because it's flaky there) this turned up a problem and I need to revert it. Specifically, this exception:

```
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: Exception in native call
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: java.lang.ClassCastException: com.facebook.react.bridge.ReadableNativeMap cannot be cast to java.lang.String
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeArray.getString(ReadableNativeArray.java:135)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:73)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper$5.extractArgument(JavaMethodWrapper.java:69)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:359)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:193)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
06-11 22:27:35.220  7715  7933 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)

```

I attempted to troubleshoot it myself, and it seems that sometimes the fileName object is a string, sometimes it is a ReadableNativeMap - I'm not sure what's going on there but it's past me at the moment and I don't want to hold up the release.

If this can be shaped up - possibly following the v6 pattern, or any pattern available in react-native itself (I know they do some stack traversal in there), I'd be happy to try again.

**Comment by bthurlow** [comment]
@mikehardy I'm not able to get the fileName to be a map object to dig into it, but the following should work to catch it.

```code
public void recordCustomError(String name, String reason, ReadableArray frameArray) {

      ArrayList<StackTraceElement> stackList = new ArrayList<>(0);
      for (int i = 0; i < frameArray.size(); i++) {
        ReadableMap map = frameArray.getMap(i);
        ReadableMap additional = map.hasKey("additional") ? map.getMap("additional") : null;
        String functionName = map.hasKey("functionName") ? map.getString("functionName") : "Unknown Function";
        String className = map.hasKey("className") ? map.getString("className") : "Unknown Class";

        String fileName = "Unknown File";
        
        if(map.hasKey("fileName")) {
          ReadableType type = map.getType("fileName");
          
          switch (type){
            case Null:
              break;
            case Map:
              //TODO Structure of fileName map object
              break;
            case String:
              fileName = map.getString("fileName");
              break;
          }
        }
        
        StackTraceElement stack = new StackTraceElement(
          className,
          functionName,
          fileName,
          map.hasKey("lineNumber") ? map.getInt("lineNumber") : -1
        );
        stackList.add(stack);

        if(additional != null){
          StackTraceElement s = new StackTraceElement(
            "Additional Parameters",
            additional.toString(),
            fileName,
            map.hasKey("lineNumber") ? map.getInt("lineNumber") : -1
          );
          stackList.add(s);
        }
      }
      StackTraceElement[] stackTrace =  new StackTraceElement[stackList.size()];
      Exception e = new Exception(name + "\n" + reason);
      stackTrace = stackList.toArray(stackTrace);
      e.setStackTrace(stackTrace);
      Crashlytics.logException(e);
  }
```

**Comment by mikehardy** [comment]
Yeah, I have to say it was surprising! I found if I did a `describe.only` in the database tests in the e2e suite, it didn't show up! But if I did the full suite it showed up every time.

My reproduction is to follow the [README.md](https://github.com/invertase/react-native-firebase/blob/master/tests/README.md#android-1) in tests and run the android one. I have good luck running it once it starts but be aware that it's a bit finicky on the startup. I have to kill and restart the `yarn run test-android` (which is the actual line I linked above) a few times sometimes before it starts for real. Once it starts it always runs through to completion on 5.4.3 now, and will fail with this PR merged in

Can you try that to see if you can reproduce? It's vital to have this one tested as otherwise it will likely crash any app that would use it and I don't want to see the github issues opening up on that one :-)

**Comment by bthurlow** [comment]
What rn and android versions are you running? Want to be on the same so I have the best chance of reproducing.

**Comment by mikehardy** [comment]
the yarn install in the tests dir will fix the rn versions, I was testing on API28 emulator (named TestingAVD per the test docs).

**Comment by bthurlow** [comment]
I was able to repro, but this error is not making any sense because according to the objects I'm receiving, I'm getting a string, not a readablemap.  I'm digging into it deeper to see if I can figure out what is going on with it, will keep you posted.

**Comment by mikehardy** [comment]
Very happy you can repro, and I share your "huh?" take on it :-), I gave it a really solid try for a fix when I saw it and only reverted when I suffered total defeat. I will be very interested to see the root cause + fix if you can get there. good luck!

**Comment by bthurlow** [comment]
Ok, the error is being generated when we call the 'should error on invalid args' and the 'should error on missing required customError property' tests.  I've tried wrapping them in a try catch but have not gotten it to work so far.  Still working on it.

**Comment by bthurlow** [comment]
So I'm totally stumped on a fix.  RN is throwing the error before it hits the native code and I cannot find a place on the JS or native side to catch it to be able to test for it.  Everything has been wrapped in try-catch on both native and js sides and none of the catches get fired.  This is only breaking when we are purposely passing bad values across.

To make debugging a little more simple, I went down to the setUserName calls because we'd get a similar error about double to string but still to no avail to try to figure out where to catch this thing.

It's acting as once the  getNativeModule(this).setUserName(userName); is called it stops and never calls the native code.  I even wrapped all that up too with no better results.

Any ideas?

**Comment by mikehardy** [comment]
I wish I had some ideas, but I was equally stumped. I spent a few hours on it myself already and I even commented out the entire contents of the methods and just putting in log calls. I started to question my sanity and all of my build tools (which - who knows - maybe I wasn't even altering the executing code owing to a misunderstanding of the tools / build chain?) and had to stop. I don't have time to pursue it more right now but on the surface it looks tantalizingly close to working

**Comment by bthurlow** [comment]
I have progress.  Will try to push something tomorrow after I can work through each test.

**Comment by bthurlow** [comment]
See #2237

**Pull request merged**
