### PR TITLE
docs(firestore): update emulator usage example with new 

### PR DESCRIPTION
**Pull request by mkarkachov**
### Description
I got warn 'host in settings to connect with firestore emulator is deprecated. Use useEmulator instead.' So I propose to update with part.

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Oh yes! Thank you - made the changes but forgot the docs in #5613 :facepalm: 
I appreciate the help cleaning up the docs

**Comment by mikehardy** [comment]
Even for docs changes we need the CLA signed though :pray: - details link on that check or the comment can help click through it

**Comment by mkarkachov** [comment]
@mikehardy signed, I can't figure out what is wrong with PR Title :)

**Comment by mkarkachov** [comment]
btw, link to Contributor Guide in PR template description is wrong

**Comment by mikehardy** [comment]
Yeah, when it's only one commit github overrides the pr title and uses the commit message so the check keeps failing on purpose to remind me to edit it at the moment of merge. Semantic commits are difficult to get right! Thanks again

**Comment by mkarkachov** [comment]
> Yeah, when it's only one commit github overrides the pr title and uses the commit message so the check keeps failing on purpose to remind me to edit it at the moment of merge. Semantic commits are difficult to get right! Thanks again

I like that I could help, I reverted commit with wrong PR title on my side, added correct and requested review again

**Pull request merged**
