### PR TITLE
[v5] Check paths in Query.isEqual

### PR DESCRIPTION
**Pull request by iwikal**
### Summary

`Query.isEqual` should return false when you compare two queries on different collections.

### Checklist

- [x] Supports `Android`
- [x] Supports `iOS`
- [x] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [ ] Typescript types updated

### Test Plan

The plan is to wait and see if CI accepts the PR.

### Release Plan

[JS][BUGFIX] [firestore] - Query.isEqual now takes the collection path into consideration

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by iwikal** [comment]
I assume you want the same functionality as in the web sdk, where path does matter.

**Comment by iwikal** [comment]
I can't really make sense of the build errors; something about a timeout in beforeAll? I couldn't build an android apk to test locally on my linux machine either.

**Comment by mikehardy** [comment]
The ci.android.test build right now is non-functional for unrelated reasons - whether your change is correct or not

ci.ios.test should be passing though, there's a separate PR (#2726) that is also experiencing failures on CI there while it works local, and we're not sure why. We are investigating

**Comment by mikehardy** [comment]
@Salakar @Ehesp I think this is also an issue on v6 but the line has moved it is here now https://github.com/invertase/react-native-firebase/blob/master/packages/firestore/lib/FirestoreQuery.js#L176 (although it's missing, so it's not there - there is no path check)

The underlying assumption that we should mirror web and check for path also seems valid, so I think this should be merged? And v6 should get the same treatment?

**Comment by iwikal** [comment]
It seems that the web sdk implements CollectionReference as a subclass of Query. It follows that if the Query.isEqual method compares paths, CollectionReference.isEqual can be straight up inherited from that. Maybe it's something we don't want to do for performance reasons, but it would be correct.

**Comment by russellwheatley** [comment]
This was merged into v6: https://github.com/invertase/react-native-firebase/pull/3738, but will not be getting merged into v5 as it is no longer supported. Thank you for bringing this to our attention @iwikal, much appreciated.

**Pull request closed without merging**
