### PR TITLE
fix type of RemoteMessage data property

### LINKED ISSUE #3129: RemoteMessage.data has incorrect type in version 5.x.x
## Issue

`data` property type of `RemoteMessage` is `Object`.

https://github.com/invertase/react-native-firebase/blob/e7e6d6f4cb3ea2d257896be0a314fce4ff3a7ff3/src/index.d.ts#L1275

Thus, when trying to get some custom property value from `RemoteMessage.data`

```js
console.log(message.data.my_custom_property);
```

it gives an error like

`Property 'my_custom_property' does not exist on type 'Object'. ts(2339)`

I think the correct type for `RemoteMessage.data` is `[key: string]: any`.

## Environment
`react-native-firebase` version: `5.5.6`.

### PR DESCRIPTION
**Pull request by ziyaddin**
Fixes #3129 

### Summary
See description of #3129.

### Checklist

- [ ] Supports `Android`
- [ ] Supports `iOS`
- [ ] `e2e` tests added or updated in packages/**/e2e
- [ ] Flow types updated
- [x] Typescript types updated

### Release Plan

 [TYPES] [ENHANCEMENT] [MESSAGING] - Change `RemoteMessage.data` property type from `Object` to `{ [key: string]: string }`.

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
@ziyaddin thanks! - this seems fine to me based on inspection and previous discussion - do you have it running locally and it works for you? I use typescript myself and remote messages so I'll end up checking it too, but the more verification in the old/stable branch the better

**Comment by ziyaddin** [comment]
@mikehardy yes, it works for me so far. I have also done `patch-package` procedure as you said in our previous discussion.

**Comment by mikehardy** [comment]
Cool - thanks guys. The v5.x.x branch is still CI challenged (and it's not really worth it to fix) but I am able to run all the tests locally and manage a release.

I'd like to have a few more things batched (if possible) prior to a release so I'll merge this but not release it just now. 

Since you've got patch-package going that shouldn't have a real impact for you, you'll get a nice patch-package warning in the future when it does come out and the patch doesn't apply, so no monitoring needed really

Cheers

**Comment by ziyaddin** [comment]
@mikehardy thanks! While editing, I came across with more cases of `data: Object` inside `index.d.ts`. Should we fix them?

**Comment by mikehardy** [comment]
I dunno - I'm open to PRs like that I'm just not sure if they are worth the effort with v5.x.x in maintenance mode. That's totally up to you. I'd mostly just check vs the v6 branch and if they are already fixed there maybe let them rest as the future has fixes and the current is maybe not worth the effort

**Pull request merged**
