### PR TITLE
feat(admob): implement support for Server Side Verification

### LINKED ISSUE #3722: Set custom data by admob rewarded adv (SSV)
Hey guys,
currently need to validate rewarded admob adv on server side (https://developers.google.com/admob/android/rewarded-video-ssv).  Do you plan to add possibility to set custom data on adv request? (request id, user id etc.)

### PR DESCRIPTION
**Pull request by iAmGhost**
### Description

This PR implements [Server Side Verification](https://developers.google.com/admob/android/rewarded-video-ssv) for AdMob package.

You can request RewardedAd with custom payload, AdMob server will call specified URL with payload instead of your app.

You have to implement verifications and set "Server-side verification" on your AdMob ad unit.

### Related issues

Fixes #3722, #2060

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__` - I didn't write jest test cases since test case for RewardedAd itself were missing.
  - [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

* Verified with real AdMob unit id with SSV callback on iOS/Android
* Implemented e2e test cases for serverSideVerificationOptions and ran both on iOS/Android

#### SSV Test Logs

App Code: 

```
const rewardedAd = RewardedAd.createForAdRequest(adUnitId, {
  serverSideVerificationOptions: {
    userId: '9999',
    customData: 'my-custom-data',
  },
});
```

Backend Log:

```
[14/Aug/2020 12:51:43] "GET /views/admob-ssv/?ad_network=...&ad_unit=...&custom_data=my-custom-data&reward_amount=1&reward_item=test_reward_item&timestamp=1597377102267&transaction_id=148cc85...&user_id=9999&signature=MEUCIQCQSi3cQ2PlxlEAkpN...&key_id=3335... HTTP/1.1" 200 0
```

#### iOS e2e test logs

```
% yarn tests:ios:test
yarn run v1.22.4
$ cd tests && ./node_modules/.bin/detox test --configuration ios.sim.debug --loglevel warn


Attempted to invoke `1` (method ID) on `KeyboardObserver` (NativeModule name) without a method queue.
Attempted to invoke `1` (method ID) on `KeyboardObserver` (NativeModule name) without a method queue.
Attempted to invoke `1` (method ID) on `KeyboardObserver` (NativeModule name) without a method queue.
Attempted to invoke `1` (method ID) on `KeyboardObserver` (NativeModule name) without a method queue.
Running application testing ({
    initialProps =     {
        isHeadless = 0;
    };
    rootTag = 11;
})
  admob()
    namespace
      ✓ accessible from firebase.app()
    setRequestConfiguration()
      ✓ throws if config is not an object
      maxAdContentRating
        ✓ throws if maxAdContentRating is invalid
        ✓ accepts a age rating
      tagForChildDirectedTreatment
        ✓ throws if tagForChildDirectedTreatment not a boolean
        ✓ sets the value
      tagForUnderAgeOfConsent
        ✓ throws if tagForUnderAgeOfConsent not a boolean
        ✓ sets the value

  admob() AdsConsent
    requestInfoUpdate
      ✓ requests info update
    showForm
      ✓ throws if options is not valid
      ✓ throws if privacy policy is not valid
      ✓ throws if withPersonalizedAds is not a boolean
      ✓ throws if withNonPersonalizedAds is not a boolean
      ✓ throws if withAdFree is not a boolean
      ✓ throws if all options are false
    getAdProviders
      ✓ returns a list of ad providers
    setDebugGeography
      ✓ throws if geography is invalid
      ✓ sets the geography
    getStatus / setStatus
      ✓ throws if status is invalid
      ✓ sets and gets unknown
      ✓ sets and gets non-personalized
      ✓ sets and gets personalized
    setTagForUnderAgeOfConsent
      ✓ throws if value is not a boolean
      ✓ sets a value
    addTestDevices
      ✓ throws if value is not an array
      ✓ throws if deviceIds contains invalid value
      ✓ sets device IDs

  admob() InterstitialAd
    createForAdRequest
      ✓ loads with requestOptions (2342ms)
    onAdEvent
      ✓ unsubscribe should prevent events (2003ms)
      ✓ loads with a valid ad unit id
      ✓ errors with an invalid ad unit id

  admob() requestOptions
    ✓ returns an empty object is not defined
    ✓ throws if options is not an object
    requestNonPersonalizedAdsOnly
      ✓ throws if requestNonPersonalizedAdsOnly is not a boolean
      ✓ accepts requestNonPersonalizedAdsOnly boolean
    networkExtras
      ✓ throws if networkExtras is not an object
      ✓ throws if networkExtras value is not a string
      ✓ accepts networkExtras object
    keywords
      ✓ throws if keywords is not an array
      ✓ throws if a keyword is not a string
      ✓ accepts keywords array
    testDevices
      ✓ throws if testDevices is not an array
      ✓ throws if a testDevices is not a string
      ✓ accepts testDevices array
    contentUrl
      ✓ throws if contentUrl is not a string
      ✓ throws if contentUrl is not a valid url
      ✓ throws if contentUrl is too long
      ✓ accepts a contentUrl
    location
      ✓ throws if not an array
      ✓ throws if latitude not a number
      ✓ throws if latitude is invalid
      ✓ throws if longitude not a number
      ✓ throws if longitude is invalid
      ✓ accepts a latitude and longitude
    locationAccuracy
      ✓ throws if not a number
      ✓ throws if less than 0
      ✓ accepts locationAccuracy
      ✓ uses a defaultValue
    requestAgent
      ✓ throws if not a string
      ✓ accepts a requestAgent
    serverSideVerificationOptions
      ✓ throws if userId is not a string
      ✓ throws if customData is not a string
      ✓ accepts a serverSideVerificationOptions

  admob() RewardedAd
    createForAdRequest
      ✓ throws if adUnitId is invalid
      ✓ throws if requestOptions are invalid
      ✓ returns a new instance
      ✓ loads with requestOptions (1388ms)
    show
      ✓ throws if showing before loaded
    onAdEvent
      ✓ throws if handler is not a function
      ✓ returns an unsubscriber function
      ✓ unsubscribe should prevent events (2000ms)
      ✓ loads with a valid ad unit id (1946ms)
      ✓ errors with an invalid ad unit id

  admob() showOptions
    ✓ returns an empty object is not defined
    ✓ throws if options is not an object
    ✓ throws if immersiveModeEnabled is not a boolean
    ✓ sets immersiveMode


  77 passing (19s)

✨  Done in 19.81s.
```

#### Android e2e test logs

```
% ANDROID_AVD_NAME=Pixel_2_API_29 yarn tests:android:test
yarn run v1.22.4
$ cd tests && ./node_modules/.bin/detox test --configuration android.emu.debug
detox[30136] INFO:  [test.js] node_modules/.bin/mocha --opts e2e/mocha.opts --configuration android.emu.debug --invert --grep :ios: --use-custom-logger "true" e2e


detox[30137] INFO:  [DetoxServer.js] server listening on localhost:63731...
detox[30137] INFO:  at node_modules/jet/lib/node/vm.js:78:11 
 [✈️] debugger has connected! Downloading app JS bundle...
  admob()
    namespace
      ✓ accessible from firebase.app()
detox[30137] INFO:  at node_modules/jet/lib/node/console.js:16:15 
 Running "testing" with {"rootTag":21}
    setRequestConfiguration()
      ✓ throws if config is not an object
      maxAdContentRating
        ✓ throws if maxAdContentRating is invalid
        ✓ accepts a age rating
      tagForChildDirectedTreatment
        ✓ throws if tagForChildDirectedTreatment not a boolean
        ✓ sets the value
      tagForUnderAgeOfConsent
        ✓ throws if tagForUnderAgeOfConsent not a boolean
        ✓ sets the value

  admob() AdsConsent
    requestInfoUpdate
      ✓ requests info update
    showForm
      ✓ throws if options is not valid
      ✓ throws if privacy policy is not valid
      ✓ throws if withPersonalizedAds is not a boolean
      ✓ throws if withNonPersonalizedAds is not a boolean
      ✓ throws if withAdFree is not a boolean
      ✓ throws if all options are false
    getAdProviders
      ✓ returns a list of ad providers
    setDebugGeography
      ✓ throws if geography is invalid
      ✓ sets the geography (1163ms)
    getStatus / setStatus
      ✓ throws if status is invalid
      ✓ sets and gets unknown
      ✓ sets and gets non-personalized
      ✓ sets and gets personalized
    setTagForUnderAgeOfConsent
      ✓ throws if value is not a boolean
      ✓ sets a value
    addTestDevices
      ✓ throws if value is not an array
      ✓ throws if deviceIds contains invalid value
      ✓ sets device IDs

  admob() InterstitialAd
    createForAdRequest
      ✓ loads with requestOptions (2877ms)
    onAdEvent
      ✓ unsubscribe should prevent events (2001ms)
      ✓ loads with a valid ad unit id
      ✓ errors with an invalid ad unit id

  admob() requestOptions
    ✓ returns an empty object is not defined
    ✓ throws if options is not an object
    requestNonPersonalizedAdsOnly
      ✓ throws if requestNonPersonalizedAdsOnly is not a boolean
      ✓ accepts requestNonPersonalizedAdsOnly boolean
    networkExtras
      ✓ throws if networkExtras is not an object
      ✓ throws if networkExtras value is not a string
      ✓ accepts networkExtras object
    keywords
      ✓ throws if keywords is not an array
      ✓ throws if a keyword is not a string
      ✓ accepts keywords array
    testDevices
      ✓ throws if testDevices is not an array
      ✓ throws if a testDevices is not a string
      ✓ accepts testDevices array
    contentUrl
      ✓ throws if contentUrl is not a string
      ✓ throws if contentUrl is not a valid url
      ✓ throws if contentUrl is too long
      ✓ accepts a contentUrl
    location
      ✓ throws if not an array
      ✓ throws if latitude not a number
      ✓ throws if latitude is invalid
      ✓ throws if longitude not a number
      ✓ throws if longitude is invalid
      ✓ accepts a latitude and longitude
    locationAccuracy
      ✓ throws if not a number
      ✓ throws if less than 0
      ✓ accepts locationAccuracy
      ✓ uses a defaultValue
    requestAgent
      ✓ throws if not a string
      ✓ accepts a requestAgent
    serverSideVerificationOptions
      ✓ throws if userId is not a string
      ✓ throws if customData is not a string
      ✓ accepts a serverSideVerificationOptions

  admob() RewardedAd
    createForAdRequest
      ✓ throws if adUnitId is invalid
      ✓ throws if requestOptions are invalid
      ✓ returns a new instance
      ✓ loads with requestOptions (2291ms)
    show
      ✓ throws if showing before loaded
    onAdEvent
      ✓ throws if handler is not a function
      ✓ returns an unsubscriber function
      ✓ unsubscribe should prevent events (2005ms)
      ✓ loads with a valid ad unit id (1969ms)
      ✓ errors with an invalid ad unit id

  admob() showOptions
    ✓ returns an empty object is not defined
    ✓ throws if options is not an object
    ✓ throws if immersiveModeEnabled is not a boolean
    ✓ sets immersiveMode

detox[30137] INFO:  at e2e/init.js:53:11 
  ✨ Tests Complete ✨ 

  77 passing (52s)

✨  Done in 52.76s.
```

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
I'll start looking through this as soon as I can, but note there is an Android compile fail at the moment:

```

/Users/runner/work/react-native-firebase/react-native-firebase/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobRewardedModule.java:87: error: package ServerSideVerificationOptions does not exist
> Task :react-native-firebase_admob:compileDebugJavaWithJavac
          ServerSideVerificationOptions.Builder options = new ServerSideVerificationOptions.Builder();
                                       ^
/Users/runner/work/react-native-firebase/react-native-firebase/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobRewardedModule.java:87: error: package ServerSideVerificationOptions does not exist
          ServerSideVerificationOptions.Builder options = new ServerSideVerificationOptions.Builder();
                                                                                           ^
Note: /Users/runner/work/react-native-firebase/react-native-firebase/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobCommon.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

**Comment by iAmGhost** [comment]
> I'll start looking through this as soon as I can, but note there is an Android compile fail at the moment:
> 
> ```
> 
> /Users/runner/work/react-native-firebase/react-native-firebase/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobRewardedModule.java:87: error: package ServerSideVerificationOptions does not exist
> > Task :react-native-firebase_admob:compileDebugJavaWithJavac
>           ServerSideVerificationOptions.Builder options = new ServerSideVerificationOptions.Builder();
>                                        ^
> /Users/runner/work/react-native-firebase/react-native-firebase/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobRewardedModule.java:87: error: package ServerSideVerificationOptions does not exist
>           ServerSideVerificationOptions.Builder options = new ServerSideVerificationOptions.Builder();
>                                                                                            ^
> Note: /Users/runner/work/react-native-firebase/react-native-firebase/packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobCommon.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> ```

Thank you for quick response! I made a mistake while merging codes, 3d73469a570f3d3066176a87cfea2a566ce2aaf4 will fix it.

**Comment by mikehardy** [comment]
You are fast! Android compile fixed now and running the e2e tests (thank you very much for adding those!)

This looks pretty straightforward - I think it will need some documentation in 2 spots:

https://rnfirebase.io/reference/admob/requestoptions
and 
https://rnfirebase.io/admob/displaying-ads#rewarded-ads

So people know how to use it?

**Comment by iAmGhost** [comment]
> You are fast! Android compile fixed now and running the e2e tests (thank you very much for adding those!)
> 
> This looks pretty straightforward - I think it will need some documentation in 2 spots:
> 
> https://rnfirebase.io/reference/admob/requestoptions
> and
> https://rnfirebase.io/admob/displaying-ads#rewarded-ads
> 
> So people know how to use it?

I just realized these documents are built from 

> You are fast! Android compile fixed now and running the e2e tests (thank you very much for adding those!)
> 
> This looks pretty straightforward - I think it will need some documentation in 2 spots:
> 
> https://rnfirebase.io/reference/admob/requestoptions
> and
> https://rnfirebase.io/admob/displaying-ads#rewarded-ads
> 
> So people know how to use it?

I just realized that these documents are built from source(and it looks beautiful!), I'll try to update documents on this weekend.

**Comment by Salakar** [comment]
Wow thanks for doing this @iAmGhost :)

Re the docs for `rnfirebase.io/reference/admob/requestoptions` this is generated so only need to update the types (which I think you have already).

Adding something to `rnfirebase.io/admob/displaying-ads#rewarded-ads` would be good though :)

**Comment by mikehardy** [comment]
Ah great feedback Mike - thanks. Reference docs: from types, other docs: they get the manual edits - will use that going forward

**Comment by Salakar** [comment]
Happy for the docs to be in a follow up PR if we don't want to block this functionality

**Comment by mikehardy** [comment]
Peeled docs request out to separate issue (that seemed to work well with the previous one) so this one is staged for merge, just waiting on CI. Release planned today

**Comment by mikehardy** [comment]
released!

**Pull request merged**
