### PR TITLE
Update typings for everything under lib/modules/auth

### PR DESCRIPTION
**Pull request by danielw93**
Add missing type declarations for `UserInfo`, `UpdateProfile`, `ActionCodeSettings`, `PhoneAuthSnapshot`, `PhoneAuthError` and `AuthResult`.

Add missing interface definitions for `ConfirmationResult` and `PhoneAuthListener`.

Add missing methods to interfaces `User` and `Auth`.

Update method signatures for interfaces `User` and `Auth`.

Rename type declaration `Credential` to `AuthCredential`.

The typescript declarations should now accurately reflect public method signatures of the code under `lib/modules/auth`

### CODE REVIEW

**Comment by Ehesp** [comment]
Awesome thanks for this. It was on my todo list 👀 

Will run through it tonight and get it merged!

**Comment by danielw93** [comment]
Nice :)
I have another commit ready that adds type declarations for the `links` module.
Should I add it to this PR or open a new one?

**Comment by Ehesp** [comment]
@danielw93 looks good, thanks again for this. Please do another PR for links!

**Comment by chrisbianca** [comment]
@danielw93 I think somebody might have beaten you to the punch on links: https://github.com/invertase/react-native-firebase/pull/757

Please do check though to see if there are any discrepancies between yours and the PR that has already been merged though.

**Comment by danielw93** [comment]
@Ehesp Nice! No problem :)
@chrisbianca even better! Yeah it's exactly the same as I have 👍

**Comment by chrisbianca** [comment]
Awesome! Thanks :)

**Pull request merged**
