### PR TITLE
Removed typo in docs

### PR DESCRIPTION
**Pull request by hkellaway**

### CODE REVIEW

**Comment by hkellaway** [comment]
the Contributor License Agreement link opens a page that is non-interactable for me

**Comment by hkellaway** [comment]
i cannot see why the TeamCity build failed - or imagine why. can you provide the error? thanks!

**Comment by mikehardy** [comment]
If you attempt to log in as guest on that page you should be able to get in ?

Either way this looks like something on the CI server isn't right:

```
/Users/ciuser/Library/buildAgent/temp/agentTmp/custom_script8709076470051283305: line 6: cd: tests: No such file or directory
[16:46:17]	Process exited with code 1
```

@Salakar ?

**Comment by Salakar** [comment]
CI can be ignored, I still need to run a custom flow for docs branch, currently it runs the flow for master which includes all the JS test etc which don't apply, will sort on Monday but this LGTM so am happy to merge.

Thanks for your contribution 🥳

**Pull request merged**
