### PR TITLE
Returning null as downloadUrl in upload task

### PR DESCRIPTION
**Pull request by felipewaku**
solves: #1591 using the first solution:

> 1. Still consider the invocation a success, providing downloadURL as null.

Can some maintainer help me with the new test case? I need a file with permission to upload but not to download.

### CODE REVIEW

**Comment by Salakar** [comment]
Hey, thanks a bunch for this! As requested I've added a rule that allows write only;

screenshot_20181019-195506_chrome

**Comment by felipewaku** [comment]
@Salakar Thanks for the support! Can you modify the rules to be equal to the ones provided in the issue?
```
match /writeOnly.jpge {
	allow read: if false;
	allow write: if true;
}
```

My test are failing due to an unknown error.

**Comment by Salakar** [comment]
Ok done, changed to as above. Thanks

**Comment by felipewaku** [comment]
@Salakar I adjusted my test. Can you review my code? :)

**Comment by Salakar** [comment]
@felipewaku thanks for this PR, it's great 👌 	

For successfully merging this PR you'll get added to the Collaborators for this repository, PR's are welcome :)

**Pull request merged**
