### PR TITLE
feat(inappmessaging): add support for triggering custom events

### PR DESCRIPTION
**Pull request by gilbertl**
### Description

I want to use the  programmatic event triggering feature in Firebase In App Messaging described here

https://firebase.google.com/docs/in-app-messaging/modify-message-behavior?platform=android#trigger_in-app_messages_programmatically

### Related issues

No issues.

### Release Summary

Support for In App Messaging's programmatic event triggering

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [X] Yes
- My change supports the following platforms;
  - [X] `Android`
  - [X] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`

It's not obvious how we can test whether the event was triggered.

  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`

There are no existing jest tests in the inappmessaging module

- [X] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [X] No

### Test Plan

I'm not sure how to test this ...

### CODE REVIEW

**Comment by gilbertl** [comment]
> Hi there! This is awesome, thank you for extending the API here to wrap features we hadn't exposed from the native SDKs, that's a huge help
> 
> I'm prepared to accept this, it looks good except there is a compile error right now for iOS:
> 
> ```
> ❌  /Users/runner/work/react-native-firebase/react-native-firebase/packages/in-app-messaging/ios/RNFBFiam/RNFBFiamModule.m:67:16: interface type 'NSString' cannot be passed by value; did you forget * in 'NSString'?
> 
>     (NSString) eventId
> ```
> 
> Seperately, can you think of a way to get some basic coverage on the API?
> 
> [`master`/packages/in-app-messaging/e2e/fiam.e2e.js](https://github.com/invertase/react-native-firebase/blob/master/packages/in-app-messaging/e2e/fiam.e2e.js)
> 
> At minimum exercising that it checks the argument correctly would be good, I'm not sure how I would test the actual in app message, that might not be worth it here

Fixed the NSString* issue and added a test that at least calls the new function. Not sure what I can verify in the test, but at least this will verify that the app doesn't crash on calling the function?

**Comment by mikehardy** [comment]
I think we still need the cla signed but otherwise it will probably be good to go when I reread it

**Review by mikehardy — CHANGES_REQUESTED** [review]
Looks good to me, just need you to sign the CLA or we can't merge

**Comment by gilbertl** [comment]
I think I signed it.

**Review by mikehardy — APPROVED** [review]
Excellent! Thanks @gilbertl !

**Pull request merged**
