### PR TITLE
[IOS][NOTIFICATIONS] getInitialNotification resolves last received notification

### PR DESCRIPTION
**Pull request by johankasperi**
### Summary

We are seeing an issue in our production app (using react-native-firebase#5.2.0) happening when the app has been in the background for a long time. Whats happening is that next time you bring the app to foreground (not by tapping on a received notification), `getInitialNotification` resolves the last received notification.

The bug is quite similar to the issue described in [`react-native-fcm`](https://github.com/evollu/react-native-fcm/issues/305)

After using the fixes in this PR we are not seeing this bug anymore.

### Checklist

- [ ] Supports `Android`
- [x] Supports `iOS`
- [ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
  - **LINK TO DOCS PR HERE**
- [ ] Flow types updated
- [ ] Typescript types updated

### Release Plan

[IOS][BUGFIX][NOTIFICATIONS] - getInitialNotification resolves last received notification

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](/CONTRIBUTING.md)

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! I'm helping maintain the v5 branch along with @Salakar and I believe we have CI all sorted and tests green etc so the v5 branch can tolerate change now. If you rebase to current v5.x.x and push this again, I can check into it and try to get it merged for you. @johankasperi  what do you think?

**Comment by johankasperi** [comment]
Hi Mike! Yeah I think it is better if we close this PR for now since I haven't tested the latest 5.x.x version and I cannot confirm if the bug still exists. If we see the bug again I will open a new PR

**Comment by mikehardy** [comment]
Okay - I'm closing this, but I'll admit I'll be surprised if this doesn't still happen, so if you see it feel free to reopen. Things haven't moved so far that it should be hard to shape it again and submit it, and I'll help shepherd it to a merge. Thanks!

**Comment by r4mdat** [comment]
Referencing - [#2618](https://github.com/invertase/react-native-firebase/issues/2618) PR still appears relevant/needed

**Comment by mikehardy** [comment]
@luatnd do you believe this is still valid? If you use patch-package to check it locally and it works for you we can reopen this and maybe merge it? (cross-linked from issue #2618)

**Comment by luatnd** [comment]
Yes, I patched and tested it, seem OK, but it's just my test, replied to you at #2168

**Comment by johankasperi** [comment]
Hi guys! Sorry for not being so active in this issue anymore but I'm currently not using pushnotifications from rn-firebase in any of my projects. However, I'm happy to help with any obj-c code if needed. Read #2618 and this PR might be able to solve this. But as you said, it's only for iOS.

**Pull request closed without merging**
