### PR TITLE
fix!(auth): confirm code returns User instead of UserCredential

### LINKED ISSUE #2543: SMS auth flow response of confirm verification code is invalid
##  Issue
Hello guys, I'm trying to implement signing with SMS provider and I found response mismatch.
If we try to confirm verification code we will get User object (like described in docs: https://rnfirebase.io/docs/v5.x.x/auth/reference/ConfirmationResult#confirm).
In my POV it's not correct, because it's not a added value and you're not passing more needed data like `isNewUser` flag.

As you can see in official Firebase docs this method should return `UserCredentials` (https://firebase.google.com/docs/reference/js/firebase.auth.ConfirmationResult#confirm)

I checked your native code and it's doable because you're passing only user object without `additionalUserInfo` (see the link to ios code: https://github.com/invertase/react-native-firebase/blob/master/packages/auth/ios/RNFBAuth/RNFBAuthModule.m#L728 and android: https://github.com/invertase/react-native-firebase/blob/master/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L956)

Hope it does make sense to you!

### PR DESCRIPTION
**Pull request by gwenoleR**
BREAKING CHANGE: `confirm(verificationCode)` now return `UserCredentials`

### Description

Actually the Phone provider do not follow the Firebase Web SDK.
The [docs](https://firebase.google.com/docs/reference/node/firebase.auth.ConfirmationResult?authuser=0#confirm) said the confirm method should return an `UserCredential` and not only an `User`.
 
### Related issues
Related to [this issue](https://github.com/invertase/react-native-firebase/issues/2543)
Fixes #2543 

### Checklist

- I read the [Contributor Guide](/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [x] `Android`
  - [x] `iOS`
- My change includes tests;
  - [x] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [x] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [x] Yes
  - [ ] No

### Need help

The method now return a UserCredential, but i have a curious issue. When I log the result using for exemple there few lines of code : 
```
const result = await firebaseConfirmation.confirm(code)
console.log(result)
```
I have the expected result : 
```
{"additionalUserInfo": {"isNewUser": false, "profile": null, "providerId": "phone", "username": null}, "user": {"displayName": "Gwénolé", "email": null, "emailVerified": false, "isAnonymous": false, "metadata": [Object], "phoneNumber": "...", "photoURL": null, "providerData": [Array], "providerId": "firebase", "refreshToken": "...", "uid": "..."}}
```
But when I try to consume, for exemple the `isNewUser` I've got undefined..

I tried to list keys of the object and I have for result 
```
console.log(Object.keys(result))
> ["_auth", "_user"]
```

I think i missed something but i don't know what..
I can only consume the `isNewUser` using : 
```
const isNewUser = result._user.additionalUserInfo.isNewUser
```
🔥

### CODE REVIEW

**Comment by Salakar** [comment]
Awesome, thanks for sorting this - once CI passes I can ship this straight away 🤓

**Comment by gwenoleR** [comment]
Oh yes, `_setUserCredential` obviously does the trick.. 
Work nice on my side 👌

**Comment by gwenoleR** [comment]
Hum, CI failed because of a timeout operation 🤔 
Anyone have any idea what's going on?

**Comment by mikehardy** [comment]
@gwenoleR that's unexpected, of course. I asked Github to rerun all jobs. It was an auth change and the auth seemed to be the problem? So it might be a false-negative but may also be a real issue. We'll see if it reproduces

**Comment by Salakar** [comment]
Shipped in https://github.com/invertase/react-native-firebase/commit/8b72876c749373af4424c68309afb2cea8dc2f07

Thanks :)

**Comment by Manoj002** [comment]
Is the change applicable for older versions too, as im still getting only user object after
`.confirm(verificationCode)`
and error too sms expired.

can anyone please help

**Comment by gwenoleR** [comment]
Hi @Manoj002, this fix make a breaking change, so you must use the v8.0.0 of the auth package

**Comment by chellongCoder** [comment]
i am using **com.google.firebase:firebase-auth:19.3.1**, but when I received otp code, I click notification to move to messenger, but when comeback to app, my otp code is submited responsed the error **The sms verification code used to create the phone auth credential is invalid. Please resend the verification code sms and be sure use the verification code provided by the user.**
any fixed? :(( thanks

**Comment by mikehardy** [comment]
@chellongCoder you are adding a comment not to an issue, but a pull request, and it's a merged/closed one at that.
Read the docs on the auth module on the main doc page where it talks about implementing the auth listener for android to handle the "android auto-verified my one time code" case. That one trips up a lot of people and results in errors like the one you mention. If it doesn't work, open a new issue and fill in the template for support

**Pull request merged**
