### PR TITLE
feat!: Update Firebase iOS SDK version to v11

### PR DESCRIPTION
**Pull request by Salakar**
This is a breaking change since the minimum version of iOS and macOS has changed

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [ ] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [ ] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Review by mikehardy — COMMENTED** [review]
oh darn - I was hoping this was non-breaking but forgot about the bumps to the min supported version on platforms, quite right on that one

podspecs and docs may not be inline with regards to minimums speced in podfile and/or described as supported in docs - haven't scanned

code may have `@available` branches that are no longer applicable as new minimum means previous checked ver is always available, could use a grep for available perhaps

test app may need xcproj update to change min supported ?

that's all I can think of as those things bump...

**Comment by mikehardy** [comment]
Task was to determine what was causing storage emulator to crash the app on iOS

- updated all the dependencies so software was current since this was likely some sort of upstream issue, perhaps current emulator and current firebase-ios-sdk played nicer together?
- - this required strong typings on the functions calls now, so quickly forward-ported those to current signatures and v2 functions where possible
- - this required a couple little fixes to the functions deploy so the new functions were in the cloud as needed (with new V2 names)
- storage test helpers manual rule push now had a type error, but it looks like the storage emulator is correctly ingesting the rules from storage rules json so just deleted those
- ✅  root cause was a bunch of [upstream firebase-ios-sdk storage init changes](https://github.com/firebase/firebase-ios-sdk/commits/main/FirebaseStorage) where they were trying to eliminate [some data race](https://github.com/firebase/firebase-ios-sdk/issues/13369) and now more strongly guard against misconfigured storage instances (emulator vs non-emulator) which were happily data-racing past before it seems

While I was there I took care of my own review comments and bumped firebase-android-sdk:
- updated docs with new minimums
- eliminated dead code paths on iOS guarded by `@available` checks that are always available with new minimum iOS target
- verified podspecs were enforcing things correctly

I think this is good to go? It passed e2e tests locally now and I reproduced the earlier failure. Hopefully CI agrees.

**Comment by witcher-shailesh** [comment]
If the PR looks fine, can we merge and release a new version? 

We are facing issues with latest versions of iOS 😞

**Comment by mikehardy** [comment]
@witcher-shailesh well, sure - but you realize it only looks fine since approx 12 hours ago and that was me just hammering on it without review 😆 . It's in review today :-)

**Comment by mikehardy** [comment]
@witcher-shailesh there are a variety of ways to get things early:
- the linked issue has two patch-package formatted patches required to work with firebase-ios-sdk 11+ in combination with overriding the SDK value in Podfile like so https://rnfirebase.io/#ios
- you can also override the Podfile iOS SDK value like that https://rnfirebase.io/#ios and use the linked patch set we auto-build on each PR here https://github.com/invertase/react-native-firebase/actions/runs/11025048103?pr=8028

**Review by exaby73 — APPROVED** [review]

**Review by mikehardy — APPROVED** [review]

**Pull request merged**
