### PR TITLE
Implement Firebase Remote Config for iOS

### PR DESCRIPTION
**Pull request by akshetpandey**
Initial implementation added for feedback

I am not sure how to add tests or android support yet

Also the function documentation format might be broken, it there a doc somewhere on how to write those?

### CODE REVIEW

**Comment by Ehesp** [comment]
Hey,

Looks good! Thanks.

Please can you add the documentation for this. @Salakar will implement the Android side :)

**Comment by Ehesp** [comment]
@akshetpandey I've now implemented this on Android. Changed a few things around for android/ios compatibility (error codes, method names etc). Thanks again!

**Comment by D1no** [comment]
@Ehesp that is awesome! When will it land on npm? We are just about switching all our conditionals to remote config - and this helps a lot. Again, great work and great project!

**Comment by Salakar** [comment]
@D1no just released to npm. v1.1.0

**Comment by Salakar** [comment]
@D1no also, the docs are here: http://invertase.io/react-native-firebase/#/modules/config

**Comment by D1no** [comment]
@Salakar just saw it. Thanks for that from Berlin ❤️

**Pull request merged**
