### PR TITLE
feat(analytics, ATT): allow use of AnalyticsWithoutAdIdSupport pod

### PR DESCRIPTION
**Pull request by mikehardy**
### Description

Allow use of new Analytics subspec that gets you Analytics without the Ad Id usage (thus no need for Apple App Transparency Tracking)

### Related issues

Discussion here https://github.com/invertase/react-native-firebase/discussions/5223

### Release Summary

2 conventional commits, can be rebase merged

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

- test with firebase-ios-sdk 7.10.0 and using new podspec variable (should fail, does fail :heavy_check_mark: )
- test with firebase-ios-sdk 7.11.0, using new variable, with admob too (should fail, does fail :heavy_check_mark: )
- test with firebase-ios-sdk 7.11.0 using new variable, no admob (should use new subspec, works :heavy_check_mark:  )

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by Salakar** [comment]
Ruby code looks ok to me so not sure why it's not picking it up. Also I think it'd be worth having this mentioned in the analytics documentation somewhere

**Review by lastthyme — APPROVED** [review]

**Comment by mikehardy** [comment]
I will definitely put it in the docs - once it works :-)

**Comment by mikehardy** [comment]
Tested and all appears to work today as I took this up again, so I think it's ready to go technically.
Added a nice documentation chunk on the analytics install that explains why you would want this,
how to do it, minimum firebase-ios-sdk requirement, AdMob incompatibility and everything

**Comment by mikehardy** [comment]
Last change was moving the entire documentation block to a top-level header (instead of inside the firebase.json block as a sub-head), everything else was green -> merging

**Pull request merged**
