### PR TITLE
fix(messaging, ios): fixed isHeadless for react-native-navigation

### PR DESCRIPTION
**Pull request by Beat-YT**
### Related issues

fixes https://github.com/invertase/react-native-firebase/issues/6429

### Release Summary

Moved the setter of `isHeadless` to before the check for rctView that does not exists on *react-native-navigation*

image

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [x] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

I sent a remote notification with content-available to true, and then I also opened the app before it shut itself down to test that it does set itself to false as well.
image

p.s: Sorry for the double pull request, I read through the CONTRIBUTING.md a bit too fast 😅

### CODE REVIEW

**Comment by Beat-YT** [comment]
@mikehardy Can you take a look?

**Comment by Beat-YT** [comment]
Well it’s not my fault if no one looks at it

**Comment by Beat-YT** [comment]
@mikehardy you said you’d approve such pull request a while back to fix the issue, can you take a look at this please.

**Review by russellwheatley — CHANGES_REQUESTED** [review]
@Beat-YT - seems fair enough to me. Need to fix linting failure. There's a script in package.json you need to run: `yarn lint:ios:fix`. Waiting for CI run to see what else pops up.

**Comment by Beat-YT** [comment]
@russellwheatley I have fixed linting failure a you requested.

**Comment by Beat-YT** [comment]
Can you check this out @russellwheatley

**Review by russellwheatley — APPROVED** [review]

**Review by Lyokone — APPROVED** [review]

**Comment by russellwheatley** [comment]
As an FYI; I ran app and tested messages in foreground and background which worked as intended. There are no ways to test this e2e so it was a manual check.

**Pull request merged**
