### PR TITLE
feat(android,ios): upgrade native SDK versions

### PR DESCRIPTION
**Pull request by andersonaddo**
I did this mostly to solve #3614 for everyone. Is this all that's required?

I think this should be fine, since the [tests already override to SDK v6.27.0](https://github.com/invertase/react-native-firebase/blob/65042d08ed1233cfdb35b6c2d51d87be2d305d3c/tests/ios/Podfile#L7).

Looking at the [changelog](https://firebase.google.com/support/release-notes/ios#cloud-firestore), I think the only changes that might change the dev experience are:

[Installations change 3](https://firebase.google.com/support/release-notes/ios#installations_2)

[Remote Config change 1](https://firebase.google.com/support/release-notes/ios#remote-config_1)

[Storage change 2](https://firebase.google.com/support/release-notes/ios#storage)

### CODE REVIEW

**Comment by andersonaddo** [comment]
Doesn't look like there's been a new BoM for Android since 25.5.0

**Comment by Salakar** [comment]
Thanks for this, LGTM, though could you change https://github.com/invertase/react-native-firebase/blob/master/packages/app/package.json#L70 as well, thanks

**Comment by andersonaddo** [comment]
Added the Android upgrade.
Note that this drops support for Gradle v4

**Comment by mikehardy** [comment]
I think gradle is on v6 now, so that's okay, react-native hasn't been on v4 for a while? Should be fine?
Ah wait! https://github.com/facebook/react-native/commit/b4017a9923b09fed4b693a8e4cfadd30ce34c88d

react-native 0.60 was the first to use it. So there are a few people using RNFBv6+ with RN59-, they need a warning that they will have to override things, so this is a major version bump for android :-)

But version numbers are free! Just needs a changelog entry warning IMHO

**Comment by Salakar** [comment]
LGTM

I wonder if we even need to major version this, I thought v6 was RN 60 min with 59 as "it works" - can't find the support table anywhere though 🙈 so can't confirm

**Comment by mikehardy** [comment]
I think you are right, if RN59 is not officially supported, you could just put a very obvious change note for RN59 people. That seems friendly enough. It's a fail-fast as well they'll find out quite quickly, not like an obscure prod only runtime issue

**Pull request merged**
