### PR TITLE
Realtime database suggestions

### LINKED ISSUE #3836: Firebase Realtime Database snapshot.forEach was not display suggestions
스크린샷 2020-06-25 오후 11 04 56

Maybe Functions is Problem..

[https://github.com/invertase/react-native-firebase/issues/3823](url)
i think same problem

This is Firebase Database Admin ts
스크린샷 2020-06-25 오후 11 10 09

Then i Fixed it. suggestion work.
스크린샷 2020-06-25 오후 11 13 32

how can i push this code?..

### PR DESCRIPTION
**Pull request by Eumhongin**
fix #3836  #3823

### CODE REVIEW

**Comment by Eumhongin** [comment]
i just pull request for realtime database, but why ios failed log for auth?
스크린샷 2020-06-26 오전 11 26 39

**Comment by mikehardy** [comment]
Perhaps because CI has run too many times in too short a time. This happens. If you retrigger those actions later it will probably succeed

**Comment by Eumhongin** [comment]
> Perhaps because CI has run too many times in too short a time. This happens. If you retrigger those actions later it will probably succeed

Thanks!!!

**Comment by Eumhongin** [comment]
> Perhaps because CI has run too many times in too short a time. This happens. If you retrigger those actions later it will probably succeed

Why Error in android MLKit?? i just modifing realtime database ts

**Comment by andersonaddo** [comment]
@Eumhongin don't forget about the CLA 😉

**Comment by Eumhongin** [comment]
> @Eumhongin don't forget about the CLA 😉

스크린샷 2020-06-28 오전 12 12 16


I also signin CLA but github does not know yet?

**Pull request closed without merging**
