### PR TITLE
fix(analytics): added a validation for length in analytics().logEvent(name, params)

### LINKED ISSUE #4496: Needs to check the length of name for a method "logEvent(name, params)".
https://github.com/invertase/react-native-firebase/blob/81c4e3b7d2ce956ed6a2cc2f40a323ec5379d6a1/packages/analytics/lib/index.js#L79-L83

Here, there is a message string to restrict length of name, but in fact, it does not check the length of the name.
'... Names should contain 1 to 32 alphanumeric characters or underscores.'

Moreover, the limit of the name is 40, which is not 32.
Reference: https://firebase.google.com/docs/reference/cpp/group/event-names#summary

### PR DESCRIPTION
**Pull request by railsjack**
### Description
I added a validation to check the length for `name` of `analytics().logEvent(name, params)`: 1-40 alphanumeric

### Related issues

Fixes #4496 

### Checklist

- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
  - [x] Yes
- My change supports the following platforms;
  - [ ] `Android`
  - [ ] `iOS`
- My change includes tests;
  - [ ] `e2e` tests added or updated in `packages/\*\*/e2e`
  - [ ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ ] I have updated TypeScript types that are affected by my change.
- This is a breaking change;
  - [ ] Yes
  - [x] No

### Test Plan

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Star this repo on GitHub ⭐️
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter

### CODE REVIEW

**Comment by mikehardy** [comment]
Looks like the test needs an update as well:

> Expected substring: "firebase.analytics().logEvent(*) 'name' invalid event name '!@£$%^&*'. Names should contain 1 to 32 alphanumeric characters or underscores."

at packages/analytics/__tests__/analytics.test.ts:162:41

**Review by mikehardy — CHANGES_REQUESTED** [review]
This looks good - just the CLA sign and the test update

**Comment by railsjack** [comment]
I am not sure why Vercel has failed.

**Comment by mikehardy** [comment]
I'm not sure why Vercel is failing either 😅 - obviously has nothing to do with this PR though, I can merge without it passing

**Review by mikehardy — APPROVED** [review]
This will pass now (or should...) I believe we're just missing the CLA now to merge

**Comment by railsjack** [comment]
Thank you, Mike.

**Comment by mikehardy** [comment]
Still missing the CLA signature though 🤔  @railsjack

**Comment by railsjack** [comment]
What should I do to pass it?

**Comment by mikehardy** [comment]
@railsjack - follow the details link, should be https://cla-assistant.io/invertase/react-native-firebase?pullRequest=4522 - and sign the request with the same github userid / email used to make the PR

**Comment by railsjack** [comment]
Done.

**Comment by mikehardy** [comment]
Fantastic - thanks for submitting this in the first place and sticking with it through all the administrivia bits :-)

**Pull request merged**
